import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
process.env.DATA_FOLDER = fs.mkdtempSync(path.join(os.tmpdir(), 'apiotp-'));
process.env.API_JWT_SECRET = 'test-secret-test-secret-test-secret';
const {createHandler} = await import('../src/api/server.js');
const {createKey} = await import('../src/api/services/keys.js');
const {setOtpSender} = await import('../src/api/services/otpService.js');
const srv = http.createServer(createHandler()); await new Promise((r) => srv.listen(0, '127.0.0.1', r)); const port = srv.address().port;
const call = (key, body) => new Promise((resolve, reject) => { const d = JSON.stringify(body); const req = http.request({host: '127.0.0.1', port, method: 'POST', path: '/api/v1/portal/otp', headers: {...(key ? {'x-api-key': key} : {}), 'content-type': 'application/json', 'content-length': Buffer.byteLength(d)}}, (res) => { let b = ''; res.on('data', (c) => (b += c)); res.on('end', () => resolve({status: res.statusCode, json: JSON.parse(b || '{}')})); }); req.on('error', reject); req.end(d); });
test.after(() => { srv.close(); setTimeout(() => process.exit(0), 50).unref(); });
test('portal otp: key required, strict input, fixed sender args, per-number rate limit', async () => {
  const sent = []; setOtpSender(async (n, c) => { sent.push([n, c]); return true; });
  const ro = createKey('r', 'readonly'), sv = createKey('s', 'service');
  assert.equal((await call(null, {number: '919876543210', code: '123456'})).status, 401);
  assert.equal((await call(ro.key, {number: '919876543210', code: '123456'})).status, 403);
  assert.equal((await call(sv.key, {number: '12', code: '123456'})).status, 400);
  assert.equal((await call(sv.key, {number: '919876543210', code: 'hello world'})).status, 400);
  assert.equal((await call(sv.key, {number: '919876543210', code: '123456'})).status, 200);
  assert.deepEqual(sent, [['919876543210', '123456']]);
  assert.equal((await call(sv.key, {number: '919876543210', code: '654321'})).status, 429);
  setOtpSender(async () => false);
  assert.equal((await call(sv.key, {number: '919111111111', code: '111111'})).status, 503);
});
