import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import AdmZip from 'adm-zip';
import {validateApkUrl,manifestPackage,inspectApk,ApkError}from '../src/commands/apk/validation.js';import{parseFdroidSearch,parseMirrorSearch}from '../src/commands/apk/search.js';import{parseFdroidInfo}from '../src/commands/apk/info.js';import{boundedGet,limitApk}from '../src/commands/apk/utility.js';
function manifest(id='org.test.app'){const values=['manifest','package',id],parts=values.map(s=>Buffer.concat([Buffer.from([s.length,s.length]),Buffer.from(s),Buffer.from([0])]));const pool=Buffer.alloc(28+12+parts.reduce((n,p)=>n+p.length,0));pool.writeUInt16LE(1);pool.writeUInt16LE(28,2);pool.writeUInt32LE(pool.length,4);pool.writeUInt32LE(3,8);pool.writeUInt32LE(0x100,16);pool.writeUInt32LE(40,20);let pos=40;parts.forEach((p,i)=>{pool.writeUInt32LE(pos-40,28+i*4);p.copy(pool,pos);pos+=p.length;});const elem=Buffer.alloc(56);elem.writeUInt16LE(0x102);elem.writeUInt16LE(16,2);elem.writeUInt32LE(56,4);elem.writeUInt32LE(0,20);elem.writeUInt16LE(20,24);elem.writeUInt16LE(20,26);elem.writeUInt16LE(1,28);elem.writeUInt32LE(0xffffffff,36);elem.writeUInt32LE(1,40);elem.writeUInt32LE(2,44);elem.writeUInt16LE(8,48);elem[51]=3;elem.writeUInt32LE(2,52);const header=Buffer.alloc(8);header.writeUInt16LE(3);header.writeUInt16LE(8,2);header.writeUInt32LE(8+pool.length+elem.length,4);return Buffer.concat([header,pool,elem]);}
test('APK official URLs reject unsafe hosts, schemes, credentials, queries and bundles',()=>{assert.equal(validateApkUrl('https://f-droid.org/repo/org.test.app_12.apk').packageName,'org.test.app');for(const s of ['http://f-droid.org/repo/org.test.app_12.apk','https://f-droid.org.evil/repo/org.test.app_12.apk','https://u:p@f-droid.org/repo/org.test.app_12.apk','https://f-droid.org:99/repo/org.test.app_12.apk','https://f-droid.org/repo/org.test.app_12.apk?x=y','https://f-droid.org/repo/org.test.app_12.apkm','https://127.0.0.1/repo/org.test.app_12.apk'])assert.throws(()=>validateApkUrl(s),ApkError);});
test('Android binary manifest identity parser rejects truncated/plain/spoofed manifests',()=>{assert.equal(manifestPackage(manifest()),'org.test.app');for(const b of [Buffer.from('<manifest package="org.test.app"/>'),manifest().subarray(0,25),Buffer.alloc(40)])assert.throws(()=>manifestPackage(b));});
test('APK ZIP identity, size, SHA256, paths and decompression are checked',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'apk-test-'));try{const f=path.join(dir,'a.apk');const z=new AdmZip();z.addFile('AndroidManifest.xml',manifest());z.addFile('classes.dex',Buffer.from('dex\n035\0'));z.writeZip(f);const a=await inspectApk(f,{expectedPackage:'org.test.app'});assert.equal(a.packageName,'org.test.app');assert.match(a.sha256,/^[a-f0-9]{64}$/);await assert.rejects(inspectApk(f,{expectedPackage:'org.other.app'}),ApkError);await assert.rejects(inspectApk(f,{maxBytes:10}),ApkError);await fs.writeFile(f,'<html>not an apk</html>'.repeat(10));await assert.rejects(inspectApk(f),ApkError);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('official metadata parsers retain source and suggested stable version',()=>{assert.equal(parseFdroidSearch('<a class="package-header" href="https://evil.test/en/packages/org.test.app"><h4 class="package-name">bad</h4></a>').length,0);assert.equal(parseFdroidSearch('<a class="package-header" href="https://f-droid.org/en/packages/org.test.app"><h4 class="package-name">Notes</h4></a>')[0].packageName,'org.test.app');const html='<h3 class="package-name">App</h3><li class="package-version"><a name="5"></a><p class="package-version-download"><a href="https://f-droid.org/repo/org.test.app_5.apk">Download</a></p></li>';const a=parseFdroidInfo(html,{packageName:'org.test.app',suggestedVersionCode:5,packages:[{versionCode:9,versionName:'beta'},{versionCode:5,versionName:'stable'}]},'org.test.app');assert.equal(a.versionName,'stable');assert.throws(()=>parseFdroidInfo(html,{packageName:'org.bad.app'},'org.test.app'));assert.throws(()=>parseMirrorSearch('<title>Just a moment...</title>'),ApkError);});
test('bounded requests reject overflow, redirects, bad MIME, blocks and preserve cleanup',async()=>{await assert.rejects(boundedGet('https://evil.test/f'),ApkError);await assert.rejects(boundedGet('https://f-droid.org/test',{maxBytes:2,fetchImpl:async()=>new Response('123')}),ApkError);await assert.rejects(boundedGet('https://f-droid.org/test',{fetchImpl:async()=>new Response('blocked',{status:403})}),ApkError);await assert.rejects(boundedGet('https://f-droid.org/test',{types:['application/zip'],fetchImpl:async()=>new Response('html',{headers:{'content-type':'text/html'}})}),ApkError);let redirect;await boundedGet('https://f-droid.org/test',{fetchImpl:async(u,o)=>{redirect=o.redirect;return new Response('ok');}});assert.equal(redirect,'error');});
test('APK rate limits are explicit',()=>{limitApk('test-user',1000);limitApk('test-user',1001);limitApk('test-user',1002);assert.throws(()=>limitApk('test-user',1003),ApkError);limitApk('test-user',62000);});
test('all four isolated APK command entrypoints load',async()=>{for(const n of ['apk','apksearch','apkinfo','apkdownload']){const c=(await import('../src/commands/'+n+'.js')).default;assert.equal(c.name,n);assert.equal(c.minArgs,1);}});
test('download failure deletes partial temporary output',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'apk-partial-')),dest=path.join(dir,'a.apk');try{await assert.rejects(boundedGet('https://f-droid.org/test',{dest,maxBytes:2,fetchImpl:async()=>new Response('abcdef')}),ApkError);await assert.rejects(fs.stat(dest));}finally{await fs.rm(dir,{recursive:true,force:true});}});
