import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {validateEdition,select,readingPages,chunks,contents} from '../src/books/library.js';
// Generic fixtures are not scripture and will never be installed as books.
function fixture(){const full=Buffer.from('fixture α\nfixture β');return {full,index:{schema:1,id:'fixture',title:'Test fixture',language:'Test',edition:'Fixture only',rights:'Fixture',sources:['https://example.org/fixture'],fullSha256:crypto.createHash('sha256').update(full).digest('hex'),counts:{books:1,chapters:1,verses:2},books:[{number:1,name:'Fixture',chapters:[{number:1,verses:[{number:1,text:'fixture α'},{number:2,text:'fixture β'}]}]}]}};}
test('full book digest and exact edition completeness required',()=>{const{index,full}=fixture();assert.equal(validateEdition(index,full),index);assert.throws(()=>validateEdition(index,Buffer.from('changed')),/integrity/);index.counts.verses=3;assert.throws(()=>validateEdition(index,full),/completeness/);});
test('invalid/missing verses are rejected and no substitute text generated',()=>{const{index}=fixture();assert.equal(select(index,{chapter:1,first:2}).verses[0].text,'fixture β');for(const ref of [{chapter:2},{chapter:1,last:3},{chapter:1,first:2,last:1},{chapter:0},{chapter:1,book:2}])assert.throws(()=>select(index,ref));assert.equal(contents(index)[0].chapters,1);});
test('navigation labels edition/source and preserves verbatim text',()=>{const{index}=fixture();const pages=readingPages(index,{chapter:1});assert.equal(pages[0].body,'1:1:1\nfixture α\n\n1:1:2\nfixture β');assert.match(pages[0].edition,/Fixture only/);assert.match(pages[0].edition,/https:\/\/example.org/);});
test('bounded unicode pages lose no characters or surrogate pairs',()=>{const value='α😀بक\n'.repeat(2000),parts=chunks(value,200);assert.equal(parts.join(''),value);assert.ok(parts.every(p=>Array.from(p).length<=200));assert.throws(()=>chunks(value,5000));});
test('actual verified editions load with complete independent counts and canonical samples',async()=>{const{loadEdition}=await import('../src/books/library.js');const q=await loadEdition('./assets/books','quran'),g=await loadEdition('./assets/books','gita'),b=await loadEdition('./assets/books','bible');assert.deepEqual(q.index.counts,{books:1,chapters:114,verses:6236});assert.deepEqual(g.index.counts,{books:1,chapters:18,verses:700});assert.deepEqual(b.index.counts,{books:66,chapters:1189,verses:31103});assert.equal(q.index.books[0].chapters[0].verses[0].text,'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ');assert.match(g.index.books[0].chapters[1].verses[46].text,/कर्मण्येवाधिकारस्ते/);assert.match(b.index.books[0].chapters[0].verses[0].text,/In the beginning, God created the heavens and the earth\./);const note=b.index.books[41].chapters[16].verses[35];assert.equal(note.noteOnly,true);assert.equal(note.text,'');assert.match(note.notes[0],/Some Greek manuscripts/);});
test('book command reading and full files keep edition/source and exact full bytes',async()=>{const{bookCommand}=await import('../src/books/command.js');const{loadEdition}=await import('../src/books/library.js');const replies=[],sent=[];const ctx={jid:'test-reader',sender:'reader',args:['2','47'],reply:async t=>replies.push(t),sock:{sendMessage:async(...a)=>sent.push(a)},msg:{}};await bookCommand('gita').run(ctx);assert.match(replies[0],/Sanskrit/);assert.match(replies[0],/कर्मण्येवाधिकारस्ते/);assert.ok(!replies[0].includes('रामानुजभाष्यम्'));await bookCommand('quran').run({...ctx,args:['full']});const{full}=await loadEdition('./assets/books','quran');assert.ok(sent[0][1].document.equals(full));assert.match(sent[0][1].caption,/Tanzil/);});
