import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Economy} from '../src/economy/store.js';
test('virtual balances atomically persist cooldowns and conserved transfers',()=>{let now=1000;const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'econ-')),'e.json');const e=new Economy(file,()=>now),a='14155551234@s.whatsapp.net',b='14155551235@s.whatsapp.net';assert.equal(e.award(a,'daily').balance,100);assert.throws(()=>e.award(a,'daily'),/cooldown/);assert.equal(e.pay(a,b,25),75);assert.equal(e.user(b).balance,25);assert.throws(()=>e.pay(a,b,100),/Insufficient/);assert.throws(()=>e.pay(a,a,1),/yourself/);assert.throws(()=>e.pay(a,b,1.2),/whole/);assert.equal(new Economy(file).user(a).balance,75);now+=86400000;assert.equal(e.award(a,'daily').balance,175);});
test('corrupt economy fails closed rather than resets wealth',()=>{const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'econ-')),'e.json');fs.writeFileSync(file,'bad');const e=new Economy(file);assert.throws(()=>e.award('14155551234@s.whatsapp.net','earn'),/unavailable/);assert.equal(fs.readFileSync(file,'utf8'),'bad');});
test('schema validation rejects tampered balance and replay-safe transactions survive restart',()=>{const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'eco-')),'eco.json');const a='14155550123@s.whatsapp.net',b='14155550124@s.whatsapp.net';const e=new Economy(file,()=>200000000);e.award(a,'daily','msg-one');assert.throws(()=>e.pay(a,b,1,'msg-one'),/already processed/);assert.equal(e.user(a).balance,100);e.pay(a,b,10,'msg-two');const next=new Economy(file);assert.throws(()=>next.pay(a,b,10,'msg-two'),/already processed/);assert.equal(next.user(a).balance,90);const data=JSON.parse(fs.readFileSync(file));data.users[e.id(a)].balance=-1;fs.writeFileSync(file,JSON.stringify(data));const corrupt=new Economy(file);assert.throws(()=>corrupt.user(a),/unavailable/);assert.throws(()=>corrupt.pay(a,b,1),/unavailable/);});
test('reward rules validated, reads do not expose mutation and failed rules preserve balances',()=>{const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'eco-')),'eco.json');const e=new Economy(file,()=>200000000);const a='14155550123@s.whatsapp.net';e.award(a,'daily');assert.throws(()=>e.configure('daily',-1));assert.equal(e.rules().daily,100);e.configure('daily',500);const u=e.user(a);u.achievements.push('hacked');assert.equal(e.user(a).achievements.length,1);assert.throws(()=>e.configure('maxBalance',99));assert.equal(e.user(a).balance,100);});
test('atomic persist failure does not claim a reward or debit',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'econ-fail-'));const file=path.join(dir,'e.json');const e=new Economy(file,()=>1000);fs.mkdirSync(file+'.tmp');const a='14155551234@s.whatsapp.net';assert.throws(()=>e.award(a,'daily'));assert.equal(e.user(a).balance,0);assert.ok(!fs.existsSync(file));});
test('persisted history schema cannot carry arbitrary private strings',()=>{const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'eco-schema-')),'e.json');const e=new Economy(file,()=>200000000);e.award('14155550123@s.whatsapp.net','daily');const data=JSON.parse(fs.readFileSync(file));data.history[0].private='secret';fs.writeFileSync(file,JSON.stringify(data));const corrupt=new Economy(file);assert.throws(()=>corrupt.user('14155550123@s.whatsapp.net'),/unavailable/);});

test('persisted transfer cooldown cannot be bypassed by restart',()=>{const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'eco-abuse-')),'e.json');let now=200000000;const e=new Economy(file,()=>now),a='14155550123@s.whatsapp.net',b='14155550124@s.whatsapp.net';e.award(a,'daily');e.pay(a,b,1,'first');assert.throws(()=>new Economy(file,()=>now).pay(a,b,1,'second'),/cooldown/);now+=2001;assert.equal(e.pay(a,b,1,'third'),98);});

test('daily transfer limit survives restart and resets only next UTC day',()=>{const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'eco-day-')),'e.json');let now=200000000;let e=new Economy(file,()=>now);const a='14155550123@s.whatsapp.net',b='14155550124@s.whatsapp.net';e.configure('daily',1000);e.award(a,'daily');for(let i=0;i<100;i++){now+=2001;e.pay(a,b,1,'unit-'+i);}now+=2001;e=new Economy(file,()=>now);assert.throws(()=>e.pay(a,b,1,'over-limit'),/Daily transfer limit/);assert.equal(e.user(a).balance,900);now+=86400000;assert.equal(e.pay(a,b,1,'next-day'),899);});
