import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import sharp from 'sharp';import {Readable} from 'node:stream';
import {freeEnhance,freeProviderUrl,validateFreeInput,codeFormerSize,CODEFORMER_SPACE} from '../src/services/freeImageProviders.js';import {providerStatus} from '../src/services/imageEnhancer.js';import {parseEnhance} from '../src/commands/_enhance.js';
async function fixture(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'free-image-'));const input=path.join(dir,'in.png');await sharp({create:{width:32,height:24,channels:3,background:'#abccba'}}).png().toFile(input);const png=await sharp(input).resize(64,48).png().toBuffer();const cfPng=await sharp(input).resize(codeFormerSize({width:32,height:24},2)).png().toBuffer();const env={REMINI_BUDGET_FILE:path.join(dir,'budget.json'),REMINI_CODEFORMER_ENABLED:'true',REMINI_CODEFORMER_BUDGET:'2',REMINI_SNAPEDIT_ENABLED:'true',REMINI_SNAPEDIT_BUDGET:'10',SNAPEDIT_API_KEY:'mock'};try{await fn({dir,input,png,cfPng,env});}finally{await fs.rm(dir,{recursive:true,force:true});}}
const resultUrl=CODEFORMER_SPACE+'/gradio_api/file=/tmp/gradio/abc/result.png';
function mockClient(events,observe=()=>{}){return async(url,opts)=>{observe({url,opts});return{view_api:async()=>({named_endpoints:{'/inference':{parameters:['image','face_align','background_enhance','face_upsample','upscale','codeformer_fidelity'].map(parameter_name=>({parameter_name}))}}}),submit:(name,data)=>{observe({name,data});return{cancel:async()=>{},async *[Symbol.asyncIterator](){for(const e of events)yield e;}};},close:()=>observe({closed:true})};};}
test('new command choices remain explicit, privacy yes required',()=>fixture(async({dir,input,env})=>{assert.equal(parseEnhance(['codeformer','2','yes'],'upscale').provider,'codeformer');assert.equal(parseEnhance(['snapedit','4'],'upscale').allowDisclosure,false);await assert.rejects(freeEnhance(input,dir,{provider:'codeformer',env}),e=>e.code==='CONSENT');}));
test('output URLs allow exact source-owned host only',()=>{assert.equal(freeProviderUrl(resultUrl,'codeformer'),resultUrl);for(const u of ['https://evil.test/a','https://sczhou-codeformer.hf.space.evil/a','https://sczhou-codeformer.hf.space/admin','http://sczhou-codeformer.hf.space/gradio_api/file=a','https://u:p@outputs.snapedit.app/a'])assert.throws(()=>freeProviderUrl(u,'codeformer'));assert.equal(freeProviderUrl('https://outputs.snapedit.app/outputs/test.png','snapedit'),'https://outputs.snapedit.app/outputs/test.png');assert.equal(freeProviderUrl('https://api-outputs.snapedit.app/outputs/test.png','snapedit'),'https://api-outputs.snapedit.app/outputs/test.png');assert.throws(()=>freeProviderUrl('https://api-outputs.snapedit.app.evil.test/a','snapedit'));});
test('source scale clamp constraints and SnapEdit size limit checked before upload',()=>{assert.throws(()=>validateFreeInput({width:1200,height:800},'codeformer',4));assert.throws(()=>validateFreeInput({width:1501,height:900},'snapedit',2));assert.throws(()=>validateFreeInput({width:100,height:100},'codeformer',1));assert.deepEqual(validateFreeInput({width:1000,height:900},'codeformer',4),{width:4000,height:3600});});
test('CodeFormer anonymous Gradio submit uses pinned endpoint and downloads immediately',()=>fixture(async({dir,input,cfPng,env})=>{const observed=[];const a=await freeEnhance(input,dir,{provider:'codeformer',allowDisclosure:true,env,connect:mockClient([{type:'data',data:[{url:resultUrl}]}],o=>observed.push(o)),request:async o=>{assert.equal(o.url,resultUrl);assert.equal(o.maxRedirects,0);return{data:Readable.from([cfPng]),headers:{'content-type':'image/png'}};}});assert.equal(a.provider,'codeformer');assert.equal(observed[0].url,CODEFORMER_SPACE);assert.equal(observed[0].opts.token,undefined);assert.equal(observed[1].name,'/inference');assert.deepEqual(observed[1].data.slice(1),[true,true,true,2,0.7]);assert.equal(JSON.parse(await fs.readFile(env.REMINI_BUDGET_FILE)).codeformer,1);assert.equal((await sharp(a.file).metadata()).width,64);}));
test('CodeFormer token mode uses owner-supplied token, no duplicate or paid fallback',()=>fixture(async({dir,input,cfPng,env})=>{env.HF_TOKEN='hf_mock';let connectOpts;await freeEnhance(input,dir,{provider:'codeformer',allowDisclosure:true,env,connect:mockClient([{type:'data',data:[{url:resultUrl}]}],o=>{if(o.opts)connectOpts=o.opts;}),request:async()=>({data:Readable.from([cfPng]),headers:{'content-type':'image/png'}})});assert.equal(connectOpts.token,'hf_mock');}));
test('CodeFormer quota error consumed one attempt and never calls output/provider fallback',()=>fixture(async({dir,input,env})=>{let calls=0;await assert.rejects(freeEnhance(input,dir,{provider:'codeformer',allowDisclosure:true,env,connect:mockClient([{type:'status',stage:'error',success:false}]),request:async()=>{calls++;}}),e=>e.code==='QUOTA');assert.equal(calls,0);assert.equal(JSON.parse(await fs.readFile(env.REMINI_BUDGET_FILE)).codeformer,1);}));
test('disabled provider and zero cap never submit',()=>fixture(async({dir,input,env})=>{env.REMINI_CODEFORMER_ENABLED='false';await assert.rejects(freeEnhance(input,dir,{provider:'codeformer',allowDisclosure:true,env}),e=>e.code==='CONFIG');env.REMINI_CODEFORMER_ENABLED='true';env.REMINI_CODEFORMER_BUDGET='0';let submits=0;const connect=async()=>({view_api:async()=>({named_endpoints:{'/inference':{parameters:['image','face_align','background_enhance','face_upsample','upscale','codeformer_fidelity'].map(parameter_name=>({parameter_name}))}}}),submit:()=>submits++,close:()=>{}});await assert.rejects(freeEnhance(input,dir,{provider:'codeformer',allowDisclosure:true,env,connect}),e=>e.code==='CREDITS');assert.equal(submits,0);}));
test('SnapEdit multipart and credit cost are correct, local balance prevents overspend',()=>fixture(async({dir,input,png,env})=>{env.REMINI_SNAPEDIT_BUDGET='4';let posts=0;const request=async o=>{if(o.method==='POST'){posts++;assert.equal(o.url,'https://api.snapedit.app/v1/images/enhance');assert.equal(o.headers['api-key'],'mock');assert.match(o.data.getBuffer().toString(),/name="zoom_factor"\r\n\r\n2/);assert.match(o.data.getBuffer().toString(),/name="enhance_faces"\r\n\r\ntrue/);return{data:{data:[{url:'https://outputs.snapedit.app/outputs/result.png'}]}};}return {data:Readable.from([png]),headers:{'content-type':'image/png'}};};const a=await freeEnhance(input,dir,{provider:'snapedit',allowDisclosure:true,env,request});assert.equal(a.provider,'snapedit');assert.equal(JSON.parse(await fs.readFile(env.REMINI_BUDGET_FILE)).snapedit,4);await assert.rejects(freeEnhance(input,dir,{provider:'snapedit',allowDisclosure:true,env,request}),e=>e.code==='CREDITS');assert.equal(posts,1);}));
test('SnapEdit4x reserves7credits, quota fails gracefully no retry',()=>fixture(async({dir,input,env})=>{let calls=0;await assert.rejects(freeEnhance(input,dir,{provider:'snapedit',scale:4,allowDisclosure:true,env,request:async()=>{calls++;throw{response:{status:429}};}}),e=>e.code==='QUOTA');assert.equal(calls,1);assert.equal(JSON.parse(await fs.readFile(env.REMINI_BUDGET_FILE)).snapedit,7);}));
test('Gradio queue timeout cancels without retry or late result download',()=>fixture(async({dir,input,env})=>{let cancel=0,close=0;const connect=async()=>({view_api:async()=>({named_endpoints:{'/inference':{parameters:['image','face_align','background_enhance','face_upsample','upscale','codeformer_fidelity'].map(parameter_name=>({parameter_name}))}}}),submit:()=>({cancel:async()=>cancel++,async *[Symbol.asyncIterator](){await new Promise(r=>setTimeout(r,80));yield{type:'data',data:[{url:resultUrl}]};}}),close:()=>close++});let requests=0;await assert.rejects(freeEnhance(input,dir,{provider:'codeformer',allowDisclosure:true,env,connect,timeoutMs:30,request:async()=>requests++}),e=>e.code==='TIMEOUT');await new Promise(r=>setTimeout(r,100));assert.equal(cancel,1);assert.ok(close>=1);assert.equal(requests,0);}));
test('provider status separates SnapEdit credits and anonymous CodeFormer configuration',()=>fixture(async({env})=>{const status=await providerStatus(env);assert.equal(status.find(x=>x.name==='snapedit').remainingLocalBudget,10);assert.equal(status.find(x=>x.name==='codeformer').keyConfigured,true);}));

test('SnapEdit late POST completion cannot download or write after timeout',()=>fixture(async({dir,input,env})=>{let gets=0;await assert.rejects(freeEnhance(input,dir,{provider:'snapedit',allowDisclosure:true,env,timeoutMs:30,request:async o=>{if(o.method==='POST'){await new Promise(r=>setTimeout(r,80));return{data:{data:[{url:'https://outputs.snapedit.app/outputs/late.png'}]}};}gets++;throw new Error('late GET');}}),e=>e.code==='TIMEOUT');await new Promise(r=>setTimeout(r,100));assert.equal(gets,0);await assert.rejects(fs.stat(path.join(dir,'result.jpg')),e=>e.code==='ENOENT');}));

test('CodeFormer source internal512short-side expansion is bounded, final size stays requested',()=>{assert.deepEqual(codeFormerSize({width:256,height:192},2),{width:1366,height:1024});assert.deepEqual(codeFormerSize({width:1024,height:512},2),{width:2048,height:1024});});

test('CodeFormer explicit free-only unlimited mode still counts attempts and does not alter SnapEdit cap',()=>fixture(async({env})=>{env.REMINI_CODEFORMER_BUDGET='0';env.REMINI_CODEFORMER_FREE_ONLY_UNLIMITED='true';const status=await providerStatus(env);assert.equal(status.find(p=>p.name==='codeformer').freeOnlyUnlimited,true);assert.equal(status.find(p=>p.name==='snapedit').freeOnlyUnlimited,false);assert.equal(status.find(p=>p.name==='snapedit').remainingLocalBudget,10);}));
