import test from 'node:test';import assert from 'node:assert/strict';import {code,translate,registry} from '../src/i18n/index.js';test('language registry aliases, fallback and interpolation',()=>{assert.ok(Object.keys(registry).length>7000);assert.equal(code('hi'),'hin');assert.equal(code('bn'),'ben');assert.equal(translate('aaa','balance',{balance:10}),'Virtual balance: 10 coins');assert.match(translate('hin','balance',{balance:10}),/10/);assert.throws(()=>code('../etc'));});
import fs from 'node:fs';import {available,locale,setLanguage,preference} from '../src/i18n/index.js';import {playerJid} from '../src/economy/identity.js';
test('locale values preserve English placeholders; no complete English clones',()=>{const english=locale('eng');for(const c of available()){const l=locale(c);assert.ok(Object.keys(l).length>=18,c);for(const [k,v]of Object.entries(l)){assert.equal(typeof v,'string',c+':'+k);assert.ok(k in english,c+':'+k);const placeholders=s=>[...new Set(s.match(/\{[A-Za-z_]+\}/g)||[])].sort();assert.deepEqual(placeholders(v),placeholders(english[k]),c+':'+k);}if(c!=='eng')assert.notEqual(l.balance,english.balance,c);}});
test('group preference overrides user preference, reset and identities stay scoped',async()=>{const user={senderJid:'14155550111:3@s.whatsapp.net',sender:'14155550111',jid:'unit@g.us',isGroup:true};await setLanguage(user,'hi');assert.equal(preference(user),'hin');await setLanguage(user,'bn',true);assert.equal(preference(user),'ben');assert.equal(preference({...user,isGroup:false}),'hin');await setLanguage(user,null,true);assert.equal(preference(user),'hin');await setLanguage(user,null);assert.equal(preference(user),'eng');assert.equal(playerJid(user),'14155550111@s.whatsapp.net');assert.throws(()=>playerJid({...user,senderJid:'14155550111@lid'}));});

test('camelCase placeholders such as maxBalance interpolate',()=>{assert.ok(!translate('hin','rules_summary',{daily:100,earn:10,seconds:60,maxBalance:1000000}).includes('{'));});

test('prototype names cannot pass language registry validation',()=>{for(const c of ['constructor','__proto__','toString'])assert.throws(()=>code(c));});

import {validateLocales} from '../src/i18n/validate.js';test('startup locale validator distinguishes complete and partial locales',()=>{const r=validateLocales();assert.equal(r.registered,7847);assert.equal(r.complete,77);assert.equal(r.partial,0);});
test('untranslated prototype-property keys are never interpreted as translated strings',()=>{assert.equal(translate('eng','constructor'),'constructor');assert.equal(translate('hin','__proto__'),'__proto__');});
