import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {Readable} from 'node:stream';import sharp from 'sharp';
import {imageMetadata,localEnhance,enhanceImage,saveImageStream,safeProviderUrl,pixelbinHeaders,EnhanceError}from '../src/services/imageEnhancer.js';
import{setApkChoices,takeApkChoice}from '../src/commands/apk/selection.js';import{limitEnhance,parseEnhance}from '../src/commands/_enhance.js';
async function fixture(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'enh-test-'));const input=path.join(dir,'in.png');await sharp({create:{width:32,height:24,channels:3,background:'#aabbcc'}}).png().toFile(input);try{await fn(dir,input);}finally{await fs.rm(dir,{recursive:true,force:true});}}
test('local image tools create validated output without network',()=>fixture(async(dir,input)=>{for(const mode of ['upscale','sharpen','denoise']){const out=path.join(dir,mode+'.jpg');const a=await localEnhance(input,out,mode);assert.equal(a.provider,'local');const m=await imageMetadata(out,{output:true});assert.equal(m.width,mode==='upscale'?64:32);}await assert.rejects(localEnhance(input,path.join(dir,'bad.jpg'),'restore'),EnhanceError);}));
test('stream input bounds remove partial output',()=>fixture(async(dir)=>{const dest=path.join(dir,'partial');await assert.rejects(saveImageStream(Readable.from([Buffer.alloc(10)]),dest,{maxBytes:5}),EnhanceError);await assert.rejects(fs.stat(dest));}));
test('invalid image and excessive pixel dimensions fail',()=>fixture(async(dir,input)=>{await fs.writeFile(path.join(dir,'bad'),'html');await assert.rejects(imageMetadata(path.join(dir,'bad')),EnhanceError);await assert.rejects(localEnhance(input,path.join(dir,'large'),'upscale',8),EnhanceError);}));
test('external providers need disclosure, configuration, budget and paid gate',()=>fixture(async(dir,input)=>{await assert.rejects(enhanceImage(input,dir,{provider:'clipdrop'}),e=>e.code==='CONSENT');await assert.rejects(enhanceImage(input,dir,{provider:'clipdrop',allowDisclosure:true,env:{REMINI_BUDGET_FILE:path.join(dir,'budget.json'),}}),e=>e.code==='CONFIG');await assert.rejects(enhanceImage(input,dir,{provider:'replicate',allowDisclosure:true,env:{REMINI_BUDGET_FILE:path.join(dir,'budget.json'),REPLICATE_API_TOKEN:'test',REMINI_REPLICATE_ENABLED:'true',REMINI_REPLICATE_BUDGET:'2'}}),e=>e.code==='PAID');}));
test('Clipdrop multipart adapter validates real pixels with mocked network',()=>fixture(async(dir,input)=>{let calls=0;const png=await fs.readFile(input);const a=await enhanceImage(input,dir,{provider:'clipdrop',allowDisclosure:true,env:{REMINI_BUDGET_FILE:path.join(dir,'budget.json'),CLIPDROP_API_KEY:'test',REMINI_CLIPDROP_ENABLED:'true',REMINI_CLIPDROP_BUDGET:'10'},request:async o=>{calls++;assert.equal(o.url,'https://clipdrop-api.co/image-upscaling/v1/upscale');assert.equal(o.maxRedirects,0);assert.equal(o.headers['x-api-key'],'test');assert.match(o.data.getBuffer().toString(),/target_width/);return{data:Readable.from([png]),headers:{'content-type':'image/webp','x-remaining-credits':'99'}};}});assert.equal(calls,1);assert.equal(a.creditsRemaining,'99');assert.equal((await imageMetadata(a.file,{output:true})).width,32);}));
test('provider returned hosts reject redirects/credentials/private targets',()=>{for(const u of ['http://delivery.pixelbin.io/a','https://evil.test/a','https://delivery.pixelbin.io.evil/a','https://u:p@delivery.pixelbin.io/a','https://127.0.0.1/a'])assert.throws(()=>safeProviderUrl(u,'pixelbin'),EnhanceError);assert.equal(safeProviderUrl('https://delivery.pixelbin.io/a','pixelbin'),'https://delivery.pixelbin.io/a');assert.match(pixelbinHeaders('test','https://api.pixelbin.io/x')['x-ebg-signature'],/^v1:[a-f0-9]{64}$/);});
test('image rate limiting and per-photo disclosure syntax',()=>{limitEnhance('rate-test',1);limitEnhance('rate-test',2);limitEnhance('rate-test',3);assert.throws(()=>limitEnhance('rate-test',4));assert.deepEqual(parseEnhance(['pixelbin','2','yes'],'upscale'),{provider:'pixelbin',scale:2,allowDisclosure:true});});
test('APK numeric selections expire and cannot cross chat or sender',()=>{setApkChoices('chat','sender',[{name:'a',packageName:'org.test.app'}],1000);assert.equal(takeApkChoice('chat','other','1',1001),null);assert.equal(takeApkChoice('other','sender','1',1001),null);assert.equal(takeApkChoice('chat','sender','hi',1001),null);assert.equal(takeApkChoice('chat','sender','1',1001).packageName,'org.test.app');assert.equal(takeApkChoice('chat','sender','1',1002),null);setApkChoices('chat','sender',[{packageName:'org.test.app'}],1000);assert.equal(takeApkChoice('chat','sender','1',122000),null);});
test('PixelBin multipart prediction and host-bound output are handled without public upload endpoint',()=>fixture(async(dir,input)=>{const png=await fs.readFile(input);let calls=[];const a=await enhanceImage(input,dir,{provider:'pixelbin',allowDisclosure:true,env:{REMINI_BUDGET_FILE:path.join(dir,'budget.json'),PIXELBIN_API_TOKEN:'test',REMINI_PIXELBIN_ENABLED:'true',REMINI_PIXELBIN_BUDGET:'10'},request:async o=>{calls.push(o.url);if(o.method==='POST'){assert.match(o.data.getBuffer().toString(),/input.enhance_face/);assert.match(o.headers['x-ebg-signature'],/^v1:/);return {data:{_id:'sr--upscale--test',status:'SUCCESS',output:['https://delivery.pixelbin.io/result.jpg']}};}return {data:Readable.from([png]),headers:{'content-type':'image/png'}};}});assert.equal(a.provider,'pixelbin');assert.equal(calls.length,2);assert.ok(!calls.some(x=>x.includes('upload')));}));
test('provider credits failure does not send photo to another provider',()=>fixture(async(dir,input)=>{let calls=0;await assert.rejects(enhanceImage(input,dir,{provider:'clipdrop',allowDisclosure:true,env:{REMINI_BUDGET_FILE:path.join(dir,'budget.json'),CLIPDROP_API_KEY:'test',REMINI_CLIPDROP_ENABLED:'true',REMINI_CLIPDROP_BUDGET:'10'},request:async()=>{calls++;throw{response:{status:402}};}}),e=>e.code==='CREDITS');assert.equal(calls,1);}));
test('paid Replicate mocked prediction keeps explicit gate and pinned schema',()=>fixture(async(dir,input)=>{const png=await fs.readFile(input);const a=await enhanceImage(input,dir,{provider:'replicate',allowDisclosure:true,env:{REMINI_BUDGET_FILE:path.join(dir,'budget.json'),REPLICATE_API_TOKEN:'test',REMINI_REPLICATE_ENABLED:'true',REMINI_REPLICATE_BUDGET:'10',REMINI_REPLICATE_PAID_APPROVED:'true',REPLICATE_ESRGAN_VERSION:'e1f4a2081605342caf55ba4294914cf266dcdf738397cf8826b48cdae516137c'},request:async o=>{if(o.method==='POST'){assert.ok(o.data.input.image.startsWith('data:image/jpeg;base64,'));return{data:{id:'test',status:'succeeded',output:'https://replicate.delivery/test.png'}};}return{data:Readable.from([png]),headers:{'content-type':'image/png'}};}});assert.equal(a.provider,'replicate');}));

test('credit attempt budget survives calls and blocks over-cap execution',()=>fixture(async(dir,input)=>{const env={REMINI_BUDGET_FILE:path.join(dir,'budget.json'),CLIPDROP_API_KEY:'test',REMINI_CLIPDROP_ENABLED:'true',REMINI_CLIPDROP_BUDGET:'1'};let calls=0;const request=async()=>{calls++;throw{response:{status:402}};};await assert.rejects(enhanceImage(input,dir,{provider:'clipdrop',allowDisclosure:true,env,request}));await assert.rejects(enhanceImage(input,dir,{provider:'clipdrop',allowDisclosure:true,env,request}),e=>e.code==='CREDITS');assert.equal(calls,1);assert.equal(JSON.parse(await fs.readFile(env.REMINI_BUDGET_FILE)).clipdrop,1);}));
