import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {normalizePhone,lookupPhone,phoneFields,formatPhoneInfo,phoneStatus} from '../src/services/phoneInfo.js';import command from '../src/commands/number.js';
async function fixture(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'phone-info-'));const env={PHONEINFO_BUDGET_FILE:path.join(dir,'quota.json'),VERIPHONE_API_KEY:'mock',IPQS_API_KEY:'mock',PHONEINFO_VERIPHONE_ENABLED:'true',PHONEINFO_VERIPHONE_BUDGET:'1',PHONEINFO_IPQS_ENABLED:'true',PHONEINFO_IPQS_BUDGET:'1'};try{await fn(env);}finally{await fs.rm(dir,{force:true,recursive:true});}}
test('phoneinfo requires one explicit international number',()=>{assert.equal(normalizePhone('+919876543210'),'+919876543210');for(const x of ['9876543210','+012345678','+919876543210,+919876543211','+919876543210 yes','+91 9876543210','http://evil.test'])assert.throws(()=>normalizePhone(x));});
test('phone lookup consent blocks all HTTP before reservation',()=>fixture(async env=>{let calls=0;await assert.rejects(lookupPhone('+919876543210',{env,request:async()=>calls++}),e=>e.code==='CONSENT');assert.equal(calls,0);await assert.rejects(fs.stat(env.PHONEINFO_BUDGET_FILE));}));
test('merged providers keep provenance, static one-credit Veriphone, no Truecaller request',()=>fixture(async env=>{let calls=0;const result=await lookupPhone('+919876543210',{env,allowDisclosure:true,request:async o=>{calls++;assert.equal(o.maxRedirects,0);assert.equal(o.timeout,15000);if(o.url.includes('veriphone')){assert.equal(o.url,'https://api.veriphone.io/v3/verify');assert.equal(o.headers.Authorization,'Bearer mock');assert.deepEqual(o.params,{phone:'+919876543210',mode:'static',record:false});return{data:{status:'success',phone_valid:true,carrier:'A',phone_type:'mobile',country:'India'}};}assert.match(o.url,/^https:\/\/www.ipqualityscore.com\/api\/json\/phone\/mock\//);return{data:{success:true,valid:true,carrier:'B',country:'IN',name:'N/A',fraud_score:25}};}});assert.equal(calls,2);const out=formatPhoneInfo(result);assert.match(out,/Assigned carrier: A/);assert.match(out,/Assigned carrier: B/);assert.match(out,/name: unavailable/);assert.match(out,/India are not guaranteed/);assert.equal(result.results[2].status,'disabled');const raw=await fs.readFile(env.PHONEINFO_BUDGET_FILE,'utf8');assert.ok(!raw.includes('9876543210'));assert.equal((await phoneStatus(env))[0].remaining,0);}));
test('caps reserve before API and prevent retries/automatic monthly refill',()=>fixture(async env=>{let calls=0;const args={env,allowDisclosure:true,request:async()=>{calls++;throw{response:{status:429}};}};const a=await lookupPhone('+919876543210',args);assert.equal(a.results[0].status,'quota');await lookupPhone('+919876543210',{...args,now:Date.now()+32*86400000});assert.equal(calls,2);}));
test('parallel requests cannot overspend lifetime cap',()=>fixture(async env=>{let calls=0;const o={env,allowDisclosure:true,request:async()=>{calls++;return{data:{status:'success',success:true}};}};await Promise.all([lookupPhone('+919876543210',o),lookupPhone('+919876543211',o)]);assert.equal(calls,2);}));
test('corrupt ledger blocks all external calls',()=>fixture(async env=>{await fs.writeFile(env.PHONEINFO_BUDGET_FILE,'{"ipqs":{"total":-1}}');let calls=0;await assert.rejects(lookupPhone('+919876543210',{env,allowDisclosure:true,request:async()=>calls++}),e=>e.code==='BUDGET');assert.equal(calls,0);}));
test('IPQS risky signal is not a certainty; invalid fields withheld, external prose stripped',()=>{const d=phoneFields('ipqs',{success:true,name:'A\n\u202eB',fraud_score:101,valid:'yes',identity_data:{emails:['private']}});assert.equal(d.name,'AB');assert.equal(d.fraudScore,null);assert.equal(d.valid,null);assert.equal(d.identity_data,undefined);assert.throws(()=>phoneFields('ipqs',{success:false}));});
test('group or sudo nonowner cannot invoke phoneinfo',async()=>{for(const ctx of [{isOwner:true,isGroup:true},{isOwner:false,isGroup:false}]){let reply;await command.run({...ctx,args:['+919876543210','yes'],reply:async x=>reply=x});assert.match(reply,/owner-only/);}});
test('zero/default budgets cannot call API',()=>fixture(async env=>{env.PHONEINFO_VERIPHONE_BUDGET='1001';env.PHONEINFO_IPQS_BUDGET='-1';let calls=0;await lookupPhone('+919876543210',{env,allowDisclosure:true,request:async()=>calls++});assert.equal(calls,0);}));

test('DataCrawler exact matching phone schema returns only basic reported name metadata',()=>{const d=phoneFields('rapidapi',{status:true,data:[{name:'Reported Name',birthday:'private',phones:[{e164Format:'+916290371061',countryCode:'IN',carrier:'Jio',numberType:'MOBILE'}],addresses:['private'],isFraud:false}]},'+916290371061');assert.deepEqual(d,{name:'Reported Name',countryCode:'IN',carrier:'Jio',lineType:'MOBILE',reportedRegion:null});assert.throws(()=>phoneFields('rapidapi',{status:true,data:[{name:'Other',phones:[{e164Format:'+919999999999'}]}]},'+916290371061'));});

test('region filter excludes street-style city values',()=>{const r=phoneFields('rapidapi',{status:true,data:[{phones:[{e164Format:'+916290371061'}],addresses:[{city:'Sarat Bose Road',address:'hidden'}]}]},'+916290371061');assert.equal(r.reportedRegion,null);const i=phoneFields('ipqs',{success:true,country:'IN',city:'N/A',region:'India'});assert.equal(i.reportedRegion,'India');});
