import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {prepareWhatsAppVideo,inspectMp4Atoms} from '../src/utils/whatsappVideo.js';import {sendMediaFile} from '../src/utils/sender.js';import config from '../src/config/config.js';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'wa-video-'));const old=config.tools.ffmpeg;const probe=spawnSync(old,['-version']);const ffmpeg=probe.status===0?old:'/usr/bin/ffmpeg';config.tools.ffmpeg=ffmpeg;
function make(file,args=[]){const p=spawnSync(ffmpeg,['-hide_banner','-loglevel','error','-y','-filter_threads','1','-filter_complex_threads','1','-f','lavfi','-i','color=c=blue:s=321x241:d=1','-f','lavfi','-i','sine=frequency=440:duration=1',...args,'-threads','1',file]);assert.equal(p.status,0,p.stderr?.toString());}
test('VP9+Opus WebM becomes H264 AAC yuv420p faststart MP4 with actual full decode',async()=>{const file=path.join(dir,'in.webm');make(file,['-c:v','libvpx-vp9','-c:a','libopus']);const out=await prepareWhatsAppVideo({path:file,type:'video',fileName:'in.webm'});assert.ok(out.size>1000);assert.equal(out.mimetype,'video/mp4');const atoms=await inspectMp4Atoms(out.path);assert.ok(atoms.moov<atoms.mdat);const decode=spawnSync(ffmpeg,['-hide_banner','-i',out.path,'-f','null','-']);assert.equal(decode.status,0);assert.match(decode.stderr.toString(),/Video: h264/);assert.match(decode.stderr.toString(),/Audio: aac/);assert.match(decode.stderr.toString(),/yuv420p/);await fs.rm(out.path);});
test('silent MP4 sender converts and streams checked video then removes only converted temp',async()=>{const file=path.join(dir,'silent.mp4');make(file,['-map','0:v','-c:v','libx264']);let payload,converted;await sendMediaFile({sendMessage:async(j,p)=>{payload=p;converted=p.video.url;assert.ok((await fs.stat(converted)).size>0);}},'c',{path:file,type:'video',size:0},{},'caption');assert.equal(payload.mimetype,'video/mp4');assert.equal(payload.caption,'caption');assert.ok(await fs.stat(file));await assert.rejects(fs.stat(converted));});
test('corrupt/truncated video is blocked and failed conversion leaves no output',async()=>{const file=path.join(dir,'bad.mp4');await fs.writeFile(file,'not a video');const before=await fs.readdir(dir);await assert.rejects(prepareWhatsAppVideo({path:file,type:'video'}));assert.deepEqual(await fs.readdir(dir),before);});
test('actual output size selects document rather than trusting stale download metadata',async()=>{const file=path.join(dir,'doc.mp4');make(file,['-map','0:v','-c:v','libx264']);const oldLimit=config.limits.maxInlineVideoBytes;config.limits.maxInlineVideoBytes=1;let p;try{await sendMediaFile({sendMessage:async(j,x)=>p=x},'c',{path:file,type:'video',size:0,fileName:'doc.mp4'},{});assert.ok(p.document);assert.equal(p.fileName,'doc.mp4');}finally{config.limits.maxInlineVideoBytes=oldLimit;}});
test.after(async()=>{config.tools.ffmpeg=old;await fs.rm(dir,{recursive:true,force:true});});
test('already safe H264 AAC video uses fast remux rather than video re-encoding',async()=>{const file=path.join(dir,'remux.mp4');make(file,['-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac']);const out=await prepareWhatsAppVideo({path:file,type:'video'});assert.equal(out.conversion,'remux');const atoms=await inspectMp4Atoms(out.path);assert.ok(atoms.moov<atoms.mdat);await fs.rm(out.path);});
test('safe H264 with incompatible audio copies video and converts only audio',async()=>{const file=path.join(dir,'audio.mkv');make(file,['-c:v','libx264','-pix_fmt','yuv420p','-c:a','libopus']);const out=await prepareWhatsAppVideo({path:file,type:'video'});assert.equal(out.conversion,'audio-transcode');await fs.rm(out.path);});
test('ETA uses measured stage speed, unknown before progress, bounded percent',async()=>{const {videoProgress,parseDuration}=await import('../src/utils/whatsappVideo.js');assert.equal(parseDuration('Duration: 00:04:00.00'),240);assert.equal(videoProgress('',240,'preparing').remainingSeconds,null);const p=videoProgress('time=00:01:00.00 speed=0.50x',240,'converting');assert.equal(p.remainingSeconds,360);assert.equal(p.percent,25);assert.equal(videoProgress('time=00:05:00.00 speed=2x',240,'checking').percent,100);});
