import {fileTypeFromFile} from 'file-type';
import fs from 'node:fs/promises';import crypto from 'node:crypto';import zlib from 'node:zlib';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const AdmZip=require('adm-zip');
export const PACKAGE_RE=/^[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)+$/;
export class ApkError extends Error{}
export function validateApkUrl(raw){let u;try{u=new URL(raw);}catch{throw new ApkError('Send a valid HTTPS APK link.');}if(u.protocol!=='https:'||u.hostname!=='f-droid.org'||u.port||u.username||u.password||u.search||u.hash)throw new ApkError('Only official f-droid.org APK links are accepted.');const m=u.pathname.match(/^\/repo\/([A-Za-z][A-Za-z0-9_.]*?)_(\d+)\.apk$/);if(!m||!PACKAGE_RE.test(m[1]))throw new ApkError('Send a direct official F-Droid .apk link.');const versionCode=Number(m[2]);if(!Number.isSafeInteger(versionCode)||versionCode<=0)throw new ApkError('Invalid APK version code.');return {url:u.href,packageName:m[1],versionCode};}
function stringPool(b,offset,size){if(size<28)throw new ApkError('Invalid Android string table.');const count=b.readUInt32LE(offset+8),flags=b.readUInt32LE(offset+16),start=b.readUInt32LE(offset+20),header=b.readUInt16LE(offset+2);if(count>50000||header<28||offset+header+count*4>offset+size)throw new ApkError('Invalid Android string table.');const strings=[];
 const bound=(p,n)=>{if(p<offset||p+n>offset+size)throw new ApkError('Invalid Android string table.');};
 for(let i=0;i<count;i++){let p=offset+start+b.readUInt32LE(offset+header+i*4);bound(p,2);if(flags&0x100){function len(){bound(p,1);let v=b[p++];if(v&0x80){bound(p,1);v=((v&0x7f)<<8)|b[p++];}return v;}len();const n=len();bound(p,n+1);if(b[p+n]!==0)throw new ApkError('Invalid Android string terminator.');strings.push(b.subarray(p,p+n).toString('utf8'));}else{let n=b.readUInt16LE(p);p+=2;if(n&0x8000){bound(p,2);n=((n&0x7fff)<<16)|b.readUInt16LE(p);p+=2;}bound(p,n*2+2);if(b.readUInt16LE(p+n*2)!==0)throw new ApkError('Invalid Android string terminator.');strings.push(b.subarray(p,p+n*2).toString('utf16le'));}}return strings;}
export function manifestPackage(b){if(b.length<8||b.readUInt16LE(0)!==3||b.readUInt32LE(4)!==b.length)throw new ApkError('The file has no valid binary Android manifest.');let strings=[];for(let o=b.readUInt16LE(2);o+8<=b.length;){const type=b.readUInt16LE(o),header=b.readUInt16LE(o+2),size=b.readUInt32LE(o+4);if(size<header||header<8||o+size>b.length)throw new ApkError('Invalid Android manifest chunk.');if(type===1)strings=stringPool(b,o,size);if(type===0x102){if(header<16||size<36)throw new ApkError('Invalid Android manifest element.');const e=o+16,name=b.readUInt32LE(e+4),attrStart=b.readUInt16LE(e+8),attrSize=b.readUInt16LE(e+10),count=b.readUInt16LE(e+12);if(strings[name]==='manifest'){if(attrSize<20||count>1000||e+attrStart+attrSize*count>o+size)throw new ApkError('Invalid Android manifest attributes.');for(let i=0;i<count;i++){const a=e+attrStart+i*attrSize;if(strings[b.readUInt32LE(a+4)]==='package'){const raw=b.readUInt32LE(a+8),typed=b[a+15]===3?b.readUInt32LE(a+16):null;const v=strings[raw===0xffffffff?typed:raw];if(PACKAGE_RE.test(v||''))return v;}}}}o+=size;}throw new ApkError('Android package identity is missing.');}
export async function inspectApk(file,{expectedPackage,maxBytes=50*1048576}={}){const st=await fs.stat(file);if(!st.isFile()||st.size<100||st.size>maxBytes)throw new ApkError('APK size is empty or exceeds the limit.');const detected=await fileTypeFromFile(file);if(!detected||!['application/zip','application/vnd.android.package-archive'].includes(detected.mime))throw new ApkError('Downloaded file type is not APK/ZIP.');const b=await fs.readFile(file);if(b.readUInt32LE(0)!==0x04034b50)throw new ApkError('The downloaded file is not an APK ZIP.');let zip;try{zip=new AdmZip(b);}catch{throw new ApkError('APK ZIP structure is invalid.');}const entries=zip.getEntries();if(!entries.length||entries.length>20000)throw new ApkError('APK archive has too many entries.');const names=new Set();for(const e of entries){if(names.has(e.entryName)||e.entryName.startsWith('/')||e.entryName.split('/').includes('..')||e.entryName.includes('\\'))throw new ApkError('APK archive paths are invalid.');names.add(e.entryName);}const m=zip.getEntry('AndroidManifest.xml');if(!m||m.header.size>2*1048576||m.header.compressedSize>2*1048576||m.header.flags&1)throw new ApkError('APK manifest is missing or invalid.');let manifest;try{const packed=m.getCompressedData();manifest=m.header.method===0?packed:m.header.method===8?zlib.inflateRawSync(packed,{maxOutputLength:2*1048576}):null;}catch{throw new ApkError('APK manifest decompression failed.');}if(!manifest||manifest.length!==m.header.size)throw new ApkError('APK manifest size mismatch.');const packageName=manifestPackage(manifest);if(expectedPackage&&packageName!==expectedPackage)throw new ApkError('APK package does not match the requested app.');return {packageName,size:st.size,sha256:crypto.createHash('sha256').update(b).digest('hex')};}
