// Light, clean roasts. Aimed only at the sender, never at appearance, family, religion or anything sensitive.
export const ROASTS = [
 'You say "5 minutes" and somehow it turns into 45. Time itself is confused by you.',
 'Your phone battery is at 3% and you still open one more app. Brave, but not smart.',
 'You have 47 unread chats and 1 reply you have been "thinking about" since last week.',
 'Your "I will start tomorrow" has been running longer than most TV serials.',
 'You open the fridge, see nothing new, close it, and open it again hoping for a miracle. Same energy as your career plan.',
 'You are the person who says "just one episode" at 11 PM and sees the sunrise.',
 'You have 300 photos of food and still say "I never take photos".',
 'Your alarm gets more snooze than a bedtime story.',
 'You study the menu for 10 minutes and order the same thing as always.',
 'You are proof that "I will reply later" is a lifestyle.',
 'You said "I am on my way" while still looking for your socks.',
 'Your phone gallery: 2% memories, 98% screenshots you will never open again.',
 'You walk into a room and forget why, then walk out and remember. A true professional.',
 'You have more browser tabs open than friends who reply on time.',
 'You tell everyone you are a morning person. The sun has never seen you.',
 'You charge your phone for 5 minutes and expect a full day. Optimism level: legendary.',
 'You called it "light work" and then asked for help three times.',
 'You are the reason the group chat has a mute button.',
 'You cook once a month and talk about it like a TV chef for the next week.',
 'You bought a gym membership to feel fit. Mission accomplished, you feel fit just owning it.',
 'You still say "I will remember it" and then forget it before the sentence ends.',
 'Your WiFi signal and your motivation have one thing in common: both drop at the worst time.',
 'You do not procrastinate. You just give the deadline a lot of time to grow up.',
 'You have a "plan B" for everything except the plan A you never started.',
 'You are so lazy that even your shadow follows you slowly.',
];
export function pickRoast(seed = Math.random()) { return ROASTS[Math.floor(seed * ROASTS.length) % ROASTS.length]; }
