import fs from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import path from 'node:path';
import {pipeline} from 'node:stream/promises';
import sharp from 'sharp';
import axios from 'axios';
import FormData from 'form-data';
import {Client,handle_file} from '@gradio/client';
import {EnhanceError,IMAGE_LIMITS,imageMetadata,prepareImage,targetSize,byteLimiter,reserveProvider} from './imageEnhancer.js';
export const CODEFORMER_SPACE='https://sczhou-codeformer.hf.space';
export function freeProviderUrl(raw,provider){let u;try{u=new URL(raw);}catch{throw new EnhanceError('Invalid provider output URL.','URL');}const hosts=provider==='codeformer'?['sczhou-codeformer.hf.space']:['outputs.snapedit.app','api-outputs.snapedit.app'];if(u.protocol!=='https:'||!hosts.includes(u.hostname)||u.username||u.password||u.port)throw new EnhanceError('Unapproved provider output host.','URL');if(provider==='codeformer'&&!/^\/gradio_api\/file=/.test(u.pathname))throw new EnhanceError('Unapproved CodeFormer output path.','URL');return u.href;}
export function codeFormerSize(meta,scale){const f=Math.max(1,512/Math.min(meta.width,meta.height));const round=v=>Math.abs(v%1-0.5)<1e-9?2*Math.round(v/2):Math.round(v);return{width:round(meta.width*f)*scale,height:round(meta.height*f)*scale};}
export function validateFreeInput(meta,provider,scale){const size=targetSize(meta,scale);if(![2,4].includes(scale))throw new EnhanceError('Use scale 2 or 4 for this provider.','SIZE');if(provider==='snapedit'&&(meta.width>1500||meta.height>1500))throw new EnhanceError('SnapEdit input must be 1500 pixels or less per side.','SIZE');if(provider==='codeformer'&&(meta.width*meta.height>4e6||Math.min(meta.width,meta.height)>1100||Math.max(meta.width,meta.height)>1500||(scale===4&&Math.max(meta.width,meta.height)>1000)))throw new EnhanceError('CodeFormer limits: 4x input <=1000px; 2x long side <=1500px, short side <=1100px. Resize first.','SIZE');return size;}
async function getResult(raw,provider,dest,request,signal){const url=freeProviderUrl(raw,provider);const r=await request({url,method:'GET',signal,timeout:15000,responseType:'stream',maxRedirects:0,proxy:false,maxContentLength:IMAGE_LIMITS.outputBytes});if(!['image/png','image/jpeg','image/webp'].includes(String(r.headers?.['content-type']||'').split(';')[0]))throw new EnhanceError('Provider output is not an image.','IMAGE');await pipeline(r.data,byteLimiter(IMAGE_LIMITS.outputBytes),createWriteStream(dest,{flags:'wx',mode:0o600}),{signal});}
export async function freeEnhance(input,dir,{provider,mode='upscale',scale=2,allowDisclosure=false,env=process.env,request=axios.request,connect=(...args)=>Client.connect(...args),timeoutMs=IMAGE_LIMITS.timeoutMs}={}){if(!allowDisclosure)throw new EnhanceError('Confirm sending this photo to the selected provider with yes.','CONSENT');if(!['upscale','restore'].includes(mode))throw new EnhanceError('Use local for sharpen/denoise.','MODE');const prepared=await prepareImage(input,dir);const meta=await imageMetadata(prepared);const target=validateFreeInput(meta,provider,scale);const expected=provider==='codeformer'?codeFormerSize(meta,scale):target;if(expected.width>4096||expected.height>4096||expected.width*expected.height>IMAGE_LIMITS.outputPixels)throw new EnhanceError('CodeFormer internal upscale exceeds safe output bounds. Use a less narrow image.','SIZE');const cost=provider==='snapedit'?(scale===2?4:7):1;const raw=path.join(dir,'provider-output'),final=path.join(dir,'result.jpg');let client,job,timer;const ctrl=new AbortController();let expired=false;
const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{expired=true;ctrl.abort();try{job?.cancel()?.catch(()=>{});}catch{}try{client?.close();}catch{}reject(new EnhanceError('Provider queue or processing timed out. No automatic retry; quota may have been used.','TIMEOUT'));},timeoutMs);});
try{const work=(async()=>{if(provider==='snapedit'){await reserveProvider(provider,env,cost);if(expired)return;const form=new FormData();form.append('input_image',await fs.readFile(prepared),{filename:'photo.png',contentType:'image/png'});form.append('zoom_factor',String(scale));form.append('enhance_faces','true');const r=await request({url:'https://api.snapedit.app/v1/images/enhance',method:'POST',data:form,headers:{...form.getHeaders(),'api-key':env.SNAPEDIT_API_KEY},signal:ctrl.signal,timeout:90000,maxBodyLength:25*1048576,maxContentLength:1048576,maxRedirects:0,proxy:false});if(expired)return;await getResult(r.data?.data?.[0]?.url,provider,raw,request,ctrl.signal);
}else{if(env.REMINI_CODEFORMER_ENABLED!=='true')throw new EnhanceError('CodeFormer is not enabled yet.','CONFIG');const opts={events:['status','data']};if(env.HF_TOKEN)opts.token=env.HF_TOKEN;client=await connect(CODEFORMER_SPACE,opts);if(expired){client.close();return;}const api=await client.view_api();const endpoint=api.named_endpoints?.['/inference']||api.named_endpoints?.inference;const names=endpoint?.parameters?.map(p=>p.parameter_name);if(!names||names.join(',')!=='image,face_align,background_enhance,face_upsample,upscale,codeformer_fidelity')throw new EnhanceError('CodeFormer API changed. No photo sent.','SCHEMA');if(expired)return;await reserveProvider(provider,env,1);if(expired)return;const blob=new Blob([await fs.readFile(prepared)],{type:'image/png'});if(expired)return;job=client.submit('/inference',[handle_file(blob),true,true,true,scale,0.7]);let received=false;for await(const event of job){if(expired)return;if(event.type==='status'&&(event.stage==='error'||event.status==='error'||event.success===false))throw new EnhanceError('CodeFormer queue, quota or model error. Wait before retrying; no quota workaround or fallback.','QUOTA');if(event.type==='data'){const file=event.data?.[0];const url=typeof file==='string'?file:file?.url;await getResult(url,provider,raw,request,ctrl.signal);received=true;break;}}if(!received&&!expired)throw new EnhanceError('CodeFormer returned no image.','PROVIDER');}
if(expired)return;const out=await imageMetadata(raw,{output:true});if(out.width!==expected.width||out.height!==expected.height)throw new EnhanceError('Provider returned '+out.width+'x'+out.height+' instead of '+expected.width+'x'+expected.height+'. Result rejected.','SIZE');const bytes=await sharp(raw,{limitInputPixels:IMAGE_LIMITS.outputPixels}).rotate().resize(target.width,target.height,{fit:'fill',withoutEnlargement:true}).jpeg({quality:92}).toBuffer();if(expired)return;await fs.writeFile(final,bytes,{flag:'wx',mode:0o600,signal:ctrl.signal});await imageMetadata(final,{output:true});if(expired){await fs.rm(final,{force:true});return;}return {provider,file:final,mime:'image/jpeg',creditsRemaining:null,note:provider==='snapedit'?'SnapEdit AI enhancement; '+cost+' trial credits reserved. Provider claims transient images/no training; metadata 90 days.':'CodeFormer face restoration on public HF Space. Small-input internal enlargement normalized to requested size. Output downloaded immediately; source schedules deletion after 30s. Upload/cache retention unverified. ZeroGPU quota enforced by HF, no paid fallback.'};})();return await Promise.race([work,timeout]);
}catch(e){await fs.rm(final,{force:true});if(e instanceof EnhanceError)throw e;if(e.response?.status===429||/quota|rate.limit|GPU.*duration/i.test(e.message||''))throw new EnhanceError('Provider free quota or rate limit reached. Wait for reset; no automatic retry or paid fallback.','QUOTA');if(e.response?.status===402)throw new EnhanceError('Provider credits exhausted. No paid fallback.','CREDITS');throw new EnhanceError('Free image provider failed or is unavailable. No automatic retry or other provider received the photo.','PROVIDER');}finally{clearTimeout(timer);ctrl.abort();try{client?.close();}catch{}await fs.rm(raw,{force:true});}}
