import {freeEnhance} from './freeImageProviders.js';
import fs from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {Transform} from 'node:stream';
import {pipeline} from 'node:stream/promises';
import sharp from 'sharp';
import axios from 'axios';
import FormData from 'form-data';
import config from '../config/config.js';
export const IMAGE_LIMITS={inputBytes:10*1048576,outputBytes:20*1048576,inputPixels:16e6,outputPixels:4096*4096,maxSide:4096,timeoutMs:120000};
export class EnhanceError extends Error{constructor(message,code='INVALID'){super(message);this.code=code;}}
export function byteLimiter(max){let n=0;return new Transform({transform(c,e,cb){n+=c.length;cb(n>max?new EnhanceError('Image exceeds the file-size limit.','SIZE'):null,c);}});}
export async function saveImageStream(stream,dest,{maxBytes=IMAGE_LIMITS.inputBytes,timeoutMs=30000}={}){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),timeoutMs);try{await pipeline(stream,byteLimiter(maxBytes),createWriteStream(dest,{flags:'wx',mode:0o600}),{signal:ctrl.signal});}catch(e){await fs.rm(dest,{force:true});throw e instanceof EnhanceError?e:new EnhanceError('Image download failed or timed out.','DOWNLOAD');}finally{clearTimeout(timer);}}
export async function imageMetadata(file,{output=false}={}){const st=await fs.stat(file);if(!st.size||st.size>(output?IMAGE_LIMITS.outputBytes:IMAGE_LIMITS.inputBytes))throw new EnhanceError('Image file is empty or too large.','SIZE');let meta;try{meta=await sharp(file,{limitInputPixels:output?IMAGE_LIMITS.outputPixels:IMAGE_LIMITS.inputPixels,failOn:'error'}).metadata();}catch{throw new EnhanceError('Image is invalid or exceeds the resolution limit.','IMAGE');}if(!['jpeg','png','webp'].includes(meta.format)||!meta.width||!meta.height||(meta.pages||1)>1)throw new EnhanceError('Use a static JPEG, PNG or WebP image.','IMAGE');if(output&&(meta.width>4096||meta.height>4096))throw new EnhanceError('Provider output exceeds the resolution limit.','SIZE');return meta;}
export function targetSize(meta,scale=2){if(![1,2,4].includes(scale))throw new EnhanceError('Use scale 1,2 or4.');if(meta.width*scale>4096||meta.height*scale>4096)throw new EnhanceError('Result would exceed4096pixels per side. Use a smaller scale.','SIZE');return {width:meta.width*scale,height:meta.height*scale};}
export async function prepareImage(input,dir){await imageMetadata(input);const file=path.join(dir,'prepared.png');await sharp(input,{limitInputPixels:IMAGE_LIMITS.inputPixels,failOn:'error'}).rotate().png().toFile(file);await imageMetadata(file);return file;}
export async function localEnhance(input,output,mode='upscale',scale=2){const meta=await imageMetadata(input);let img=sharp(input,{limitInputPixels:IMAGE_LIMITS.inputPixels,failOn:'error'}).rotate();if(mode==='upscale')img=img.resize(targetSize(meta,scale));else if(mode==='sharpen')img=img.sharpen({sigma:1});else if(mode==='denoise')img=img.median(3);else throw new EnhanceError('Local processing supports upscale,sharpen or denoise, not AI restoration.','MODE');await img.jpeg({quality:92}).toFile(output);await imageMetadata(output,{output:true});return {provider:'local',file:output,note:'Local Sharp processing, not AI face restoration.',mime:'image/jpeg'};}
let budgetWrite=Promise.resolve();
const budgetFile=env=>env.REMINI_BUDGET_FILE||path.join(config.paths.data,'image-credit-budget.json');
async function readBudget(env){try{const j=JSON.parse(await fs.readFile(budgetFile(env),'utf8'));if(!j||typeof j!=='object'||Array.isArray(j)||Object.values(j).some(x=>!Number.isSafeInteger(x)||x<0))throw new Error();return j;}catch(e){if(e.code==='ENOENT')return {};throw new EnhanceError('Credit budget file is unreadable. External requests disabled.','BUDGET');}}
export async function providerStatus(env=process.env){const used=await readBudget(env);return ['clipdrop','pixelbin','replicate','snapedit','codeformer'].map(name=>({name,keyConfigured:name==='codeformer'||!!env[{clipdrop:'CLIPDROP_API_KEY',pixelbin:'PIXELBIN_API_TOKEN',replicate:'REPLICATE_API_TOKEN',snapedit:'SNAPEDIT_API_KEY'}[name]],enabled:env['REMINI_'+name.toUpperCase()+'_ENABLED']==='true',freeOnlyUnlimited:name==='codeformer'&&env.REMINI_CODEFORMER_FREE_ONLY_UNLIMITED==='true',remainingLocalBudget:name==='codeformer'&&env.REMINI_CODEFORMER_FREE_ONLY_UNLIMITED==='true'?null:Math.max(0,Number(env['REMINI_'+name.toUpperCase()+'_BUDGET']||0)-(used[name]||0))}));}
export async function reserveProvider(name,env,cost=1){const run=budgetWrite.catch(()=>{}).then(async()=>{const p=(await providerStatus(env)).find(p=>p.name===name);if(!p?.keyConfigured||!p.enabled)throw new EnhanceError('This provider is not configured/enabled yet.','CONFIG');if(!p.freeOnlyUnlimited&&(!Number.isSafeInteger(p.remainingLocalBudget)||p.remainingLocalBudget<cost))throw new EnhanceError('Provider test budget exhausted. Ask the owner before adding credits.','CREDITS');if(name==='replicate'&&env.REMINI_REPLICATE_PAID_APPROVED!=='true')throw new EnhanceError('Replicate is paid and needs owner approval before use.','PAID');const used=await readBudget(env);used[name]=(used[name]||0)+cost;const file=budgetFile(env),tmp=file+'.tmp';try{await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(tmp,JSON.stringify(used),{mode:0o600});await fs.rename(tmp,file);}catch{throw new EnhanceError('Could not save credit budget. No provider request was sent.','BUDGET');}});budgetWrite=run;return run;}
export function safeProviderUrl(raw,provider){let u;try{u=new URL(raw);}catch{throw new EnhanceError('Provider returned an invalid download URL.','URL');}const allowed=provider==='pixelbin'?['delivery.pixelbin.io','cdn.pixelbin.io']:['replicate.delivery'];if(u.protocol!=='https:'||u.username||u.password||u.port||!allowed.some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))throw new EnhanceError('Provider returned an unapproved download host.','URL');return u.href;}
export function pixelbinHeaders(token,url,method='GET',date=new Date()){const stamp=date.toISOString().replace(/[:\-]|\.\d{3}/g,'');const u=new URL(url);const canonical=[method,u.pathname,'',`host:${u.host}\nx-ebg-param:${stamp}\n`,'host;x-ebg-param',crypto.createHash('sha256').update('').digest('hex')].join('\n');const str=stamp+'\n'+crypto.createHash('sha256').update(canonical).digest('hex');return {Authorization:'Bearer '+Buffer.from(token).toString('base64'),'x-ebg-param':Buffer.from(stamp).toString('base64'),'x-ebg-signature':'v1:'+crypto.createHmac('sha256','1234567').update(str).digest('hex')};}
function clientOptions(signal){return {signal,timeout:30000,maxBodyLength:25*1048576,maxContentLength:IMAGE_LIMITS.outputBytes,maxRedirects:0,proxy:false};}
async function downloadOutput(url,provider,dest,request,signal,headers={}){const safe=safeProviderUrl(url,provider);const r=await request({url:safe,method:'GET',responseType:'stream',headers,...clientOptions(signal)});const mime=String(r.headers?.['content-type']||'').split(';')[0];if(!['image/jpeg','image/png','image/webp'].includes(mime))throw new EnhanceError('Provider output is not a supported image.','IMAGE');await pipeline(r.data,byteLimiter(IMAGE_LIMITS.outputBytes),createWriteStream(dest,{flags:'wx',mode:0o600}),{signal});return r;}
async function waitJob(job,provider,request,signal,env,sleep){const done=provider==='pixelbin'?'SUCCESS':'succeeded',bad=provider==='pixelbin'?['FAILURE']:['failed','canceled'];for(let i=0;i<24&&job.status!==done;i++){if(bad.includes(job.status))throw new EnhanceError('Image provider could not finish this request.','PROVIDER');await sleep(4000,signal);const id=provider==='pixelbin'?job._id:job.id;if(!/^[a-zA-Z0-9_-]{1,160}$/.test(id||''))throw new EnhanceError('Provider returned an invalid job ID.','PROVIDER');const url=provider==='pixelbin'?'https://api.pixelbin.io/service/platform/transformation/v1.0/predictions/'+id:'https://api.replicate.com/v1/predictions/'+id;const headers=provider==='pixelbin'?pixelbinHeaders(env.PIXELBIN_API_TOKEN,url):{Authorization:'Bearer '+env.REPLICATE_API_TOKEN};job=(await request({url,method:'GET',headers,...clientOptions(signal),maxContentLength:1048576})).data;}if(job.status!==done)throw new EnhanceError('Provider processing timed out. Check credit usage before retrying.','TIMEOUT');return job;}
const defaultSleep=(ms,signal)=>new Promise((resolve,reject)=>{if(signal.aborted)return reject(new EnhanceError('Request timed out.','TIMEOUT'));const t=setTimeout(done,ms);function done(){signal.removeEventListener('abort',abort);resolve();}function abort(){clearTimeout(t);reject(new EnhanceError('Request timed out.','TIMEOUT'));}signal.addEventListener('abort',abort,{once:true});});
export async function enhanceImage(input,dir,{provider='local',mode='upscale',scale=2,allowDisclosure=false,env=process.env,request=axios.request,sleep=defaultSleep,connect,timeoutMs}={}){if(['codeformer','snapedit'].includes(provider))return freeEnhance(input,dir,{provider,mode,scale,allowDisclosure,env,request,connect,timeoutMs});const output=path.join(dir,'enhanced.jpg');if(provider==='local')return localEnhance(input,output,mode,scale);if(!['clipdrop','pixelbin','replicate'].includes(provider))throw new EnhanceError('Choose local,clipdrop,pixelbin or replicate.');if(!allowDisclosure)throw new EnhanceError('External enhancement sends your photo to the selected provider. Confirm disclosure first.','CONSENT');if(provider!=='local'&&!['upscale','restore'].includes(mode))throw new EnhanceError('Use local mode for sharpen/denoise.','MODE');if(provider==='clipdrop'&&mode==='restore')throw new EnhanceError('Clipdrop adapter supports upscaling,not AI face restoration.','MODE');const prepared=await prepareImage(input,dir);const meta=await imageMetadata(prepared);const target=targetSize(meta,scale);await reserveProvider(provider,env);const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),IMAGE_LIMITS.timeoutMs);try{let creditsRemaining=null;
 if(provider==='clipdrop'){const form=new FormData();form.append('image_file',await fs.readFile(prepared),{filename:'photo.png',contentType:'image/png'});form.append('target_width',String(target.width));form.append('target_height',String(target.height));const r=await request({url:'https://clipdrop-api.co/image-upscaling/v1/upscale',method:'POST',data:form,headers:{...form.getHeaders(),'x-api-key':env.CLIPDROP_API_KEY},responseType:'stream',...clientOptions(ctrl.signal)});if(!['image/jpeg','image/webp'].includes(String(r.headers?.['content-type']||'').split(';')[0]))throw new EnhanceError('Clipdrop did not return an image.','IMAGE');await pipeline(r.data,byteLimiter(IMAGE_LIMITS.outputBytes),createWriteStream(output,{flags:'wx',mode:0o600}),{signal:ctrl.signal});creditsRemaining=r.headers?.['x-remaining-credits']??null;
 }else if(provider==='pixelbin'){const url='https://api.pixelbin.io/service/platform/transformation/v1.0/predictions/sr/upscale';const form=new FormData();form.append('input.image',await fs.readFile(prepared),{filename:'photo.png',contentType:'image/png'});form.append('input.type',scale+'X');form.append('input.enhance_face',String(mode==='restore'));form.append('input.enhance_quality','true');form.append('input.model','picasso');const r=await request({url,method:'POST',data:form,headers:{...form.getHeaders(),...pixelbinHeaders(env.PIXELBIN_API_TOKEN,url,'POST')},...clientOptions(ctrl.signal),maxContentLength:1048576});const job=await waitJob(r.data,provider,request,ctrl.signal,env,sleep);await downloadOutput(Array.isArray(job.output)?job.output[0]:job.output,provider,output,request,ctrl.signal);
 }else{const jpg=await sharp(prepared).jpeg({quality:90}).toBuffer();if(jpg.length>256*1024)throw new EnhanceError('Replicate data-URL trial is limited to256KiB. Resize the input first.','SIZE');const version=env.REPLICATE_ESRGAN_VERSION;if(!/^[a-f0-9]{64}$/.test(version||''))throw new EnhanceError('Replicate model version must be pinned by the owner.','CONFIG');const r=await request({url:'https://api.replicate.com/v1/predictions',method:'POST',data:{version,input:{image:'data:image/jpeg;base64,'+jpg.toString('base64'),scale,face_enhance:mode==='restore'}},headers:{Authorization:'Bearer '+env.REPLICATE_API_TOKEN,'Content-Type':'application/json',Prefer:'wait=30','Cancel-After':'90s'},...clientOptions(ctrl.signal),maxContentLength:1048576});const job=await waitJob(r.data,provider,request,ctrl.signal,env,sleep);await downloadOutput(Array.isArray(job.output)?job.output[0]:job.output,provider,output,request,ctrl.signal,{Authorization:'Bearer '+env.REPLICATE_API_TOKEN});}
 await imageMetadata(output,{output:true});const final=path.join(dir,'result.jpg');await sharp(output,{limitInputPixels:IMAGE_LIMITS.outputPixels}).rotate().jpeg({quality:92}).toFile(final);await imageMetadata(final,{output:true});return {provider,file:final,mime:'image/jpeg',creditsRemaining,note:provider==='pixelbin'?'Provider-hosted input/output; outputs retained about30days. Local files are removed after sending.':provider==='replicate'?'Paid model; API input/output normally removed after1hour.':'Clipdrop upscaling; provider retention unverified.'};
 }catch(e){await fs.rm(output,{force:true});if(e instanceof EnhanceError)throw e;if(e.response?.status===402)throw new EnhanceError('Provider credits exhausted. No paid fallback was attempted.','CREDITS');if(e.response?.status===429)throw new EnhanceError('Provider rate limit reached. Wait before retrying.','RATE');throw new EnhanceError(ctrl.signal.aborted?'Enhancement timed out. Credits may have been used.':'Enhancement provider failed. No other provider received the photo.','PROVIDER');}finally{clearTimeout(timer);}}
