import fs from 'node:fs/promises';
import path from 'node:path';
import axios from 'axios';
import config from '../config/config.js';

export class PhoneInfoError extends Error {constructor(message,code='INVALID'){super(message);this.code=code;}}
const providers=['veriphone','ipqs','rapidapi'];
const keys={veriphone:'VERIPHONE_API_KEY',ipqs:'IPQS_API_KEY',rapidapi:'RAPIDAPI_API_KEY'};
const maxima={veriphone:1000,ipqs:1000,rapidapi:7};
let writes=Promise.resolve();
const ledgerPath=env=>env.PHONEINFO_BUDGET_FILE||path.join(config.paths.data,'phone-info-budget.json');
export function normalizePhone(value){const v=String(value??'').trim();if(!/^\+[1-9]\d{7,14}$/.test(v))throw new PhoneInfoError('Use one number in international format, for example +919876543210. No spaces or lists.');return v;}
function cap(env,p){const x=Number(env['PHONEINFO_'+p.toUpperCase()+'_BUDGET']||0);return Number.isSafeInteger(x)&&x>=0&&x<=maxima[p]?x:0;}
async function ledger(env){try{const j=JSON.parse(await fs.readFile(ledgerPath(env),'utf8'));if(!j||typeof j!=='object'||Array.isArray(j)||Object.entries(j).some(([k,v])=>!providers.includes(k)||!v||!Number.isSafeInteger(v.total)||v.total<0||!Array.isArray(v.times)||v.times.some(x=>!Number.isSafeInteger(x)||x<0)))throw new Error();return j;}catch(e){if(e.code==='ENOENT')return {};throw new PhoneInfoError('Phone quota file is unreadable. No external lookup sent.','BUDGET');}}
export async function phoneStatus(env=process.env){const used=await ledger(env);return providers.map(p=>({provider:p,enabled:env['PHONEINFO_'+p.toUpperCase()+'_ENABLED']==='true'&&!!env[keys[p]],remaining:Math.max(0,cap(env,p)-(used[p]?.total||0))}));}
async function reserve(p,env,now){const work=writes.catch(()=>{}).then(async()=>{const j=await ledger(env),v=j[p]||{total:0,times:[]};if(v.total>=cap(env,p))throw new PhoneInfoError('Local free lookup cap reached. No paid fallback.','QUOTA');v.times=v.times.filter(t=>t>now-86400000);if(p==='ipqs'&&v.times.length>=35)throw new PhoneInfoError('IPQS rolling 24-hour cap reached. No retry.','QUOTA');v.total++;v.times.push(now);j[p]=v;const f=ledgerPath(env);try{await fs.mkdir(path.dirname(f),{recursive:true});await fs.writeFile(f+'.tmp',JSON.stringify(j),{mode:0o600});await fs.rename(f+'.tmp',f);}catch{throw new PhoneInfoError('Could not save lookup cap. No external request sent.','BUDGET');}});writes=work;return work;}
const text=v=>typeof v==='string'&&!['','N/A','null','unknown'].includes(v.trim())?v.replace(/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/g,'').replace(/\s+/g,' ').trim().slice(0,100):null;
const coarse=v=>{const x=text(v);return x&&!/\b(road|street|lane|avenue|drive|flat|house|apartment|floor|rd|st|ln|ave|dr)\b|\d/i.test(x)?x:null;};
const bool=v=>typeof v==='boolean'?v:null;
export function phoneFields(p,d,phone){if(!d||typeof d!=='object')throw new PhoneInfoError('Provider response changed.','SCHEMA');if(p==='veriphone'){if(d.status!=='success')throw new PhoneInfoError('Veriphone did not return a successful result.','PROVIDER');return{valid:bool(d.phone_valid),country:text(d.country),countryCode:text(d.country_code),carrier:text(d.carrier),lineType:text(d.phone_type),region:text(d.phone_region)};}
if(p==='rapidapi'){if(d.status!==true||!Array.isArray(d.data))throw new PhoneInfoError('Caller-name response changed.','SCHEMA');const row=d.data.find(x=>Array.isArray(x.phones)&&x.phones.some(n=>n.e164Format===phone));if(!row)throw new PhoneInfoError('Caller-name result did not match requested number.','SCHEMA');const n=row.phones.find(x=>x.e164Format===phone);return{name:text(row.name),countryCode:text(n.countryCode),carrier:text(n.carrier),lineType:text(n.numberType),reportedRegion:(row.addresses||[]).map(a=>coarse(a.city)).filter(Boolean).join(', ')||null};}
if(d.success!==true)throw new PhoneInfoError('IPQS did not return a successful result.','PROVIDER');return{valid:bool(d.valid),countryCode:text(d.country),carrier:text(d.carrier),lineType:text(d.line_type),name:text(d.name),reportedRegion:[coarse(d.city),coarse(d.region)].filter(Boolean).join(', ')||null,fraudScore:Number.isInteger(d.fraud_score)&&d.fraud_score>=0&&d.fraud_score<=100?d.fraud_score:null,recentAbuse:bool(d.recent_abuse),voip:bool(d.VOIP),risky:bool(d.risky)};}
export async function lookupPhone(value,{allowDisclosure=false,env=process.env,request=axios.request,now=Date.now()}={}){const phone=normalizePhone(value);if(!allowDisclosure)throw new PhoneInfoError('Confirm sending this number to the enabled phone-info providers with yes.','CONSENT');const status=await phoneStatus(env),results=[];for(const p of providers){const s=status.find(x=>x.provider===p);if(!s.enabled){results.push({provider:p,status:'disabled'});continue;}if(s.remaining===0){results.push({provider:p,status:'quota'});continue;}if(p==='rapidapi'&&!/^\+91[6-9]\d{9}$/.test(phone)){results.push({provider:p,status:'unsupported'});continue;}try{await reserve(p,env,now);const options=p==='veriphone'?{url:'https://api.veriphone.io/v3/verify',method:'GET',headers:{Authorization:'Bearer '+env.VERIPHONE_API_KEY},params:{phone,mode:'static',record:false}}:p==='rapidapi'?{url:'https://truecaller4.p.rapidapi.com/api/v1/getDetails',method:'GET',params:{countryCode:'IN',phone:phone.slice(3)},headers:{'x-rapidapi-key':env.RAPIDAPI_API_KEY,'x-rapidapi-host':'truecaller4.p.rapidapi.com'}}:{url:'https://www.ipqualityscore.com/api/json/phone/'+encodeURIComponent(env.IPQS_API_KEY)+'/'+encodeURIComponent(phone),method:'GET'};const r=await request({...options,timeout:15000,maxRedirects:0,proxy:false,maxContentLength:65536,maxBodyLength:1024,responseType:'json'});results.push({provider:p,status:'ok',fields:phoneFields(p,r.data,phone)});}catch(e){results.push({provider:p,status:e instanceof PhoneInfoError?e.code==='QUOTA'?'quota':e.code==='BUDGET'?'budget':'failed':e.response?.status===429?'quota':'failed'});}}
return{phone,results};}
export function formatPhoneInfo({phone,results}){const lines=['Phone info: '+phone];for(const r of results){lines.push('\n'+r.provider+':');if(r.status!=='ok'){lines.push({disabled:'Not configured.',quota:'Free/local cap reached. No paid fallback.',budget:'Quota storage failed. No lookup sent.',failed:'Unavailable or response invalid. No retry.',unsupported:'Number country not supported by this adapter yet.', 'unverified-license':'Not configured. Caller-name source is still awaiting verified API schema.'}[r.status]||'Unavailable.');continue;}const labels={valid:'Numbering-plan valid',country:'Country',countryCode:'Country code',carrier:'Assigned carrier',lineType:'Line type',region:'Reported numbering region (not live location)',reportedRegion:'Reported region (not live location)',name:'Associated name (unverified)',fraudScore:'IPQS fraud score (0-100, not proof of wrongdoing)',recentAbuse:'Recent abuse signal',voip:'VoIP',risky:'Risk signal'};for(const [k,v]of Object.entries(r.fields))if(v!==null)lines.push(labels[k]+': '+String(v));if(r.provider==='ipqs'&&!r.fields.name)lines.push('Associated name: unavailable.');}lines.push('\nNames for India are not guaranteed. Metadata is not identity verification or live location. Sources can disagree; results kept separate. No bulk search, retries, paid fallback or automatic quota reset.');return lines.join('\n');}
