import {downloadMediaMessage} from '@whiskeysockets/baileys';
import path from 'node:path';
import config from '../config/config.js';
import logger from '../utils/logger.js';
import {findMedia} from '../utils/imageTools.js';
import {createJobDir,removeJobDir,freeDiskBytes} from '../utils/fileManager.js';
import {downloadQueue} from '../utils/downloader.js';
import {saveImageStream,enhanceImage,EnhanceError,providerStatus,IMAGE_LIMITS} from '../services/imageEnhancer.js';
const rates=new Map();
export function limitEnhance(user,now=Date.now()){const a=(rates.get(user)||[]).filter(t=>now-t<60000);if(a.length>=3)throw new EnhanceError('Image limit:3 requests per minute.','RATE');rates.set(user,[...a,now]);if(rates.size>5000)rates.clear();}
export function parseEnhance(args,mode){const p=args.find(x=>['local','clipdrop','pixelbin','replicate','snapedit','codeformer'].includes(x.toLowerCase()))?.toLowerCase()||'local';const scale=Number(args.find(x=>/^[124]x?$/i.test(x))?.replace(/x/i,'')||(mode==='sharpen'||mode==='denoise'?1:2));return {provider:p,scale,allowDisclosure:args.some(x=>x.toLowerCase()==='yes')};}
export async function runEnhance(ctx,mode='upscale'){let dir;try{if(ctx.args[0]==='status')return ctx.reply((await providerStatus()).map(p=>p.name+': '+(p.enabled&&p.keyConfigured?'configured':'disabled')+(p.freeOnlyUnlimited?', provider free quota only (no local attempt cap)':', remaining local budget '+p.remainingLocalBudget)+(p.name==='codeformer'?' attempts (not GPU minutes)':p.name==='snapedit'?' credits':' attempts')).join('\n')+'\nNo automatic fallback or paid auto-topup.');limitEnhance(ctx.sender);const opts=parseEnhance(ctx.args,mode);if(opts.provider!=='local'&&!ctx.isOwner)throw new EnhanceError('External provider trials are owner-only. Local /sharpen and /denoise work without keys.','PERMISSION');if(opts.provider!=='local'&&!opts.allowDisclosure)return ctx.reply('This sends the photo to '+opts.provider+'. '+(opts.provider==='pixelbin'?'Provider URLs may be accessible to anyone with the link and outputs stay about30days.':opts.provider==='clipdrop'?'Provider retention is not verified.':opts.provider==='codeformer'?'Public Hugging Face Space. Output deletion scheduled after30s; upload/cache retention unverified. Free GPU quota, may queue or reject.':opts.provider==='snapedit'?'Provider claims images processed transiently, no model training; request metadata90days. Costs4credits at2x or7at4x.':'Paid model; API data normally removed after1hour.')+' To confirm this photo, use '+config.prefix+(mode==='upscale'?'remini':mode)+' '+opts.provider+' '+opts.scale+' yes.');const media=findMedia(ctx.msg);if(!media||media.type!=='image'||media.animated)throw new EnhanceError('Send or reply to a static JPEG,PNG or WebP photo.');if(Number(media.node.fileLength)>IMAGE_LIMITS.inputBytes)throw new EnhanceError('Photo exceeds10MiB.','SIZE');if(await freeDiskBytes()<config.limits.minFreeDiskBytes)throw new EnhanceError('Not enough free disk space.','DISK');await downloadQueue.add(ctx.sender,async()=>{dir=await createJobDir();const input=path.join(dir,'input');const stream=await downloadMediaMessage(media.message,'stream',{}, {logger,reuploadRequest:ctx.sock.updateMediaMessage});await saveImageStream(stream,input);const a=await enhanceImage(input,dir,{...opts,mode});await ctx.sock.sendMessage(ctx.jid,{document:{url:a.file},mimetype:a.mime,fileName:'remini.jpg',caption:'Provider: '+a.provider+'\n'+a.note+(a.creditsRemaining!==null&&a.creditsRemaining!==undefined?'\nCredits left: '+a.creditsRemaining:'')},{quoted:ctx.msg});});}catch(e){await ctx.reply(e instanceof EnhanceError?e.message:'Image processing failed. No automatic provider fallback.');}finally{await removeJobDir(dir);}}
