import sharp from 'sharp';
import config from '../config/config.js';
import logger from '../utils/logger.js';
import {makeLimiter,pollinationsImage,fluxImage} from '../services/publicAi.js';
const limiter=makeLimiter('IMAGINE','IMAGINE_PER_HOUR',60,1);
const users=new Map();
function userLimit(u,now=Date.now()){const a=(users.get(u)||[]).filter(t=>now-t<300000);if(a.length>=3)return false;users.set(u,[...a,now]);if(users.size>5000)users.clear();return true;}
export function cleanPrompt(args){return args.join(' ').replace(/\s+/g,' ').trim().slice(0,300);}
export default {name:'imagine',aliases:['img','aiimage'],category:'Image',description:'Generate an image from text (free public AI)',usage:'imagine <description>',
async run(ctx){
  const prompt=cleanPrompt(ctx.args||[]);
  if(!prompt)return ctx.reply('Usage: '+config.prefix+'imagine a red car on a rainy neon street');
  if(!userLimit(ctx.sender))return ctx.reply('Limit: 3 images per 5 minutes. Try again shortly.');
  if(!limiter.ok())return ctx.reply('Image generation is busy or turned off right now. Try again in a minute.');
  await limiter.run(async()=>{
    let buf,src;
    try{buf=await pollinationsImage(prompt,{timeoutMs:45000});src='Pollinations';}
    catch(e){logger.warn('imagine pollinations failed: '+(e?.message||'error'));
      try{buf=await fluxImage(prompt,{timeoutMs:40000});src='FLUX.1-schnell (Hugging Face)';}
      catch(e2){logger.warn('imagine flux failed: '+(e2?.message||'error'));return ctx.reply('Image generation failed (free AI services are busy). Try again in a minute.');}}
    let out;try{out=await sharp(buf,{limitInputPixels:4096*4096}).jpeg({quality:90}).toBuffer();}catch{return ctx.reply('Image generation failed. Try again.');}
    await ctx.sock.sendMessage(ctx.jid,{image:out,caption:'Prompt: '+prompt+'\nGenerated by free public AI ('+src+'). Your text was sent to that third-party service.'},{quoted:ctx.msg});
  });
}};
