import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const defaults=()=>({version:1,users:{},history:[],processed:[],rules:{daily:100,earn:10,earnCooldown:60000,maxBalance:1000000}});
const fresh=()=>({balance:0,dailyAt:0,earnAt:0,earned:0,transfers:0,payAt:0,payDay:0,payCount:0,achievements:[]});
const integer=(n,min=0,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
function validate(s){if(!s||s.version!==1||!s.users||Array.isArray(s.users)||typeof s.users!=='object'||!Array.isArray(s.history)||!Array.isArray(s.processed)||!s.rules)throw new Error('Invalid economy schema');const r=s.rules;if(!integer(r.daily,1,10000)||!integer(r.earn,1,1000)||!integer(r.earnCooldown,10000,86400000)||!integer(r.maxBalance,100,100000000))throw new Error('Invalid economy rules');if(s.history.length>1000||s.history.some(x=>!x||!integer(x.at)||!['daily','earn','pay'].includes(x.kind)||!integer(x.amount,1,10000)||Object.keys(x).some(k=>!['at','kind','user','from','to','amount'].includes(k))||[x.user,x.from,x.to].filter(v=>v!==undefined).some(v=>typeof v!=='string'||!(/^[a-f0-9]{64}$/.test(v))))||s.processed.length>5000||s.processed.some(x=>typeof x!=='string'||x.length>150)||new Set(s.processed).size!==s.processed.length)throw new Error('Invalid economy history');for(const [id,u]of Object.entries(s.users)){if(!/^[a-f0-9]{64}$/.test(id)||!u||!integer(u.balance,0,r.maxBalance)||!integer(u.dailyAt)||!integer(u.earnAt)||!integer(u.earned)||!integer(u.transfers)||!integer(u.payAt)||!integer(u.payDay)||!integer(u.payCount,0,100)||!Array.isArray(u.achievements)||u.achievements.some(x=>!['first_reward','earned_1000'].includes(x)))throw new Error('Invalid economy user');}}
export class Economy {
 constructor(file,now=()=>Date.now()){this.file=file;this.now=now;this.state=defaults();this.available=true;try{this.state=JSON.parse(fs.readFileSync(file,'utf8'));validate(this.state);}catch(e){if(e.code!=='ENOENT'){this.available=false;this.state=defaults();}}}
 id(jid){if(!/^\d{7,15}@s\.whatsapp\.net$/.test(jid))throw new Error('Use a valid phone-number user');return crypto.createHash('sha256').update(jid).digest('hex');}
 check(){if(!this.available)throw new Error('Economy store unavailable; no balances reset or changed');}
 user(jid){this.check();const id=this.id(jid);return {id,...structuredClone(this.state.users[id]||fresh())};}
 transaction(fn,operationId){this.check();const next=structuredClone(this.state);if(operationId){if(typeof operationId!=='string'||operationId.length>150)throw new Error('Invalid transaction ID');if(next.processed.includes(operationId))throw new Error('Transaction already processed');next.processed.push(operationId);next.processed=next.processed.slice(-5000);}const result=fn(next);validate(next);fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';const fd=fs.openSync(tmp,'w',0o600);try{fs.writeFileSync(fd,JSON.stringify(next));fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(tmp,this.file);this.state=next;try{const parent=fs.openSync(path.dirname(this.file),'r');try{fs.fsyncSync(parent);}finally{fs.closeSync(parent);}}catch{this.available=false;throw new Error('Economy store unavailable; do not retry transaction');}return result;}
 award(jid,kind,operationId){if(!['daily','earn'].includes(kind))throw new Error('Invalid reward');return this.transaction(s=>{const id=this.id(jid);const u=s.users[id]||=fresh();const t=this.now(),key=kind+'At',wait=kind==='daily'?86400000:s.rules.earnCooldown;if(u[key]&&t-u[key]<wait)throw new Error('Reward cooldown: wait '+Math.ceil((wait-(t-u[key]))/1000)+' seconds');const amount=s.rules[kind];if(u.balance+amount>s.rules.maxBalance)throw new Error('Reward limit reached');u.balance+=amount;u.earned+=amount;u[key]=t;if(!u.achievements.includes('first_reward'))u.achievements.push('first_reward');if(u.earned>=1000&&!u.achievements.includes('earned_1000'))u.achievements.push('earned_1000');s.history=[{at:t,kind,user:id,amount},...s.history].slice(0,1000);return {amount,balance:u.balance};},operationId);}
 pay(from,to,amount,operationId){const a=this.id(from),b=this.id(to);if(a===b)throw new Error('Cannot pay yourself');if(!integer(amount,1,10000))throw new Error('Use a whole amount 1-10000');return this.transaction(s=>{const sender=s.users[a],target=s.users[b]||=fresh();if(!sender||sender.balance<amount)throw new Error('Insufficient virtual balance');const now=this.now(),day=Math.floor(now/86400000);if(sender.payAt&&now-sender.payAt<2000)throw new Error('Transfer cooldown: wait 2 seconds');if(sender.payDay!==day){sender.payDay=day;sender.payCount=0;}if(sender.payCount>=100)throw new Error('Daily transfer limit reached');if(target.balance+amount>s.rules.maxBalance)throw new Error('Recipient balance limit');sender.balance-=amount;target.balance+=amount;sender.transfers++;sender.payAt=now;sender.payDay=day;sender.payCount++;s.history=[{at:this.now(),kind:'pay',from:a,to:b,amount},...s.history].slice(0,1000);return sender.balance;},operationId);}
 configure(rule,value){if(!Object.hasOwn(this.state.rules,rule))throw new Error('Unknown reward rule');return this.transaction(s=>{s.rules[rule]=value;return structuredClone(s.rules);});}
 rules(){this.check();return structuredClone(this.state.rules);}
 leaders(){this.check();return Object.entries(this.state.users).sort((a,b)=>b[1].balance-a[1].balance).slice(0,10).map(([id,u],i)=>({rank:i+1,player:id.slice(0,6),balance:u.balance}));}
 leaderboard(){return this.leaders().map(x=>`${x.rank}. Player ${x.player}: ${x.balance}`);}
}
