import {gameConfig,difficulty} from './settings.js';
export class GameEngine{
 constructor({sessions,progression,brain,now=()=>Date.now()}){this.sessions=sessions;this.progression=progression;this.brain=brain;this.now=now;this.notifications=new Map();}
 async start(ctx,name,level='easy',opts={}){if(this.progression.available===false)throw new Error('Game profiles unavailable. Existing file preserved.');const game=this.brain.get(name);if(!game)throw new Error('Unknown game.');difficulty(level);this.sessions.limit(ctx.jid,ctx.senderJid||ctx.sender);if(opts.daily){if(this.progression.dailyPlayed(ctx.senderJid||ctx.sender,opts.day))throw new Error('Daily challenge already played today.');}const s=this.sessions.create({chat:ctx.jid,players:[ctx.senderJid||ctx.sender],game:name,difficulty:level,state:game.create(level,opts),ttl:game.timeMs||gameConfig.questionMs});s.daily=opts.daily?opts.day:null;this.notifications.set(s.id,ctx.reply);try{if(s.daily)this.progression.markDaily(s.players[0],s.daily);await ctx.reply(this.render(s));if(game.memoryDelayMs){const timer=setTimeout(async()=>{if(!this.sessions.sessions.has(s.id))return;s.state.hidden=true;s.expires=this.now()+gameConfig.questionMs;try{await ctx.reply(this.render(s));}catch{}},game.memoryDelayMs);timer.unref();s.timer=timer;}return s;}catch(e){this.end(s);throw e;}}
 render(s){const game=this.brain.get(s.game);return `Game ${s.id} | ${s.game} | ${s.difficulty}\n${game.render(s.state)}\nAnswer: /${s.game} answer TEXT\nCancel: /${s.game} cancel`;}
 async answer(ctx,name,input){const player=ctx.senderJid||ctx.sender,s=this.sessions.current(ctx.jid,player);if(!s||s.kind!=='brain'||s.game!==name)throw new Error('Start this game first.');this.sessions.limit(ctx.jid,player);const result=this.brain.get(name).move(s.state,input);if(result.done){const xp=this.progression.finish({id:s.id,chat:s.chat,players:s.players,winners:result.won?s.players:[],draw:false,game:s.game,difficulty:s.difficulty});this.end(s);return ctx.reply(`${result.won?'Correct!':'Game over.'} Answer: ${result.answer}\nXP: ${xp[0]}`);}return ctx.reply(this.render(s));}
 end(s){clearTimeout(s.timer);this.notifications.delete(s.id);this.sessions.end(s.id);}
 async expire(s){clearTimeout(s.timer);const reply=this.notifications.get(s.id);this.notifications.delete(s.id);if(reply)try{await reply(`Game ${s.id} expired. No XP awarded.`);}catch{}}
 cancel(ctx){const s=this.sessions.current(ctx.jid,ctx.senderJid||ctx.sender);if(!s)throw new Error('No active game.');if(s.kind!=='brain')throw new Error('Use /leavegame for multiplayer.');this.end(s);return ctx.reply('Game canceled. No XP awarded.');}
}
