import crypto from 'node:crypto';import {difficulty} from './settings.js';
export class MultiplayerGameManager{
 constructor({sessions,progression,modules}){this.sessions=sessions;this.progression=progression;this.modules=modules;this.replies=new Map();this.timers=new Map();}
 async invite(ctx,name,players,level='easy'){if(this.progression.available===false)throw new Error('Game profiles unavailable. Existing file preserved.');const g=this.modules.get(name);if(!g)throw new Error('Unknown multiplayer game.');difficulty(level);const player=ctx.senderJid||ctx.sender;if(!players.includes(player)||players.length<(g.minPlayers||g.players)||players.length>g.players)throw new Error(`This game needs ${g.minPlayers||g.players}-${g.players} players.`);if(g.teams&&players.length%2)throw new Error('Team quiz needs an even player count.');this.sessions.limit(ctx.jid,player,true);const s=this.sessions.create({chat:ctx.jid,players,game:name,kind:'multi',invited:players.filter(p=>p!==player),difficulty:level,ttl:this.sessions.config.inviteMs});this.replies.set(s.id,ctx.reply);s.isGroup=ctx.isGroup;s.sock=ctx.sock;s.privateChats=[...players];if(!ctx.isGroup){for(const p of s.invited){try{await ctx.sock.sendMessage(p,{text:`${player.split('@')[0]} challenges you to ${name}. /accept ${s.id} or /decline ${s.id}. Expires in${this.sessions.config.inviteMs/1000}s.`});}catch(e){this.end(s);throw new Error('Could not deliver invitation. Nothing started.');}}}return ctx.reply(`Invite ${s.id}: ${name}. Players${players.map(p=>p.split('@')[0]).join(', ')}. /accept ${s.id} or /decline ${s.id}.`);}
 locate(ctx,id){const player=ctx.senderJid||ctx.sender;let s=id?this.sessions.sessions.get(id):this.sessions.current(ctx.jid,player);if(!s||s.kind!=='multi'||!s.players.includes(player))throw new Error('Game not found or you are not a player.');this.sessions.prune();if(!this.sessions.sessions.has(s.id))throw new Error('Game expired.');if(ctx.jid!==s.chat&&!(!ctx.isGroup&&s.privateChats.includes(ctx.jid)))throw new Error('Use this game in its original chat or your own private chat.');return s;}
 async send(s,text){let error;const reply=this.replies.get(s.id);if(reply)try{await reply(text);}catch(e){error=e;}if(!s.isGroup&&s.sock)for(const p of s.players)if(p!==s.chat)try{await s.sock.sendMessage(p,{text});}catch(e){error=e;}if(error)throw error;}
 async accept(ctx,id){const s=this.locate(ctx,id),p=ctx.senderJid||ctx.sender;this.sessions.accept(s.id,s.chat,p);if(s.status==='active'){s.state=this.modules.get(s.game).create(s.difficulty);s.state.playerCount=s.players.length;this.armReaction(s);return this.send(s,this.render(s));}return ctx.reply('Accepted. Waiting for other players.');}
 async decline(ctx,id){const s=this.locate(ctx,id);this.sessions.decline(s.id,s.chat,ctx.senderJid||ctx.sender);try{return await this.send(s,`Invite ${s.id} declined.`);}finally{this.end(s);}}
 render(s){return `Game ${s.id}: ${s.game}\n${s.status==='invited'?'Waiting for acceptance.':this.modules.get(s.game).render(s.state)}\n/move ${s.id} YOUR_MOVE | /leavegame ${s.id}`;}
 armReaction(s){if(!this.modules.get(s.game).reaction)return;clearTimeout(this.timers.get(s.id));const timer=setTimeout(async()=>{if(!this.sessions.sessions.has(s.id)||s.status!=='active')return;s.state.ready=true;this.sessions.touch(s);try{await this.send(s,`Game ${s.id}: GO! /move ${s.id} go`);}catch{}},crypto.randomInt(2000,5001));timer.unref();this.timers.set(s.id,timer);}
 async move(ctx,id,input){const s=this.locate(ctx,id),p=ctx.senderJid||ctx.sender,g=this.modules.get(s.game);if(s.status!=='active')throw new Error('Wait for all players to accept.');if(g.privateMoves&&ctx.isGroup)throw new Error('Send your choice in a private chat with Jarvis.');this.sessions.limit(s.chat,p);const r=g.move(s.state,String(input).trim().toLowerCase(),s.players.indexOf(p),s.difficulty);if(r.done){const xp=this.progression.finish({id:s.id,chat:s.chat,players:s.players,winners:r.winners.map(i=>s.players[i]),draw:r.draw,game:s.game,difficulty:s.difficulty});try{await this.send(s,`Game ${s.id} finished. ${r.draw?'Draw.':'Winner(s): '+r.winners.map(i=>'player'+(i+1)).join(', ')}\n${r.detail||''}\nXP: ${xp.join(', ')}`);}finally{this.end(s);}return;}if(r.newRound){this.sessions.touch(s);this.armReaction(s);}else if(!g.reaction&&(g.name==='ttt'||g.name==='connect4'))this.sessions.touch(s);if(r.secret)return ctx.reply('Choice locked. Waiting for opponent.');return this.send(s,(r.detail?r.detail+'\n':'')+this.render(s));}
 async leave(ctx,id){const s=this.locate(ctx,id);if(s.status==='invited'){try{await this.send(s,`Invite ${s.id} canceled.`);}finally{this.end(s);}return;}const loser=ctx.senderJid||ctx.sender;this.progression.finish({id:s.id,chat:s.chat,players:s.players,winners:s.players.filter(p=>p!==loser),draw:false,game:s.game,difficulty:s.difficulty,forfeit:true});try{await this.send(s,`Game ${s.id}: player left, game forfeited.`);}finally{this.end(s);}}
 end(s){clearTimeout(this.timers.get(s.id));this.timers.delete(s.id);this.replies.delete(s.id);this.sessions.end(s.id);}
 async expire(s){try{await this.send(s,`Game ${s.id} expired. No XP awarded.`);}finally{this.end(s);}}
}
