import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export class GameProgression{
 constructor(file,{now=()=>Date.now()}={}){this.file=file;this.now=now;this.data={version:1,players:{},completed:{},chats:{}};this.available=true;try{const d=JSON.parse(fs.readFileSync(file,'utf8'));if(typeof d!=='object'||d===null||d.version!==1||!d.players||typeof d.players!=='object'||Array.isArray(d.players)||!d.completed||typeof d.completed!=='object'||Array.isArray(d.completed)||!d.chats||typeof d.chats!=='object'||Array.isArray(d.chats)||Object.values(d.players).some(p=>['xp','wins','losses','draws','played','streak','bestStreak'].some(k=>!Number.isSafeInteger(p[k])||p[k]<0)||!p.stats||typeof p.stats!=='object'||Array.isArray(p.stats)||Object.values(p.stats).some(x=>!x||['played','wins','losses','draws','lastReward'].some(k=>!Number.isSafeInteger(x[k])||x[k]<0))||!Array.isArray(p.achievements)))throw Error('Invalid game profiles');this.data=d;}catch(e){if(e.code!=='ENOENT')this.available=false;}}
 id(player){return crypto.createHash('sha256').update('jarvis-game-player:'+player).digest('hex').slice(0,24);}
 day(){return new Date(this.now()).toISOString().slice(0,10);}
 profile(player){return this.data.players[this.id(player)]||{xp:0,wins:0,losses:0,draws:0,played:0,streak:0,bestStreak:0,lastDay:null,daily:null,achievements:[],stats:{},updated:0};}
 mutate(fn){if(!this.available)throw Error('Game profiles unavailable. Existing file preserved; no scores changed.');const before=structuredClone(this.data);try{const result=fn();fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.'+crypto.randomBytes(5).toString('hex')+'.tmp';try{const fd=fs.openSync(tmp,'wx',0o600);try{fs.writeFileSync(fd,JSON.stringify(this.data));fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(tmp,this.file);}finally{fs.rmSync(tmp,{force:true});}return result;}catch(e){this.data=before;throw e;}}
 dailyPlayed(player,day){return this.profile(player).daily===day;}
 markDaily(player,day){return this.mutate(()=>{const id=this.id(player),p=this.data.players[id]??=structuredClone(this.profile(player));if(p.daily===day)throw Error('Daily challenge already played.');p.daily=day;});}
 finish({id,chat,players,winners,draw,game,difficulty='easy',forfeit=false}){return this.mutate(()=>{if(this.data.completed[id])throw Error('Game result already saved.');const now=this.now(),day=this.day(),xp=[];for(const player of players){const key=this.id(player),p=this.data.players[key]??=structuredClone(this.profile(player));const win=winners.includes(player),result=draw?'draws':win?'wins':'losses',base=forfeit?0:win?{easy:10,medium:15,hard:20}[difficulty]||10:draw?3:2;const prior=p.stats[game]?.lastReward||0;const hour=Math.floor(now/3600000);if(p.rewardHour!==hour){p.rewardHour=hour;p.hourXp=0;}const amount=now-prior<10000&&prior?0:Math.min(base,Math.max(0,200-(p.hourXp||0)));p.hourXp=(p.hourXp||0)+amount;xp.push(amount);p.xp+=amount;p[result]++;p.played++;p.updated=now;const stat=p.stats[game]??={played:0,wins:0,losses:0,draws:0,lastReward:0};stat.played++;stat[result]++;if(amount)stat.lastReward=now;if(amount&&p.lastDay!==day){const yesterday=new Date(now-86400000).toISOString().slice(0,10);p.streak=p.lastDay===yesterday?p.streak+1:1;p.lastDay=day;p.bestStreak=Math.max(p.bestStreak,p.streak);}for(const [name,ok]of[['first-game',p.played>=1],['ten-wins',p.wins>=10],['century-xp',p.xp>=100],['three-day-streak',p.bestStreak>=3],['five-games',Object.keys(p.stats).length>=5]])if(ok&&!p.achievements.includes(name))p.achievements.push(name);const c=crypto.createHash('sha256').update(chat).digest('hex').slice(0,20);const board=this.data.chats[c]??={};board[key]=(board[key]||0)+amount;}this.data.completed[id]=now;for(const [k,t]of Object.entries(this.data.completed))if(now-t>86400000)delete this.data.completed[k];if(Object.keys(this.data.completed).length>5000)delete this.data.completed[Object.keys(this.data.completed)[0]];if(Object.keys(this.data.players).length>10000)throw Error('Game profile limit reached.');const chats=Object.keys(this.data.chats);if(chats.length>1000)delete this.data.chats[chats[0]];return xp;});}
 leaderboard(chat){const c=crypto.createHash('sha256').update(chat).digest('hex').slice(0,20);return Object.entries(this.data.chats[c]||{}).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,xp],i)=>`${i+1}. Player ${id.slice(0,6)}: ${xp}XP`).join('\n')||'No game scores in this chat yet.';}
}
