// Reviewed offline questions. Categories are explicit, not live facts.
export const trivia={science:[['Which planet is known as the Red Planet?','mars'],['What gas do plants absorb during photosynthesis?','carbon dioxide'],['How many legs does an insect have?','6'],['What is H2O commonly called?','water']],geography:[['Which ocean is the largest?','pacific'],['Which continent contains Brazil?','south america'],['Which country contains the city of Kyoto?','japan'],['Which country has the capital Ottawa?','canada']],general:[['How many squares are on a standard chessboard?','64'],['How many minutes are in an hour?','60'],['How many sides does a triangle have?','3'],['Which instrument has black and white keys?','piano']]};
export const words={easy:['apple','chair','house','water','plant','green','bread','light'],medium:['planet','garden','orange','window','silver','forest','bridge','castle'],hard:['journey','capture','balance','mystery','diamond','weather','blanket','thunder']};
export const riddles=[['What has keys but cannot open locks?','piano'],['What gets wetter as it dries?','towel'],['What has hands but cannot clap?','clock'],['What has a neck but no head?','bottle'],['What has teeth but cannot bite?','comb']];
export const capitals=[['India','new delhi'],['Japan','tokyo'],['France','paris'],['Canada','ottawa'],['Australia','canberra'],['Italy','rome'],['Brazil','brasilia'],['Egypt','cairo'],['Nepal','kathmandu'],['Kenya','nairobi']];
export const flags=[['🇮🇳','india'],['🇯🇵','japan'],['🇫🇷','france'],['🇨🇦','canada'],['🇦🇺','australia'],['🇮🇹','italy'],['🇧🇷','brazil'],['🇬🇧','united kingdom'],['🇳🇵','nepal'],['🇰🇪','kenya']];
export const emojis=[['🌧️🏹','rainbow'],['⭐🐟','starfish'],['🧈🪰','butterfly'],['🌞🌻','sunflower'],['🔥🪰','firefly'],['❄️👨','snowman']];
export const synonyms=[['happy',['glad','joyful']],['quick',['fast','rapid']],['small',['tiny','little']],['begin',['start']],['silent',['quiet']],['brave',['bold','courageous']],['difficult',['hard','challenging']]];
export const antonyms=[['hot',['cold']],['early',['late']],['wide',['narrow']],['empty',['full']],['accept',['reject']],['increase',['decrease']],['ancient',['modern']]];
export const spelling=[['aple','apple'],['recieve','receive'],['seperate','separate'],['definately','definitely'],['becaus','because'],['neccessary','necessary'],['tomorow','tomorrow']];
