import crypto from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import config from '../config/config.js';
const knownCodes=new Set(['ETIMEDOUT','TIMEOUT','AbortError','ECONNRESET','ECONNREFUSED','ENOTFOUND','EAI_AGAIN','NETWORK','ENOSPC','EROFS','EACCES','NO_KEYS','ALL_FAILED','NO_TOOL','SEARCH_FAIL','VOICE','PROVIDER','SHARP_MISSING','DISK','PRIVATE','REGION','BOT_CHECK','UNSUPPORTED','NO_RESULTS','EMPTY','FAILED','DOWNLOAD','MEDIA','USER_LIMIT','QUEUE_FULL','TOO_LARGE','BAD_TYPE','BLOCKED_HOST','empty','long','lang','busy','provider','Error','TypeError']);
export function errorCode(err){const c=String(err?.code||err?.cause?.code||err?.name||'');return knownCodes.has(c)?c:'UNKNOWN';}
const recent=[];const counts=new Map();const out=path.join(config.paths.data,'errors.json');
try{const saved=JSON.parse(fs.readFileSync(out,'utf8'));if(Array.isArray(saved))for(const x of saved.slice(0,100)){if(x&&/^[a-f0-9]{10}$/.test(x.id)&&/^[a-z0-9_]{1,30}$/.test(x.command)&&['timeout','network','storage','download','service','input','internal'].includes(x.kind)&&Number.isSafeInteger(x.count)&&x.count>0){const safe={id:x.id,at:Number(x.at)||0,command:x.command,kind:x.kind,code:knownCodes.has(x.code)?x.code:'UNKNOWN',count:x.count};recent.push(safe);const key=safe.command+':'+safe.kind;counts.set(key,Math.max(counts.get(key)||0,safe.count));}}}catch{}

export function classify(err){const code=String(err?.code||err?.cause?.code||err?.name||'');const text=String(err?.message||'');if(/ETIMEDOUT|TIMEOUT|ABORT/i.test(code)||/timeout|timed out/i.test(text))return 'timeout';if(/ECONNRESET|ECONNREFUSED|ENOTFOUND|EAI_AGAIN|NETWORK/i.test(code))return 'network';if(/ENOSPC|EROFS|EACCES|store unavailable|corrupt/i.test(code+' '+text))return 'storage';if(/^(empty|long|lang)$/.test(code))return 'input';if(/^(busy|provider)$/.test(code)||/NO_KEYS|ALL_FAILED|NO_TOOL|SEARCH_FAIL|VOICE|PROVIDER|SHARP_MISSING/i.test(code))return 'service';if(/DISK|ENOSPC/i.test(code))return 'storage';if(/PRIVATE|REGION|BOT_CHECK|UNSUPPORTED|NO_RESULTS|EMPTY|FAILED|DOWNLOAD|MEDIA/i.test(code))return 'download';if(/429|503|unavailable|rate.limit/i.test(code+' '+text))return 'service';if(/valid|use |cannot|cooldown|wait |expired|insufficient|limit|unknown|require|whole amount/i.test(text))return 'input';return 'internal';}
const messages={timeout:'The service took too long. Try again later.',network:'The network is temporarily unavailable. Try again later.',storage:'Storage is unavailable. No automatic reset was attempted. Contact an administrator.',download:'The download failed. Check the link and try again.',service:'The service is unavailable or busy. Try again later.',input:'Check the command input or cooldown. Use /help for the correct format.',internal:'This command could not finish. Contact an administrator with this reference.'};
export function failure(command,err){command=/^[a-z0-9_]{1,30}$/.test(String(command))?command:'unknown';const kind=classify(err);const id=crypto.randomBytes(5).toString('hex');const key=command+':'+kind;counts.set(key,(counts.get(key)||0)+1);if(counts.size>500)counts.clear();recent.unshift({id,at:Date.now(),command,kind,code:errorCode(err),count:counts.get(key)});recent.length=Math.min(recent.length,100);try{fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out+'.tmp',JSON.stringify(recent),{mode:0o600});fs.renameSync(out+'.tmp',out);}catch{}return {id,kind,message:messages[kind]};}
export const diagnostics=()=>({recent:structuredClone(recent),recurring:Object.fromEntries(counts)});
/** Retry only explicitly idempotent reads, before response/send or mutation. Never wrap a command. */
export async function safeRead(operation,{attempts=2,delay=250,sleep=ms=>new Promise(r=>setTimeout(r,ms))}={}){if(!Number.isSafeInteger(attempts)||attempts<1||attempts>3)throw new Error('Invalid retry bound');for(let n=1;;n++){try{return await operation(n);}catch(e){if(n>=attempts||!['timeout','network','service'].includes(classify(e)))throw e;await sleep(delay*n);}}}
