import {getSetting,setSetting,flushDatabase} from '../database/database.js';import {jidToNumber} from '../utils/helpers.js';import crypto from 'node:crypto';
export function validJid(jid){return typeof jid==='string'&&/^\d{7,15}@s\.whatsapp\.net$/.test(jid);}
export const sudoList=()=>getSetting('sudoUsers',[]).filter(validJid);
export function isSudo(ctx){const n=jidToNumber(ctx.senderJid||'');return !!n&&sudoList().includes(n+'@s.whatsapp.net');}
export async function changeSudo(jid,add,actor){if(!validJid(jid))throw new Error('Mention one valid WhatsApp phone-number JID');const list=sudoList();if(add&&list.includes(jid))throw new Error('User is already sudo');if(!add&&!list.includes(jid))throw new Error('User is not sudo');if(add&&list.length>=50)throw new Error('Maximum 50 sudo users');setSetting('sudoUsers',add?[...list,jid]:list.filter(x=>x!==jid));const tag=x=>crypto.createHash('sha256').update(String(x)).digest('hex').slice(0,12);const audit=getSetting('sudoAudit',[]);setSetting('sudoAudit',[{at:Date.now(),action:add?'add':'remove',actor:tag(actor),target:tag(jid)},...audit].slice(0,100));try{await flushDatabase(true);}catch(e){setSetting('sudoUsers',list);setSetting('sudoAudit',audit);throw e;}}
export async function permitted(ctx,cmd){const level=cmd.ownerOnly?'owner':cmd.requiredLevel||'user';if(!['user','admin','sudo','owner'].includes(level))return false;if(level==='user')return true;if(ctx.isOwner)return true;if(level==='owner')return !['addsudo','delsudo','listsudo'].includes(cmd.name)&&isSudo(ctx);if(level==='sudo')return isSudo(ctx);if(level==='admin'){if(!ctx.isGroup)return false;try{const m=await ctx.sock.groupMetadata(ctx.jid);const n=jidToNumber(ctx.senderJid||'');return m.participants.some(p=>['admin','superadmin'].includes(p.admin)&&[p.id,p.phoneNumber,p.jid].some(x=>jidToNumber(x||'')===n));}catch{return false;}}return false;}

export const fullAccess=ctx=>!!ctx.isOwner||isSudo(ctx);

/** Accept one explicit international number or one actual WhatsApp mention. Never infer a recipient from replies. */
export function sudoTarget(ctx){const m=ctx.msg?.message||{};const info=m.extendedTextMessage?.contextInfo||m.imageMessage?.contextInfo||{};const mentions=info.mentionedJid||[];if(mentions.length){if(mentions.length!==1||!validJid(mentions[0]))throw new Error('Mention exactly one phone-number user');return mentions[0];}const args=ctx.args||[];if(args.length!==1||!/^\+?[1-9]\d{6,14}$/.test(args[0]))throw new Error('Use one international number, e.g. /addsudo +16508702892, or mention one user');return args[0].replace(/^\+/,'')+'@s.whatsapp.net';}
