// Generated prompt bank. Family-friendly. Do not edit by hand.
export default {
"funny": [
"Send a voice note of you making animal sounds for 10 seconds.",
"Do your best impression of a news anchor reading the weather and send it as a voice note.",
"Change your WhatsApp status to \"I am a potato\" for one hour.",
"Send a voice note singing the happy birthday song in the weirdest voice you can.",
"Speak only in rhymes for the next 5 minutes.",
"Send a selfie with the funniest face you can make.",
"Text the last person you chatted with \"I know what you did\" and share their reaction.",
"Send a voice note of you laughing like a villain.",
"Type your next three messages using only emojis.",
"Do 10 jumping jacks and send a voice note of you counting while out of breath.",
"Imitate a famous Bollywood villain and send the clip.",
"Talk like a robot for the next 5 minutes in this chat.",
"Send a photo of the most random thing near you right now.",
"Write a two-line poem about the last thing you ate.",
"Send a voice note pretending to be a cricket commentator describing you drinking water.",
"Say the alphabet backwards as fast as you can and send a voice note.",
"Use only the letter \"a\" as vowels in your next message.",
"Sing the chorus of your favourite song using only \"la la la\" and send it.",
"Put a spoon on your nose and send a photo.",
"Send a voice note pretending to be a tour guide for your room.",
"Make up a short advertisement for a pen and send it as a voice note.",
"Do your best chicken dance and describe it in the group.",
"Send a screenshot of your most-used emoji list.",
"Call yourself \"Your Majesty\" in every message for the next 10 minutes.",
"Send a voice note saying \"I love Mondays\" in a very sad voice.",
"Reply to every message in this group in Shakespeare style for 5 minutes.",
"Send a photo of your breakfast, lunch, or dinner and give it a movie name.",
"Tell a joke in a serious news voice.",
"Speak without moving your lips and send a voice note.",
"Pretend to be a cat for 2 minutes in the chat. Only \"meow\" allowed.",
"Record yourself saying a tongue twister three times fast.",
"Draw a cartoon of yourself with your non-dominant hand and send the photo.",
"Send a voice note of a fake sneeze that sounds real.",
"Send a selfie wearing something on your head that is not a hat.",
"Rename your contact name to \"Chief Dancer\" for the next hour in your own phone and show us.",
"Send a voice note describing your day like a nature documentary.",
"Act like a toddler in the next 3 messages.",
"Say \"I love this group\" in as many languages as you know.",
"Send a voice note of you humming a song, and let us guess it.",
"Do a slow-motion walk across your room and describe how it felt.",
"Speak in a funny accent for the next 3 voice notes.",
"Send a picture of your left shoe and give it a dramatic backstory.",
"Do a mock interview as a mango and send it as a voice note.",
"Describe your crush as a type of food, without naming them.",
"Send a voice note saying a normal sentence while chewing on something.",
"Make a 10-second sales pitch for the item closest to you.",
"Make a funny name tag for every person in this group.",
"Attempt the \"pat head, rub belly\" challenge and tell us how it went.",
"Send a voice note where you laugh like Santa Claus.",
"Send a message in this chat typed with your elbow.",
"Send a picture of what is in your fridge and say you are a food critic.",
"Sing a lullaby in the style of a rock star and send it.",
"Give a dramatic reading of the last text message you received. No names.",
"Pretend to be a teacher scolding the group for talking in class.",
"Narrate your next 5 minutes like a sports commentator.",
"Send a photo with your best \"model\" pose.",
"Say \"I am the best\" 5 times in different emotions in a voice note.",
"Send a selfie with your hair styled in the funniest way possible.",
"Say a sentence while holding your nose and send it as a voice note.",
"Send the funniest meme you have saved in your phone.",
"Make up a new dance move and describe its name and steps.",
"Whisper your next 3 messages in all caps.",
"Speak like a pirate for the next 5 minutes.",
"Send a voice note giving your own horoscope for tomorrow in a dramatic way.",
"Make a funny face and send it as a sticker.",
"Put on a funny hat or a towel as a cape and send a photo.",
"Recite a nursery rhyme as a rap.",
"Say good night to the group as if you are an old-time movie hero.",
"Send a voice note where you sings a lullaby to an imaginary baby.",
"Send a voice note where you pretends to be a village sarpanch giving a speech.",
"Send a voice note where you reads the instructions on a shampoo bottle like a thriller.",
"Send a voice note where you announces your arrival at a railway station.",
"Send a voice note where you imitates a cartoon character you love.",
"Send a voice note where you says \"good morning\" in 5 different tones.",
"Send a voice note where you tells a short horror story in a funny voice.",
"Send a voice note where you describes a cricket match between two ants.",
"Send a voice note where you gives a fake weather report for your room.",
"Send a voice note where you pretends to be a rooster at sunrise.",
"Send a voice note where you plays a double role as a shopkeeper and a customer.",
"Send a voice note where you sings a song using only the word \"oye\".",
"Send a voice note where you pretends to order food at a fancy restaurant.",
"Send a voice note where you reads a recipe like a rap song.",
"Send a voice note where you pretends to be a baby who just discovered a phone.",
"Send a voice note where you says your full name like a royal announcement.",
"Send a voice note where you shouts a movie dialogue from the balcony.",
"Send a voice note where you laughs, then cries, then laughs again in 10 seconds.",
"Send a voice note where you pretends to be a GPS giving directions to the kitchen.",
"Send a voice note where you talks like a wise old grandpa giving advice.",
"Send a voice note where you imitates the sound of a train.",
"Send a voice note where you counts from 1 to 10 getting more excited each time.",
"Send a voice note where you reads out a random phone notification dramatically.",
"Send a voice note where you pretends to be a mimic of three different people in your family.",
"Send a voice note where you tells the story of the three little pigs in 20 seconds.",
"Send a voice note where you says a tongue twister while smiling.",
"Send a voice note where you pretends to be a cartoon villain on the phone.",
"Send a voice note where you sings the national anthem of your imaginary country.",
"Send a voice note where you pretends to be a news reporter at a chai stall.",
"Send a voice note where you pretends to be a sleepy teacher taking attendance.",
"Send a voice note where you describes the last meal you ate like a food blogger.",
"Send a voice note where you says \"I am the king of the world\" with full swag.",
"Send a voice note where you whispers a secret that is actually a joke.",
"Send a voice note where you pretends to call a pizza place and orders 100 pizzas.",
"Send a voice note where you tells everyone good night in a villain voice.",
"Send a voice note where you imitates a dog, a cat, and a cow in one go.",
"Send a voice note where you reads a tweet like a poet.",
"Send a voice note where you pretends to be a ghost saying hello.",
"Send a voice note where you gives a motivational speech to a chair.",
"Send a voice note where you reviews your last meal as a food critic.",
"Send a voice note where you pretends to talk to an alien.",
"Send a voice note where you sings a nursery rhyme as a heavy metal band.",
"Send a voice note where you announces tonight's dinner menu like a hotel manager.",
"Send a voice note where you explains how to tie shoelaces in the most dramatic way.",
"Send a voice note where you says the days of the week like a rap.",
"Send a voice note where you pretends to be an auto driver bargaining.",
"Send a voice note where you pretends to be a mother calling you for dinner.",
"Send a voice note where you pretends to be a tired shopkeeper at closing time.",
"Send a voice note where you tells a joke and laughs before the punchline.",
"Send a voice note where you says \"namaste\" in 10 funny styles.",
"Send a voice note where you pretends to be a kid reading a story.",
"Send a voice note where you recites the multiplication table of 7 like a rap.",
"Do your best impression of a cricket commentator and send it as a voice note.",
"Do your best impression of a Bollywood hero and send it as a voice note.",
"Do your best impression of a Bollywood villain and send it as a voice note.",
"Do your best impression of a strict teacher and send it as a voice note.",
"Do your best impression of a street vendor and send it as a voice note.",
"Do your best impression of a politician giving a speech and send it as a voice note.",
"Do your best impression of a news anchor and send it as a voice note.",
"Do your best impression of an auto driver and send it as a voice note.",
"Do your best impression of a baby crying and send it as a voice note.",
"Do your best impression of a rooster and send it as a voice note.",
"Do your best impression of a robot and send it as a voice note.",
"Do your best impression of a pirate and send it as a voice note.",
"Do your best impression of your father when he is angry and send it as a voice note.",
"Do your best impression of your mother when she calls for dinner and send it as a voice note.",
"Do your best impression of a snake charmer and send it as a voice note.",
"Do your best impression of a stand-up comedian and send it as a voice note.",
"Do your best impression of a movie trailer voice and send it as a voice note.",
"Do your best impression of a DJ at a wedding and send it as a voice note.",
"Do your best impression of a cartoon dog and send it as a voice note.",
"Do your best impression of a grumpy cat and send it as a voice note.",
"Do your best impression of a monkey and send it as a voice note.",
"Do your best impression of an elephant and send it as a voice note.",
"Do your best impression of a police inspector and send it as a voice note.",
"Do your best impression of a cricket umpire and send it as a voice note.",
"Do your best impression of a yoga teacher and send it as a voice note.",
"Do your best impression of a rapper and send it as a voice note.",
"Do your best impression of a game show host and send it as a voice note.",
"Do your best impression of a doctor on a phone call and send it as a voice note.",
"Do your best impression of a school principal and send it as a voice note.",
"Do your best impression of a flight attendant and send it as a voice note.",
"Do your best impression of a cartoon penguin and send it as a voice note.",
"Do your best impression of a lion roaring and send it as a voice note.",
"Do your best impression of a TikTok star and send it as a voice note.",
"Do your best impression of a sleepy sloth and send it as a voice note.",
"Do your best impression of a chef on a cooking show and send it as a voice note.",
"Do your best impression of a delivery guy at the door and send it as a voice note.",
"Do your best impression of a tour guide and send it as a voice note.",
"Do your best impression of a mobile network voice saying \"the number you dialled\" and send it as a voice note.",
"Do your best impression of a salesperson selling a pen and send it as a voice note.",
"Do your best impression of a fortune teller and send it as a voice note.",
"Put \"I am a potato\" as your status for one hour and show us.",
"Put \"Free hugs available\" as your status for one hour and show us.",
"Put \"Looking for my lost sleep\" as your status for one hour and show us.",
"Put \"Chai over everything\" as your status for one hour and show us.",
"Put \"Currently loading, please wait\" as your status for one hour and show us.",
"Put \"Do not disturb, I am being awesome\" as your status for one hour and show us.",
"Put \"Professional overthinker\" as your status for one hour and show us.",
"Put \"Eat, sleep, repeat\" as your status for one hour and show us.",
"Put \"I came, I saw, I forgot\" as your status for one hour and show us.",
"Put \"Today I woke up like this\" as your status for one hour and show us.",
"Put \"Under construction\" as your status for one hour and show us.",
"Put \"Official snack inspector\" as your status for one hour and show us.",
"Put \"Searching for the meaning of Wi-Fi\" as your status for one hour and show us.",
"Put \"My bed misses me\" as your status for one hour and show us.",
"Put \"Ctrl+Alt+Delete my Monday\" as your status for one hour and show us.",
"Put \"Mood: filmy\" as your status for one hour and show us.",
"Put \"Genius at work\" as your status for one hour and show us.",
"Put \"Professional napper\" as your status for one hour and show us.",
"Put \"404 motivation not found\" as your status for one hour and show us.",
"Put \"I am not lazy, I am on energy-saving mode\" as your status for one hour and show us.",
"Put \"I am the main character\" as your status for one hour and show us.",
"Put \"Namaste from the other side\" as your status for one hour and show us.",
"Put \"Breaking news: I am hungry\" as your status for one hour and show us.",
"Put \"Cheese is my love language\" as your status for one hour and show us.",
"Put \"Coffee first, then talk\" as your status for one hour and show us.",
"Put \"Born to be wild, forced to be at home\" as your status for one hour and show us.",
"Put \"Keep calm and eat samosa\" as your status for one hour and show us.",
"Put \"Loading happiness\" as your status for one hour and show us.",
"Put \"Spreading smiles, one sticker at a time\" as your status for one hour and show us.",
"Put \"Plot twist: I am sleeping\" as your status for one hour and show us.",
"Put \"Looking for a nap buddy\" as your status for one hour and show us.",
"Put \"Single and ready to nap\" as your status for one hour and show us.",
"Put \"This is my pose\" as your status for one hour and show us.",
"Put \"Dancing in my head\" as your status for one hour and show us.",
"Put \"My brain has too many tabs open\" as your status for one hour and show us.",
"Put \"Sponsored by chai\" as your status for one hour and show us.",
"Put \"Warning: contains sarcasm\" as your status for one hour and show us.",
"Put \"Please do not feed the introvert\" as your status for one hour and show us.",
"Put \"Exploring my fridge\" as your status for one hour and show us.",
"Put \"I am fluent in sarcasm\" as your status for one hour and show us.",
"Chat like a Shakespeare character for the next 5 minutes.",
"Chat like someone who just woke up for the next 5 minutes.",
"Chat like a very polite British butler for the next 5 minutes.",
"Chat like a sports commentator for the next 5 minutes.",
"Chat like a news reporter for the next 5 minutes.",
"Chat like a cowboy for the next 5 minutes.",
"Chat like a pirate for the next 5 minutes.",
"Chat like a robot for the next 5 minutes.",
"Chat like a drama queen for the next 5 minutes.",
"Chat like an excited kid for the next 5 minutes.",
"Chat like a wise old monk for the next 5 minutes.",
"Chat like a villain from a movie for the next 5 minutes.",
"Chat like a Bollywood hero for the next 5 minutes.",
"Chat like a strict teacher for the next 5 minutes.",
"Chat like a motivational speaker for the next 5 minutes.",
"Chat like a tired dad for the next 5 minutes.",
"Chat like a gossiping aunty for the next 5 minutes.",
"Chat like a detective for the next 5 minutes.",
"Chat like a talking cat for the next 5 minutes.",
"Chat like a baby for the next 5 minutes.",
"Send a voice note saying \"Do not worry, be happy\" shy.",
"Send a voice note saying \"I am hungry\" in love.",
"Send a voice note saying \"I miss you\" sleepy.",
"Send a voice note saying \"Wake me up when it is Friday\" shy.",
"Send a voice note saying \"I lost my sleep\" like a very old person.",
"Send a voice note saying \"I have a secret\" like a robot.",
"Send a voice note saying \"You got this\" like a very old person.",
"Send a voice note saying \"Let us go on an adventure\" like a villain.",
"Send a voice note saying \"I am on my way\" like a sports commentator.",
"Send a voice note saying \"This is my last message\" angry.",
"Send a voice note saying \"Wake me up when it is Friday\" angry.",
"Send a voice note saying \"Good morning world\" like a very old person.",
"Send a voice note saying \"Thank you for being you\" sleepy.",
"Send a voice note saying \"It is chai time\" like a robot.",
"Send a voice note saying \"Wake me up when it is Friday\" very sad.",
"Send a voice note saying \"I am on my way\" sleepy.",
"Send a voice note saying \"You got this\" in a whisper.",
"Send a voice note saying \"I have a secret\" sleepy.",
"Send a voice note saying \"You are awesome\" very sad.",
"Send a voice note saying \"Good morning world\" in love.",
"Send a voice note saying \"I am hungry\" extremely excited.",
"Send a voice note saying \"It is chai time\" shy.",
"Send a voice note saying \"I miss you\" like a sports commentator.",
"Send a voice note saying \"You got this\" very sad.",
"Send a voice note saying \"This is my last message\" in a whisper.",
"Send a voice note saying \"Wake me up when it is Friday\" extremely excited.",
"Send a voice note saying \"It is chai time\" extremely excited.",
"Send a voice note saying \"I have a secret\" in love.",
"Send a voice note saying \"Let us go on an adventure\" like a very old person.",
"Send a voice note saying \"Do not worry, be happy\" in love.",
"Send a voice note saying \"I lost my sleep\" shy.",
"Send a voice note saying \"This is my last message\" like a very old person.",
"Send a voice note saying \"Do not worry, be happy\" like a robot.",
"Send a voice note saying \"I am hungry\" like a very old person.",
"Send a voice note saying \"Do not worry, be happy\" like a very old person.",
"Send a voice note saying \"I miss you\" like a very old person.",
"Send a voice note saying \"I am hungry\" shy.",
"Send a voice note saying \"This is my last message\" like a kid.",
"Send a voice note saying \"I forgot my keys\" like a kid.",
"Send a voice note saying \"Wake me up when it is Friday\" like a robot.",
"Send a voice note saying \"I have a secret\" very sad.",
"Send a voice note saying \"Do not worry, be happy\" like a sports commentator.",
"Send a voice note saying \"I forgot my keys\" angry.",
"Send a voice note saying \"You are awesome\" shy.",
"Send a voice note saying \"You are awesome\" sleepy.",
"Send a voice note saying \"I have a secret\" like a kid.",
"Send a voice note saying \"I miss you\" in love.",
"Send a voice note saying \"Thank you for being you\" in love.",
"Send a voice note saying \"It is chai time\" like a kid.",
"Send a voice note saying \"I have a secret\" shy.",
"Send a voice note saying \"It is chai time\" like a very old person.",
"Send a voice note saying \"I am on my way\" in a whisper.",
"Send a voice note saying \"I am hungry\" like a villain.",
"Send a voice note saying \"This is my last message\" in love.",
"Send a voice note saying \"Thank you for being you\" angry.",
"Send a voice note saying \"I lost my sleep\" in a whisper.",
"Send a voice note saying \"You are awesome\" angry.",
"Send a voice note saying \"I lost my sleep\" like a robot.",
"Send a voice note saying \"Good morning world\" in a whisper.",
"Send a voice note saying \"Do not worry, be happy\" sleepy.",
"Draw a house with one eye closed on paper and send the photo.",
"Draw your best friend as a cartoon on paper and send the photo.",
"Draw a map of an imaginary island on paper and send the photo.",
"Draw your dream car on paper and send the photo.",
"Draw a flower in 20 seconds on paper and send the photo.",
"Draw a cat using a single line on paper and send the photo.",
"Draw your favourite animal without lifting the pen on paper and send the photo.",
"Draw a self-portrait in 30 seconds on paper and send the photo.",
"Draw a superhero with a funny power on paper and send the photo.",
"Draw a logo for this group on paper and send the photo.",
"Draw a monster that is actually cute on paper and send the photo.",
"Draw a snowman in summer on paper and send the photo.",
"Draw your name as a logo on paper and send the photo.",
"Draw your ideal pet on paper and send the photo.",
"Draw a comic strip of 3 panels on paper and send the photo."
],
"sad": [
"Send a heartfelt thank-you message to someone who helped you in a tough time.",
"Write down one thing you are grateful for today and share it here.",
"Message an old friend you have not talked to for a long time and say hi.",
"Send a voice note telling the group about a memory that makes you smile through tears.",
"Write a short letter to your younger self and read the first line to us.",
"Share a song that always makes you emotional and say why.",
"Tell someone in your life today that you are proud of them.",
"Share a photo from your childhood and tell us what you miss from that time.",
"Call a grandparent or an elder in your family and ask about their day.",
"Share one thing you forgave someone for and how it felt.",
"Write one kind sentence to every person in this group.",
"Send a message to a person you miss telling them so.",
"Share a picture of a place that holds an emotional memory for you.",
"Tell the group about a lesson you learned from something that hurt.",
"Send a voice note describing the best hug you ever received.",
"Write one thing you wish to tell your future self.",
"Share one thing you want to let go of this month.",
"Send a heart emoji to the five people you care about most in your contacts.",
"Tell us about someone whose kindness you will never forget.",
"Send a message thanking your parents for something small.",
"Share the saddest song on your playlist and how it makes you feel.",
"Share an old picture with someone you miss, with a short caption.",
"Write a short goodbye note to a habit you want to quit.",
"Tell us about a time you felt proud even though no one noticed.",
"Compliment each person in this group on one thing you really admire.",
"Write down three things that give you hope and share them.",
"Share a quote that helped you in a hard time.",
"Say sorry to someone you have been meaning to apologise to, even if just in a text.",
"Call your best friend and tell them what they mean to you.",
"Share a message that comforted you the most.",
"Make a list of three things you would tell your younger self to not worry about.",
"Send a voice note saying something comforting to the person who feels low in this group.",
"Hug someone near you for 10 seconds and tell us how it felt.",
"Write a small poem about missing home.",
"Tell us about a dream you set aside and what you would say to it now.",
"Draw a sad face, then turn it into a smiley, and send the photo.",
"Share one memory with a friend that you would relive if you could.",
"Send a thank-you voice note to a teacher who made a difference.",
"Message someone and tell them you are thinking of them today.",
"Post a positive quote on your status that could help someone having a bad day.",
"Share the most heartfelt compliment you have ever received.",
"Write down your biggest fear and a way to face it.",
"Tell us about your best childhood friend and what happened to them.",
"Write a short thank-you note to your pet or to your favourite place.",
"Share the hardest goodbye you have had and what helped you.",
"Tell the group one small thing that makes you cry happy tears.",
"Send a message to your future self to open one year from now.",
"Share one thing about yourself you are proud of but rarely say.",
"Say something kind to a person you had a fight with.",
"Pick a sad song, play it, and share one line that hits hard.",
"Message a sibling and tell them one thing you appreciate about them.",
"Make a gratitude list of 5 items from today and send it.",
"Share a small win from this week that you are proud of.",
"Look at an old photo and write what the person in it would want to hear today.",
"Tell us about someone who believed in you.",
"Say one thing you would tell your younger self before an exam or interview.",
"Share a place you want to visit once you are feeling better.",
"Write one affirmation for yourself and post it on your status.",
"Share a short voice note of encouragement for the group.",
"Describe the happiest day you can remember in 3 lines.",
"Tell us about a person who changed your life for good.",
"Find something you have kept for years and tell us why you cannot throw it away.",
"Tell us what home smells like to you.",
"Write a thank-you message to yourself for getting through this year.",
"Share a memory you would love to relive.",
"Share a person who taught you patience.",
"Share a song that takes you back to an old time.",
"Share a place you want to visit again.",
"Share the best advice you got from an elder.",
"Share a small kindness you will never forget.",
"Share a time you felt proud of your own strength.",
"Share something you wish you had done sooner.",
"Share a lesson from a hard year.",
"Share a moment when a friend stood by you.",
"Share one thing you forgave yourself for.",
"Share something you are learning to accept.",
"Share a person you wish you had thanked.",
"Share a childhood habit you miss.",
"Share a photo that brings back a feeling.",
"Share a goal you are slowly working towards.",
"Share a time you felt truly at peace.",
"Share a thing that always makes you feel better.",
"Share an old gift that means a lot.",
"Share the best day of this year so far."
],
"romantic": [
"Send a voice note of you reading a filmy romantic dialogue with full drama.",
"Write a two-line shayari about the moon and send it here.",
"Send a rose emoji to the person you would take on a dream date.",
"Describe your ideal date night in exactly 3 sentences.",
"Sing one line of a romantic song for the group.",
"Create a cheesy pick-up line and say it in a voice note.",
"Send a photo of the sunset or sky at your place with a romantic caption.",
"Write a love poem for your favourite food.",
"Plan a perfect surprise date for a friend and describe it in 4 lines.",
"Recite your favourite romantic movie scene in your own words.",
"Send a heart-shaped photo of anything around you.",
"Make a playlist of 3 songs you would play on a date and share it.",
"Describe your dream wedding in 3 sentences.",
"Send a voice note saying \"I will always be there for you\" in your most romantic voice.",
"Write a mock love letter from a coffee cup to a teabag.",
"Send a flower or a picture of a flower to someone who made you smile today.",
"Do a filmy proposal to a cushion or a teddy and describe it.",
"Write a good morning message that would melt anybody's heart.",
"Describe your crush's smile without naming them.",
"Write a poem with the word \"chai\" in every line.",
"Show your best \"hero entry\" pose and send the photo.",
"Recreate a famous romantic movie pose with a friend or an object and share the photo.",
"Pick one person in the group and give them a sweet compliment.",
"Send a voice note giving relationship advice as a filmy uncle.",
"Invent a romantic nickname for the person who sent the last message in this chat.",
"Write the opening line of a romance novel starring you.",
"Plan a candlelight dinner using only what is in your kitchen and send a photo of the setup.",
"Write a four-line song about a monsoon love story.",
"Send the cutest couple picture you can find on the internet and give them names.",
"Send a voice note speaking in a romantic movie narrator voice about your day.",
"Dedicate a song to someone in the group without saying why.",
"Recite the \"I love you\" phrase in 3 different languages.",
"Write a \"dear future partner\" note and share one line.",
"Create a pun about love and share it.",
"Send a picture of your favourite romantic place or a dream destination.",
"Tell us your best flirting line, kept clean and cheesy.",
"Draw a heart with your name and a doodle of your ideal date.",
"Write a love letter from the moon to the sun and read two lines.",
"Send a voice note giving a toast to love.",
"Send a short voice note whispering \"good night\" in a sweet way.",
"Make a couple name by mixing two famous characters and explain why they match.",
"Describe the most romantic place in your city and why.",
"Make a bouquet using emojis and send it.",
"Say something romantic about the rain in 15 seconds.",
"Rate your own flirting skills out of 10 and justify.",
"Send a screenshot of a romantic song you are listening to right now.",
"Describe your first date idea with a famous couple from a movie.",
"Tell us a romantic fact or tradition from your culture.",
"Pose with a stuffed toy as if on a date and send the photo.",
"Make up a love story about two vegetables.",
"Write a cute reply to \"Are you free this evening?\" as a filmy hero.",
"Write a short poem called \"Ek Chai Aur Tum\".",
"Describe a sweet gesture that someone would like to receive on their birthday.",
"Make a short drama dialogue between a lover and the weather.",
"Tell a love story in exactly 6 words.",
"Say your best compliment in a voice note without using the word \"beautiful\".",
"Share the sweetest line you have ever read in a book or a song.",
"Make a love-themed riddle for the group.",
"Write a romantic caption for the last photo you took.",
"Create a short rhyme about love and read it out loud.",
"Choose a flower that matches each person in the group and say why.",
"Create a \"love recipe\": three ingredients that make a perfect relationship.",
"Write a poetic good night message for the group.",
"Describe your perfect rainy evening for two in a voice note.",
"Write a filmy dialogue about a road trip together and share it.",
"Write a song title about a quiet library and share it.",
"Write a caption for a couple photo about a train journey and share it.",
"Write a two-line poem about a long drive and share it.",
"Write a caption for a couple photo about a road trip together and share it.",
"Write a two-line poem about a train journey and share it.",
"Write a filmy dialogue about a quiet library and share it.",
"Write a good night message about a rainy evening and share it.",
"Write a two-line poem about a handwritten note and share it.",
"Write a song title about a surprise gift and share it.",
"Write a two-line poem about a road trip together and share it.",
"Write a caption for a couple photo about a surprise gift and share it.",
"Write a good night message about a moonlit walk and share it.",
"Write a filmy dialogue about a train journey and share it.",
"Write a short shayari about a train journey and share it.",
"Write a song title about a festival night and share it.",
"Write a short shayari about a first meeting and share it.",
"Write a caption for a couple photo about a moonlit walk and share it.",
"Write a short shayari about a long drive and share it.",
"Write a good night message about a festival night and share it.",
"Write a song title about a handwritten note and share it.",
"Write a short shayari about a moonlit walk and share it.",
"Write a caption for a couple photo about a festival night and share it.",
"Write a short shayari about a sunset and share it.",
"Write a good night message about a first meeting and share it.",
"Write a two-line poem about a moonlit walk and share it.",
"Write a short shayari about a surprise gift and share it.",
"Write a short shayari about a chai date and share it.",
"Write a filmy dialogue about a long drive and share it.",
"Write a caption for a couple photo about a quiet library and share it.",
"Write a song title about a first meeting and share it.",
"Write a two-line poem about a festival night and share it.",
"Write a caption for a couple photo about a chai date and share it.",
"Write a two-line poem about a surprise gift and share it.",
"Write a good night message about a quiet library and share it.",
"Write a filmy dialogue about a first meeting and share it.",
"Write a good night message about a chai date and share it.",
"Write a caption for a couple photo about a sunset and share it.",
"Write a short shayari about a quiet library and share it.",
"Write a good night message about a road trip together and share it."
],
"love": [
"Tell three people you care about why they matter to you.",
"Send a message to your best friend saying what you value most about them.",
"Write a thank-you note to a family member and send it.",
"Draw a heart and fill it with names of people you love, then share it.",
"Give a heartfelt compliment to each person who has sent a message in the last hour.",
"Send a voice note saying \"I appreciate you\" to the group in your warmest voice.",
"Surprise someone at home with a small good deed and tell us what it was.",
"Cook or make a drink for someone in your home and send a photo.",
"Write down 5 things you love about your life.",
"Give your mother or father a big hug and tell us what they said.",
"Write a list of 3 things you love about this group.",
"Tell your best friend a memory you treasure about them.",
"Send the sweetest message you can think of to someone special, no names.",
"Make a card for someone you love using paper and a pen and send a photo.",
"Tell your pet or a plant how much you love them in a voice note.",
"Share a picture of your favourite person in your family with a caption about why.",
"Create a friendship slogan for the group.",
"Describe your best friend using only 5 emojis.",
"Say \"thank you\" to 3 people today for something small.",
"Create a poem of 4 lines about friendship.",
"Share a picture of the best gift you ever received and who gave it.",
"Tell someone you love them using only emojis.",
"Choose a song that represents your friendship with someone in the group and share it.",
"Give someone a nickname that shows how much you like them.",
"Describe the group using one word each for every member.",
"Share your favourite family tradition and why you love it.",
"Tell the group about a small thing someone does that makes you smile every time.",
"Surprise a friend with a voice note of their favourite song's chorus.",
"Say 3 nice things about your hometown.",
"Write a sweet message for your future family.",
"Record a message of encouragement for someone who has an exam or interview coming up.",
"Share a recipe your family makes with love.",
"Do something kind for a stranger today and tell us what it was.",
"Write the best thing you learned from your parents.",
"Give a shoutout to a person who always supports you.",
"Make a list of 5 reasons to love Sundays.",
"Hug a tree, a pillow, or a person and send the photo.",
"Plan a mini surprise party for someone in the group and describe it.",
"Share what you love about the person who sent the last message.",
"Say one thing you love about each season.",
"Write a thank-you card for your favourite teacher.",
"Dedicate your next status to someone you love.",
"Send a good-luck message to everyone who has something coming up this week.",
"Introduce your best friend to the group in 3 sentences, full of praise.",
"Make a \"reasons I love you\" list for your mom, five lines.",
"Send a message to your cousin saying how much you value them.",
"Describe a hug in one sentence.",
"Send a voice note giving 5 compliments to yourself.",
"Give someone in the group a sweet virtual gift and explain it.",
"Offer your help to someone in the group for any small thing.",
"Share a picture of the place you love the most at home.",
"Tell us how you would celebrate your best friend's birthday.",
"Share a story about when someone showed you unexpected kindness.",
"Write a goodnight wish for a loved one, in a poetic way.",
"Make a drawing of your family and share it.",
"Make a short video or voice note thanking the person who inspires you.",
"Share the most loving thing someone has said to you.",
"Write a toast for a friend's wedding in four lines.",
"Tell the group your all-time favourite family photo story.",
"Share a hobby of a loved one and what it means to you.",
"Say \"I am grateful for you\" to three people and tell us their reactions.",
"Message a friend you have not spoken to in a while and say you care.",
"Give a compliment to someone using a rhyme.",
"Create a \"love tag\" for each person in the group.",
"Write a rap verse about the moon and share it here.",
"Write a slogan about sleep and share it here.",
"Write a limerick about exam stress and share it here.",
"Write a rap verse about your best friend and share it here.",
"Write a riddle about cricket and share it here.",
"Write a riddle about a train journey and share it here.",
"Write a haiku about a surprise and share it here.",
"Write a rap verse about monsoon and share it here.",
"Write a riddle about your last birthday and share it here.",
"Write a limerick about a surprise and share it here.",
"Write a song title about the moon and share it here.",
"Write a tweet about a Monday morning and share it here.",
"Write a movie title about a train station and share it here.",
"Write a short story in 3 sentences about biryani and share it here.",
"Write a product advertisement about your school bag and share it here.",
"Write a shayari about a train journey and share it here.",
"Write a short story in 3 sentences about WiFi and share it here.",
"Write a shayari about your room and share it here.",
"Write a rap verse about your school bag and share it here.",
"Write a motto about WiFi and share it here.",
"Write a movie title about a power cut and share it here.",
"Write a movie title about WiFi and share it here.",
"Write a haiku about your school bag and share it here.",
"Write a product advertisement about your phone charger and share it here.",
"Write a song title about WiFi and share it here.",
"Write a tweet about a rickshaw and share it here.",
"Write a song title about a lazy Sunday and share it here.",
"Write a slogan about a train journey and share it here.",
"Write a short story in 3 sentences about a train station and share it here.",
"Write a limerick about an umbrella and share it here.",
"Write a rap verse about your favourite snack and share it here.",
"Write a riddle about monsoon and share it here.",
"Write a motto about exam stress and share it here.",
"Write a motto about your room and share it here.",
"Write a song title about a long weekend and share it here.",
"Write a tweet about exam stress and share it here.",
"Write a product advertisement about a power cut and share it here.",
"Write a slogan about a Monday morning and share it here.",
"Write a shayari about your last birthday and share it here.",
"Write a shayari about your phone charger and share it here.",
"Write a rap verse about ice cream and share it here.",
"Write a haiku about cricket and share it here.",
"Write a riddle about your school bag and share it here.",
"Write a tweet about traffic and share it here.",
"Write a short story in 3 sentences about monsoon and share it here.",
"Write a slogan about a wedding and share it here.",
"Write a song title about a train journey and share it here.",
"Write a shayari about a pet and share it here.",
"Write a shayari about monsoon and share it here.",
"Write a song title about Diwali lights and share it here.",
"Write a slogan about an umbrella and share it here.",
"Write a motto about a surprise and share it here.",
"Write a limerick about your school bag and share it here.",
"Write a shayari about mangoes and share it here.",
"Write a haiku about a power cut and share it here.",
"Write a riddle about mangoes and share it here.",
"Write a motto about a wedding and share it here.",
"Write a short story in 3 sentences about the moon and share it here.",
"Write a motto about homework and share it here.",
"Write a limerick about a long weekend and share it here.",
"Write a limerick about monsoon and share it here.",
"Write a short story in 3 sentences about a wedding and share it here.",
"Write a movie title about biryani and share it here.",
"Write a shayari about a lazy Sunday and share it here.",
"Write a shayari about a power cut and share it here.",
"Write a riddle about the moon and share it here.",
"Write a shayari about homework and share it here.",
"Write a haiku about a long weekend and share it here.",
"Write a product advertisement about mangoes and share it here.",
"Write a motto about mangoes and share it here.",
"Text your best friend a random fun fact, and tell us how they replied.",
"Text your cousin a joke, and tell us how they replied.",
"Text an old friend a \"remember when\" memory, and tell us how they replied.",
"Text a family member a compliment, and tell us how they replied.",
"Text a classmate a thank-you, and tell us how they replied.",
"Text someone you have not spoken to in a month a good-luck wish, and tell us how they replied.",
"Text your neighbour a good-morning greeting, and tell us how they replied.",
"Text a colleague or teacher a \"have a great day\" message, and tell us how they replied.",
"Text your sibling a funny meme, and tell us how they replied.",
"Text your mother a thank-you for something specific, and tell us how they replied.",
"Send a short compliment to the person who makes you laugh the most.",
"Send a dramatic compliment to the last person who messaged in this group.",
"Send a honest compliment to the person who makes you laugh the most.",
"Send a poetic compliment to the group admin.",
"Send a kind compliment to the person who sent the last emoji.",
"Send a sweet compliment to the quietest person in this group.",
"Send a funny compliment to the person who joined this group most recently.",
"Send a funny compliment to the group admin.",
"Send a poetic compliment to the person who joined this group most recently.",
"Send a kind compliment to the last person who messaged in this group.",
"Send a kind compliment to the person who joined this group most recently.",
"Send a short compliment to the person who sent the last emoji.",
"Send a dramatic compliment to the person who joined this group most recently.",
"Send a short compliment to the quietest person in this group.",
"Send a unexpected compliment to the group admin.",
"Send a dramatic compliment to the person you talk to the least here.",
"Send a sweet compliment to the person who makes you laugh the most.",
"Send a honest compliment to the last person who messaged in this group.",
"Send a funny compliment to the person whose name comes first alphabetically.",
"Send a kind compliment to the person whose name comes first alphabetically.",
"Send a short compliment to the person who joined this group most recently.",
"Send a poetic compliment to the person you talk to the least here.",
"Send a kind compliment to the person you talk to the least here.",
"Send a honest compliment to the person who joined this group most recently.",
"Send a dramatic compliment to the quietest person in this group.",
"Send a sweet compliment to the group admin.",
"Send a poetic compliment to the last person who messaged in this group.",
"Send a short compliment to the person you talk to the least here.",
"Send a funny compliment to the person who sent the last emoji.",
"Send a short compliment to the person whose name comes first alphabetically.",
"Send a dramatic compliment to the person who makes you laugh the most.",
"Send a short compliment to the last person who messaged in this group.",
"Send a honest compliment to the person whose name comes first alphabetically.",
"Send a short compliment to the group admin.",
"Send a honest compliment to the person you talk to the least here.",
"Send a unexpected compliment to the last person who messaged in this group.",
"Send a funny compliment to the last person who messaged in this group.",
"Send a dramatic compliment to the group admin.",
"Send a sweet compliment to the person who joined this group most recently.",
"Send a honest compliment to the group admin."
],
"brother": [
"Send your brother a funny voice note and share his reaction.",
"Send a photo of you and your brother, or an old picture of him, with a funny caption.",
"Ask your brother to rate your singing and tell us his score.",
"Challenge your brother to a thumb war and report the winner.",
"Ask your brother for a joke and share it here.",
"Ask your brother to say something nice about you and send it here.",
"Let your brother pick a silly name for you for the next hour.",
"Do a 30-second dance with your brother and send the video or describe it.",
"Send a message to your brother saying \"You are the best\" without any reason and share his reply.",
"Have your brother choose a song and sing the first line.",
"Challenge your brother to a staring contest and report the winner.",
"Make your brother laugh within one minute and describe how.",
"Share a pic of your brother's funniest sleeping pose, if you have one, or describe it.",
"Ask your brother to teach you something new in 5 minutes.",
"Make a mini handshake with your brother and show it.",
"Let your brother give you a silly challenge, then do it.",
"Ask your brother what he thinks your biggest talent is and share the answer.",
"Race your brother to finish a glass of water and report who won.",
"Cook or make something together with your brother and send a photo.",
"Share the funniest nickname you gave your brother as a kid.",
"Call your brother and sing \"Happy Birthday\" even if it is not his birthday.",
"Write 3 compliments about your brother and send them to him.",
"Ask your brother to describe you in 3 words and share it.",
"Make a superhero poster of your brother using doodles.",
"Trade phone wallpapers with your brother for a day.",
"Let your brother choose your status for one hour.",
"Ask your brother his best memory of you two and share it.",
"Challenge your brother to a game and let him choose the punishment.",
"Offer your brother help with a chore without being asked.",
"Take a funny selfie with your brother wearing the same facial expression.",
"Ask your brother to share his favourite childhood game with the group.",
"Ask your brother what he would change about you and take it with a smile.",
"Tell your brother one thing you are proud of him for and share how he reacts.",
"Take a brother-and-me photo with the same pose as an old childhood pic.",
"Teach your brother a tongue twister and see who says it fastest.",
"Do an arm wrestle with your brother and share the result.",
"Send a thank-you message to your brother for something he did for you.",
"Write a funny short story about you and your brother as secret agents.",
"Ask your brother his dream job and tell us what it is.",
"Ask your brother to give you a motivational speech for 20 seconds.",
"Share your brother's most-used phrase and imitate how he says it.",
"Have a quick quiz with your brother about each other and tell the score.",
"Make your brother a card that says \"World's Okayest Brother\" and send a photo.",
"Lend something of yours to your brother for a day and tell us what.",
"Ask your brother to name your biggest weakness, then make a plan to fix it.",
"Give your brother a compliment about his style or his skills.",
"Share a childhood story that your brother hates being told.",
"Write a mini newspaper headline about your brother's most famous mishap.",
"Make your brother laugh with an impression of him and share how it went.",
"Share what you think your brother will be famous for.",
"Share a picture of the two of you from at least 5 years ago.",
"Ask your brother to pick your next dare.",
"Challenge your brother to a 10-second plank and see who lasts longer.",
"Do a comedy skit with your brother for 30 seconds.",
"Create a secret code word with your brother and share it with the group.",
"Ask your brother to pick a movie for you to watch tonight.",
"Ask your brother for advice on something and follow it for a day.",
"Tell your brother three things you like about him in a voice note.",
"Name three things your brother is better at than you.",
"Mimic your brother's walk and let the group guess who it is.",
"Ask your brother to rate your outfit out of ten.",
"Let your brother make a meme about you and share it.",
"Make a \"Brothers Forever\" caption and use it on your status.",
"Ask your brother to tell you their favourite memory of the two of you and share what he says.",
"Ask your brother to share one thing they are scared of and share what he says.",
"Ask your brother to name your best quality and share what he says.",
"Ask your brother to describe you in a funny line and share what he says.",
"Ask your brother to guess your favourite song and share what he says.",
"Ask your brother to pick a movie you must watch tonight and share what he says.",
"Ask your brother to tell you a secret skill they have and share what he says.",
"Ask your brother to sing one line of any song and share what he says.",
"Ask your brother to choose a snack you must eat and share what he says.",
"Ask your brother to tell you what they love about home and share what he says.",
"Ask your brother to give you a challenge for one hour and share what he says.",
"Ask your brother to tell you their dream for the next year and share what he says.",
"Ask your brother to share a funny childhood story and share what he says.",
"Ask your brother to describe a day they would like to spend with you and share what he says.",
"Ask your brother to say one thing you do that makes them smile and share what he says.",
"Ask your brother to draw a doodle of you and share what he says.",
"Ask your brother to give you a nickname for the day and share what he says.",
"Ask your brother to pick your outfit tomorrow and share what he says.",
"Ask your brother to share what they want to learn this year and share what he says.",
"Ask your brother to teach you a trick in one minute and share what he says."
],
"sister": [
"Send your sister a funny voice note and share her reaction.",
"Send a photo of you and your sister, or an old picture of her, with a funny caption.",
"Ask your sister to rate your singing and tell us her score.",
"Challenge your sister to a thumb war and report the winner.",
"Ask your sister for a joke and share it here.",
"Ask your sister to say something nice about you and send it here.",
"Let your sister pick a silly name for you for the next hour.",
"Do a 30-second dance with your sister and send the video or describe it.",
"Send a message to your sister saying \"You are the best\" without any reason and share her reply.",
"Have your sister choose a song and sing the first line.",
"Challenge your sister to a staring contest and report the winner.",
"Make your sister laugh within one minute and describe how.",
"Share a pic of your sister's funniest sleeping pose, if you have one, or describe it.",
"Ask your sister to teach you something new in 5 minutes.",
"Make a mini handshake with your sister and show it.",
"Let your sister give you a silly challenge, then do it.",
"Ask your sister what she thinks your biggest talent is and share the answer.",
"Race your sister to finish a glass of water and report who won.",
"Cook or make something together with your sister and send a photo.",
"Share the funniest nickname you gave your sister as a kid.",
"Call your sister and sing \"Happy Birthday\" even if it is not her birthday.",
"Write 3 compliments about your sister and send them to her.",
"Ask your sister to describe you in 3 words and share it.",
"Make a superhero poster of your sister using doodles.",
"Trade phone wallpapers with your sister for a day.",
"Let your sister choose your status for one hour.",
"Ask your sister her best memory of you two and share it.",
"Challenge your sister to a game and let her choose the punishment.",
"Offer your sister help with a chore without being asked.",
"Take a funny selfie with your sister wearing the same facial expression.",
"Ask your sister to share her favourite childhood game with the group.",
"Ask your sister what she would change about you and take it with a smile.",
"Tell your sister one thing you are proud of her for and share how she reacts.",
"Take a sister-and-me photo with the same pose as an old childhood pic.",
"Teach your sister a tongue twister and see who says it fastest.",
"Do an arm wrestle with your sister and share the result.",
"Send a thank-you message to your sister for something she did for you.",
"Write a funny short story about you and your sister as secret agents.",
"Ask your sister her dream job and tell us what it is.",
"Ask your sister to give you a motivational speech for 20 seconds.",
"Share your sister's most-used phrase and imitate how she says it.",
"Have a quick quiz with your sister about each other and tell the score.",
"Make your sister a card that says \"World's Okayest Sister\" and send a photo.",
"Lend something of yours to your sister for a day and tell us what.",
"Ask your sister to name your biggest weakness, then make a plan to fix it.",
"Give your sister a compliment about her style or her skills.",
"Share a childhood story that your sister hates being told.",
"Write a mini newspaper headline about your sister's most famous mishap.",
"Make your sister laugh with an impression of her and share how it went.",
"Share what you think your sister will be famous for.",
"Ask your sister to pick your next dare.",
"Challenge your sister to a 10-second plank and see who lasts longer.",
"Do a comedy skit with your sister for 30 seconds.",
"Create a secret code word with your sister and share it with the group.",
"Ask your sister to pick a movie for you to watch tonight.",
"Ask your sister for advice on something and follow it for a day.",
"Tell your sister three things you like about her in a voice note.",
"Name three things your sister is better at than you.",
"Mimic your sister's walk and let the group guess who it is.",
"Ask your sister to rate your outfit out of ten.",
"Let your sister make a meme about you and share it.",
"Make a \"Sisters Forever\" caption and use it on your status.",
"Let your sister do your hairstyle or choose your outfit and send a photo.",
"Swap an old childhood photo with your sister and share the story.",
"Compliment your sister's best quality in a voice note.",
"Ask your sister to tell you their favourite memory of the two of you and share what she says.",
"Ask your sister to share one thing they are scared of and share what she says.",
"Ask your sister to name your best quality and share what she says.",
"Ask your sister to describe you in a funny line and share what she says.",
"Ask your sister to guess your favourite song and share what she says.",
"Ask your sister to pick a movie you must watch tonight and share what she says.",
"Ask your sister to tell you a secret skill they have and share what she says.",
"Ask your sister to sing one line of any song and share what she says.",
"Ask your sister to choose a snack you must eat and share what she says.",
"Ask your sister to tell you what they love about home and share what she says.",
"Ask your sister to give you a challenge for one hour and share what she says.",
"Ask your sister to tell you their dream for the next year and share what she says.",
"Ask your sister to share a funny childhood story and share what she says.",
"Ask your sister to describe a day they would like to spend with you and share what she says.",
"Ask your sister to say one thing you do that makes them smile and share what she says.",
"Ask your sister to draw a doodle of you and share what she says.",
"Ask your sister to give you a nickname for the day and share what she says.",
"Ask your sister to pick your outfit tomorrow and share what she says.",
"Ask your sister to share what they want to learn this year and share what she says.",
"Ask your sister to teach you a trick in one minute and share what she says."
],
"irl": [
"Solve this and answer in the chat: what has keys but cannot open locks?",
"Count the number of windows in your house and share the answer.",
"Go outside and find something red. Send a photo.",
"Name 10 countries that start with the letter \"I\" or \"S\" in 30 seconds.",
"Type the alphabet in reverse order without mistakes in under 30 seconds.",
"Name five things in your room that are older than you.",
"Write a to-do list for a perfect Sunday and share it.",
"Tell us the shortest route from your home to the nearest chai shop.",
"Draw a map of your room from memory and send the photo.",
"Do 20 squats and tell us how you feel.",
"Eat something healthy right now and show us.",
"Drink a full glass of water and send a thumbs up.",
"Close your eyes for 30 seconds and tell us three sounds you heard.",
"Stand on one leg for 20 seconds and report how it went.",
"Find an item at home that starts with each letter in your name.",
"Tidy one small corner of your room and send a before and after photo.",
"Memorise a 6-digit number in 10 seconds and write it back.",
"Switch off all lights and the screen for 2 minutes and tell us what you thought of.",
"Name 5 animals starting with the same letter in 20 seconds.",
"Calculate 17 times 13 in your head without a calculator and tell us the time you took.",
"Say 3 facts about your city that most people do not know.",
"Teach the group a quick life hack you use every day.",
"Plan a 2-day trip to a nearby place with a budget of 2000 rupees and post the plan.",
"Describe how to make your favourite dish in exactly 5 steps.",
"Share three books, movies or shows you would recommend for a rainy day.",
"Write a one-line rule for the group chat and justify it.",
"Share your morning routine in 5 bullet points.",
"Make a paper aeroplane and send the photo of its first flight.",
"Make a funny but helpful poster for the group in 1 minute.",
"Name your top 3 life priorities and why.",
"Teach us a word from your mother tongue with the meaning.",
"Do a 1-minute stretching routine and describe it.",
"Take a photo from an unusual angle at your place and challenge us to guess what it is.",
"Make a small quiz of 3 questions for the group.",
"Walk around the house, find the most useless object, and make a speech about it.",
"Make a list of 5 free ways to have fun.",
"Write a \"life pro tip\" about money in one line.",
"Take a photo of your handwriting and write \"Hello from earth\".",
"Sort your phone's apps by colour and send a screenshot.",
"Memorise a phone number from the group in 20 seconds and say it back.",
"Describe a problem in your colony and one realistic fix.",
"Decide what to cook for dinner using only three ingredients you have and share it.",
"Explain how the internet works to a 5-year-old in 3 lines.",
"Fold a T-shirt in the quickest way you can and show us the result.",
"Pick a random page of a book near you and read the first line aloud.",
"Give three reasons why sleep is important in a funny way.",
"Write the names of five teachers you remember and one memory for each.",
"List 5 things you would buy with 500 rupees.",
"Create a new rule for cricket and explain it.",
"Find a coin and flip it five times. Share the sequence.",
"Find a word that rhymes with \"orange\" or say you cannot and explain why.",
"Describe your dream house in 3 sentences.",
"Draw a quick doodle of your favourite food and send it.",
"Switch your phone to grayscale for 10 minutes and tell us what changed.",
"List 5 jobs that did not exist 20 years ago.",
"Take a walk for 5 minutes and send a photo of the best thing you saw.",
"Do a quick riddle: what gets wetter as it dries? Answer in the chat.",
"Say the days of the week in reverse order in one breath.",
"Send a screenshot of your screen time today and tell us what surprised you.",
"Set a 5-minute timer and declutter your bag. Send a photo of what you removed.",
"Find three objects at home that make a rhyming set and send a photo.",
"Think of a startup idea for your neighbourhood and pitch it in 3 lines.",
"Solve this: if 5 machines make 5 items in 5 minutes, how long do 100 machines take for 100 items?",
"Count how many steps it takes from your bed to the main door and tell us.",
"Share a \"would you rather\" question for the group to answer.",
"Do a quick budget plan for next month and share one saving tip.",
"Send a photo of the most colourful thing near you.",
"Send a photo of your favourite mug.",
"Send a photo of the sky outside your window.",
"Send a photo of something that starts with the letter S.",
"Send a photo of your shoes lined up.",
"Send a photo of the view from your balcony or window.",
"Send a photo of something shiny near you.",
"Send a photo of your desk or study table.",
"Send a photo of the oldest thing in your house.",
"Send a photo of your favourite book or magazine.",
"Send a photo of the item that is closest to your left hand.",
"Send a photo of your lunch plate.",
"Send a photo of your phone wallpaper.",
"Send a photo of something that makes you feel calm.",
"Send a photo of your charger and cables mess.",
"Send a photo of a plant or a tree near you.",
"Send a photo of your breakfast table.",
"Send a photo of an object that reminds you of childhood.",
"Send a photo of your pillow or bed.",
"Send a photo of the funniest-looking thing at your home.",
"Send a photo of your slippers.",
"Send a photo of something blue.",
"Send a photo of something round.",
"Send a photo of a pair of things.",
"Send a photo of your bag or backpack.",
"Send a photo of your keys.",
"Send a photo of a clock showing the current time.",
"Send a photo of the tallest thing you can see.",
"Send a photo of your hand with a funny drawing on it.",
"Send a photo of your reflection in an unusual surface.",
"Send a photo of your favourite spot at home.",
"Send a photo of the sunlight on your wall.",
"Send a photo of a creative shadow.",
"Send a photo of your pet or a neighbour's pet.",
"Send a photo of something you made.",
"Send a photo of your tea or coffee.",
"Send a photo of a snack you love.",
"Send a photo of your bookshelf.",
"Send a photo of something older than 10 years.",
"Send a photo of something from a trip you took.",
"Describe your ideal Sunday in exactly 3 sentences.",
"Describe your biggest wish in one breath.",
"Describe your best friend like a movie trailer.",
"Describe the smell of fresh food in exactly 10 words.",
"Describe the colour blue in exactly 3 sentences.",
"Describe a day without a phone in exactly 3 sentences.",
"Describe your school days without using the letter E.",
"Describe your favourite food as a poem of 4 lines.",
"Describe the smell of fresh food as a poem of 4 lines.",
"Describe the colour blue like a movie trailer.",
"Describe the internet to your grandparents as a poem of 4 lines.",
"Describe your school days using only emojis.",
"Describe your biggest wish using only emojis.",
"Describe a crowded bus as a poem of 4 lines.",
"Describe your last dream in exactly 10 words.",
"Describe the last movie you watched in a rhyming couplet.",
"Describe your ideal Sunday in exactly 10 words.",
"Describe your best friend like a weather report.",
"Describe the last movie you watched like a weather report.",
"Describe a day without a phone in one breath.",
"Describe your favourite teacher as a poem of 4 lines.",
"Describe your school days like a bedtime story.",
"Describe your day so far in a rhyming couplet.",
"Describe your bed in one breath.",
"Describe your hometown like a weather report.",
"Describe your favourite food in exactly 3 sentences.",
"Describe a rainy day like a bedtime story.",
"Describe the internet to your grandparents using only emojis.",
"Describe your day so far as a poem of 4 lines.",
"Describe your best friend without using the letter E.",
"Describe the group chat like a movie trailer.",
"Describe a power cut like a movie trailer.",
"Describe your morning routine without using the letter E.",
"Describe a wedding function in exactly 10 words.",
"Describe the colour blue using only emojis.",
"Describe your ideal Sunday like a movie trailer.",
"Describe the internet to your grandparents in a rhyming couplet.",
"Describe your morning routine like a weather report.",
"Describe your ideal Sunday as a poem of 4 lines.",
"Describe the sound of rain in a rhyming couplet.",
"Describe your dream holiday in exactly 3 sentences.",
"Describe your favourite teacher using only emojis.",
"Describe a crowded bus in one breath.",
"Describe your ideal Sunday like a bedtime story.",
"Describe your last dream like a bedtime story.",
"Do 20 arm circles and tell us how you feel.",
"Do 25 push-ups and tell us how you feel.",
"Do 20 high knees and tell us how you feel.",
"Do 10 burpees and tell us how you feel.",
"Do 15 skips and tell us how you feel.",
"Do 15 squats and tell us how you feel.",
"Do 10 squats and tell us how you feel.",
"Do 10 toe touches and tell us how you feel.",
"Do 10 lunges and tell us how you feel.",
"Do 10 push-ups and tell us how you feel.",
"Do 15 sit-ups and tell us how you feel.",
"Do 15 lunges and tell us how you feel.",
"Do 25 high knees and tell us how you feel.",
"Do 30 skips and tell us how you feel.",
"Do 30 sit-ups and tell us how you feel.",
"Do 10 arm circles and tell us how you feel.",
"Do 10 sit-ups and tell us how you feel.",
"Do 15 high knees and tell us how you feel.",
"Do 30 lunges and tell us how you feel.",
"Do 25 lunges and tell us how you feel.",
"Do 20 sit-ups and tell us how you feel.",
"Do 30 toe touches and tell us how you feel.",
"Do 20 push-ups and tell us how you feel.",
"Do 25 jumping jacks and tell us how you feel.",
"Name 7 birds in 20 seconds in a voice note.",
"Name 7 fruits in 30 seconds in a voice note.",
"Name 5 Indian cities in 30 seconds in a voice note.",
"Name 7 cricketers in 30 seconds in a voice note.",
"Name 8 Bollywood movies in 40 seconds in a voice note.",
"Name 7 colours in 20 seconds in a voice note.",
"Name 10 vegetables in 30 seconds in a voice note.",
"Name 10 desserts in 40 seconds in a voice note.",
"Name 7 capital cities in 30 seconds in a voice note.",
"Name 8 languages in 30 seconds in a voice note.",
"Name 5 rivers in 30 seconds in a voice note.",
"Name 8 famous scientists in 40 seconds in a voice note.",
"Name 8 cartoon characters in 20 seconds in a voice note.",
"Name 7 mobile apps in 20 seconds in a voice note.",
"Name 8 school subjects in 20 seconds in a voice note.",
"Name 10 musical instruments in 30 seconds in a voice note.",
"Name 10 flowers in 30 seconds in a voice note.",
"Name 8 spices in 20 seconds in a voice note.",
"Name 7 sports in 20 seconds in a voice note.",
"Name 10 mountains in 40 seconds in a voice note."
]
};
