// Generated prompt bank. Family-friendly. Do not edit by hand.
export default {
"funny": [
"What is the most embarrassing thing you have done in public?",
"What is the silliest thing you have ever cried about?",
"What is the weirdest food combination you secretly enjoy?",
"Which cartoon character do you still have a soft spot for?",
"What is the funniest nickname anyone has given you?",
"Have you ever walked into a glass door or wall? Tell the story.",
"What is the worst haircut you have ever had?",
"What is the strangest thing you have ever Googled?",
"Which song do you sing loudest when nobody is home?",
"What is the most embarrassing thing in your phone gallery (without showing it)?",
"Have you ever waved back at someone who was not waving at you?",
"What is the dumbest lie you told as a kid that people actually believed?",
"What is the funniest autocorrect fail you have sent?",
"If you were a vegetable, which one would you be and why?",
"What is the most ridiculous excuse you gave to skip school or work?",
"Have you ever laughed at the wrong time, like at a serious moment? What happened?",
"What is the weirdest dream you can remember?",
"Which animal do you think you act like the most?",
"What is the strangest talent you have?",
"What is your most embarrassing moment on a video call?",
"What was the funniest thing you did while half asleep?",
"Have you ever sent a message to the wrong person? What did it say?",
"What is the silliest fear you still have?",
"Which social media post of yours makes you cringe today?",
"What is the most random thing you have ever bought online?",
"Have you ever pretended to be on a phone call to avoid someone?",
"What is the funniest thing your parents ever caught you doing?",
"What is the worst dance move you have ever done in public?",
"What is the silliest argument you have had with a friend?",
"If your pet could talk, what embarrassing secret would it tell about you?",
"What is the strangest thing you have eaten on a dare?",
"Which word do you always pronounce wrong?",
"What is the most childish thing you still do?",
"Have you ever fallen asleep somewhere very awkward? Where?",
"What is the weirdest rule you follow in daily life?",
"What is the funniest thing you have said while sleep talking, as told by others?",
"What is the cringiest outfit you have ever worn?",
"Have you ever talked to yourself in the mirror? What did you say?",
"What is the most embarrassing ringtone you have ever had?",
"Which Bollywood dialogue do you use way too often?",
"What is the funniest thing you have done to avoid doing homework?",
"What is the worst gift you have ever given someone?",
"What is the silliest thing you have ever been scolded for?",
"Have you ever eaten something that fell on the floor? What was it?",
"What is the funniest name you have ever heard and still remember?",
"What is the most embarrassing thing you have said in front of your crush's friends?",
"What is the worst pickup line you know?",
"Have you ever tried to cook something and failed badly? What was it?",
"What is the weirdest place you have ever dozed off?",
"What is the funniest misunderstanding you have been part of?",
"Which emoji do you overuse the most, and why?",
"What is the strangest superstition you believe in?",
"What would your villain origin story be?",
"What is the most dramatic thing you have done over something tiny?",
"If your life was a sitcom, what would the title be?",
"What is the worst advice you have ever followed?",
"What is the most useless thing you have memorized?",
"What is the funniest thing you have said to a teacher?",
"Have you ever been caught singing in the bathroom? By whom?",
"What is the weirdest compliment you have ever received?",
"What is the funniest thing in your search history from this week?",
"What is the most ridiculous thing you have bargained for?",
"What snack would you fight someone for?",
"Which relative would be the funniest to take on a trip, and why?",
"What is the silliest thing you have said to impress someone?",
"Have you ever forgotten the name of someone right after meeting them?",
"What is the silliest reason you have ever been late?",
"What would you do if you woke up invisible for one day?",
"What is the funniest thing you have seen a stranger do?",
"Have you ever laughed so hard you cried in class or at a function?",
"What is the funniest school memory you have?",
"What is the worst selfie you have ever posted?",
"What cheesy line from a movie do you secretly love?",
"Have you ever tripped on stage or in front of a crowd?",
"Which of your friends is the worst driver, and why?",
"What is the funniest way you have ever been woken up?",
"Who in this group would survive the longest in a zombie apocalypse, and who would be first to go?",
"What is the funniest thing you have done to get out of trouble?",
"What would your reality TV show be called?",
"What is the silliest thing that makes you instantly angry?",
"What is the strangest thing in your bag or pocket right now?",
"Who in this group is most likely to forget their own birthday?",
"Who in this group is most likely to laugh at their own joke?",
"Who in this group is most likely to get lost with a map in hand?",
"Who in this group is most likely to fall asleep during a movie?",
"Who in this group is most likely to cry at a sad ad?",
"Who in this group is most likely to text back after 3 days?",
"Who in this group is most likely to become a millionaire?",
"Who in this group is most likely to become famous on the internet?",
"Who in this group is most likely to talk to a stranger for an hour?",
"Who in this group is most likely to win a dance contest?",
"Who in this group is most likely to sing in the shower loudly?",
"Who in this group is most likely to run away from a lizard?",
"Who in this group is most likely to burn water while cooking?",
"Who in this group is most likely to cry during a farewell?",
"Who in this group is most likely to forget where they kept their phone while holding it?",
"Who in this group is most likely to laugh in the middle of a serious meeting?",
"Who in this group is most likely to eat the last slice of pizza?",
"Who in this group is most likely to sleep through an alarm?",
"Who in this group is most likely to argue with a shopkeeper?",
"Who in this group is most likely to buy something they do not need?",
"Who in this group is most likely to become a teacher?",
"Who in this group is most likely to become a chef?",
"Who in this group is most likely to travel the world alone?",
"Who in this group is most likely to get a tattoo?",
"Who in this group is most likely to sing at a wedding uninvited?",
"Who in this group is most likely to win a quiz show?",
"Who in this group is most likely to get stuck in a lift?",
"Who in this group is most likely to forget to charge their phone?",
"Who in this group is most likely to snore the loudest?",
"Who in this group is most likely to tell the same story three times?",
"Who in this group is most likely to miss their train or bus?",
"Who in this group is most likely to shop for 5 hours without buying anything?",
"Who in this group is most likely to laugh at the wrong time?",
"Who in this group is most likely to make friends with a street dog?",
"Who in this group is most likely to plan a trip but never go?",
"Who in this group is most likely to become a movie star?",
"Who in this group is most likely to walk into a glass door?",
"Who in this group is most likely to talk in their sleep?",
"Who in this group is most likely to take 100 photos of the same thing?",
"Who in this group is most likely to give the best advice?",
"Who in this group is most likely to keep a secret forever?",
"Who in this group is most likely to lose their keys daily?",
"Who in this group is most likely to start a business?",
"Who in this group is most likely to get a pet snake?",
"Who in this group is most likely to wake up the earliest?",
"Who in this group is most likely to stay up the latest?",
"Who in this group is most likely to dance at a stranger's baraat?",
"Who in this group is most likely to drop their phone on their face?",
"Who in this group is most likely to cry while watching a cricket match?",
"Who in this group is most likely to be a motivational speaker?",
"Who in this group is most likely to be late to their own party?",
"Who in this group is most likely to get carried away in an argument?",
"Who in this group is most likely to eat the spiciest food without water?",
"Who in this group is most likely to forget a friend's birthday?",
"Who in this group is most likely to hide in a corner at a party?",
"Who in this group is most likely to become a YouTuber?",
"Who in this group is most likely to panic at a spider?",
"Who in this group is most likely to make everyone laugh at a funeral meeting by accident?",
"Who in this group is most likely to take selfies at every place?",
"Who in this group is most likely to cheat at a board game?",
"Who in this group is most likely to call their mother daily?",
"Who in this group is most likely to overthink a text?",
"Who in this group is most likely to rehearse a conversation before a call?",
"Who in this group is most likely to get a perfect score?",
"Who in this group is most likely to laugh so much that they cannot speak?",
"Who in this group is most likely to make the best chai?",
"Who in this group is most likely to be the group's therapist?",
"Who in this group is most likely to go viral for something silly?",
"Who in this group is most likely to forget their umbrella on a rainy day?",
"Who in this group is most likely to try a new food every day?",
"Who in this group is most likely to argue about cricket?",
"Who in this group is most likely to pick up a stray kitten?",
"Who in this group is most likely to reach a party first?",
"Who in this group is most likely to become the group's DJ?",
"Who in this group is most likely to adopt five pets?",
"Who in this group is most likely to laugh at old photos?",
"Who in this group is most likely to get into a harmless prank war?",
"Who in this group is most likely to build a gadget at home?",
"Who in this group is most likely to learn five languages?",
"Who in this group is most likely to bring snacks to every hangout?",
"Who in this group is most likely to keep a diary?",
"Who in this group is most likely to talk to their plants?",
"Who in this group is most likely to take the longest to reply?",
"Who in this group is most likely to post the most stories?",
"Who in this group is most likely to move to another country?",
"Who in this group is most likely to fall asleep on a bus?",
"Who in this group is most likely to ask for the bill first?",
"Who in this group is most likely to stay in touch with school friends?",
"Who in this group is most likely to pull an all-nighter?",
"Rate your cooking skills out of 10 and explain your score.",
"Rate your dancing skills out of 10 and explain your score.",
"Rate your singing skills out of 10 and explain your score.",
"Rate your drawing skills out of 10 and explain your score.",
"Rate your sense of humour out of 10 and explain your score.",
"Rate your sleep schedule out of 10 and explain your score.",
"Rate your phone addiction out of 10 and explain your score.",
"Rate your fashion sense out of 10 and explain your score.",
"Rate your driving or riding skills out of 10 and explain your score.",
"Rate your gaming skills out of 10 and explain your score.",
"Rate your cricket skills out of 10 and explain your score.",
"Rate your memory out of 10 and explain your score.",
"Rate your punctuality out of 10 and explain your score.",
"Rate your luck out of 10 and explain your score.",
"Rate your patience out of 10 and explain your score.",
"Rate your selfie game out of 10 and explain your score.",
"Rate your knowledge of Bollywood out of 10 and explain your score.",
"Rate your ability to keep secrets out of 10 and explain your score.",
"Rate your ability to give advice out of 10 and explain your score.",
"Rate your mood in the morning out of 10 and explain your score.",
"Rate your handwriting out of 10 and explain your score.",
"Rate your lying skills out of 10 and explain your score.",
"Rate your daily laziness out of 10 and explain your score.",
"Rate your bargaining skills out of 10 and explain your score.",
"Rate your confidence on stage out of 10 and explain your score.",
"Rate your last exam performance out of 10 and explain your score.",
"Rate your mother's cooking out of 10 and explain your score.",
"Rate your Wi-Fi speed today out of 10 and explain your score.",
"Rate your WhatsApp status taste out of 10 and explain your score.",
"Rate your general knowledge out of 10 and explain your score.",
"Rate your last holiday out of 10 and explain your score.",
"Rate your last birthday out of 10 and explain your score.",
"Rate your haircut out of 10 and explain your score.",
"Rate your taste in music out of 10 and explain your score.",
"Rate your swimming skills out of 10 and explain your score.",
"Rate your math skills out of 10 and explain your score.",
"Rate your English skills out of 10 and explain your score.",
"Rate your talent for making friends out of 10 and explain your score.",
"Rate your talent for making jokes out of 10 and explain your score.",
"Rate your overall vibe today out of 10 and explain your score.",
"Have you ever pretended to be sick to skip a day? Tell us the story.",
"Have you ever eaten a whole pizza alone? Tell us the story.",
"Have you ever cried at a movie that was not even sad? Tell us the story.",
"Have you ever danced in the rain? Tell us the story.",
"Have you ever talked to a stranger on a train and became friends? Tell us the story.",
"Have you ever forgotten your own phone number? Tell us the story.",
"Have you ever sent a text and then wished you had not? Tell us the story.",
"Have you ever slept through an important event? Tell us the story.",
"Have you ever laughed out loud in a library or class? Tell us the story.",
"Have you ever lied about your age? Tell us the story.",
"Have you ever stayed up all night to finish a series? Tell us the story.",
"Have you ever taken a photo and deleted it because you looked bad? Tell us the story.",
"Have you ever got a nickname you hated? Tell us the story.",
"Have you ever waved at a person you thought you knew? Tell us the story.",
"Have you ever tried to fix something and broke it more? Tell us the story.",
"Have you ever worn the same clothes two days in a row? Tell us the story.",
"Have you ever eaten something and pretended to like it? Tell us the story.",
"Have you ever joined a group chat by mistake? Tell us the story.",
"Have you ever used the wrong name at a meeting? Tell us the story.",
"Have you ever wanted to restart your life? Tell us the story.",
"Have you ever rewatched the same movie ten times? Tell us the story.",
"Have you ever made a wish at 11:11? Tell us the story.",
"Have you ever cried on a birthday? Tell us the story.",
"Have you ever walked into the wrong washroom? Tell us the story.",
"Have you ever hidden from a guest at home? Tell us the story.",
"Have you ever missed your bus because you overslept? Tell us the story.",
"Have you ever given a gift you did not like to someone else? Tell us the story.",
"Have you ever read a message and forgot to reply for days? Tell us the story.",
"Have you ever returned a gift? Tell us the story.",
"Have you ever stood up for a friend in a fight? Tell us the story.",
"Have you ever memorised an entire song from a movie in one day? Tell us the story.",
"Have you ever told a fib to get out of a plan? Tell us the story.",
"Have you ever fallen on stage? Tell us the story.",
"Have you ever kept a pet that you were not supposed to? Tell us the story.",
"Have you ever learned an instrument and quit? Tell us the story.",
"Have you ever gone on a trip without telling your parents everything? Tell us the story.",
"Have you ever stalked your own old photos? Tell us the story.",
"Have you ever been scared of the dark as a teenager? Tell us the story.",
"Have you ever talked to your phone's assistant for fun? Tell us the story.",
"Have you ever googled your own name? Tell us the story.",
"Have you ever been caught napping in class? Tell us the story.",
"Have you ever asked an awkward question in public? Tell us the story.",
"Have you ever laughed at your own typo? Tell us the story.",
"Have you ever borrowed a pen and never returned it? Tell us the story.",
"Have you ever used a fake name online? Tell us the story.",
"Have you ever kept an old SMS you could not delete? Tell us the story.",
"Have you ever helped a stranger and never told anyone? Tell us the story.",
"Have you ever tried to impress someone with a lie? Tell us the story.",
"Have you ever forgotten an exam date? Tell us the story.",
"Have you ever ate a full meal without any plate? Tell us the story.",
"Have you ever had a crush on a cartoon character? Tell us the story.",
"Have you ever accidentally called a teacher \"mom\" or \"dad\"? Tell us the story.",
"Have you ever worn your shirt inside out the whole day? Tell us the story.",
"Have you ever cried because of a cartoon? Tell us the story.",
"Have you ever sung loudly at a wedding? Tell us the story.",
"Have you ever stayed awake all night before exam day? Tell us the story.",
"Have you ever been on a long road trip with friends? Tell us the story.",
"Have you ever slept in a train station? Tell us the story.",
"Have you ever forgotten the lyrics to your favourite song? Tell us the story.",
"Have you ever used a joke you read online as your own? Tell us the story.",
"Have you ever saved a number as a funny name? Tell us the story.",
"Have you ever gotten lost in your own city? Tell us the story.",
"Have you ever joined a gym and never went? Tell us the story.",
"Have you ever tried to cut your own hair? Tell us the story.",
"Have you ever worn mismatched socks all day? Tell us the story.",
"Have you ever had a pet fish die? Tell us the story.",
"Have you ever been stuck in a lift? Tell us the story.",
"Have you ever cried in public? Tell us the story.",
"Have you ever given someone the wrong directions on purpose? Tell us the story.",
"Have you ever talked to a wall like a person? Tell us the story.",
"Have you ever sung a song to a pet? Tell us the story.",
"Have you ever made a promise to yourself and broken it? Tell us the story.",
"Have you ever read someone's message over their shoulder? Tell us the story.",
"Have you ever been on TV or radio? Tell us the story.",
"Have you ever written a diary? Tell us the story.",
"Have you ever mailed a letter? Tell us the story.",
"Have you ever received a handwritten letter? Tell us the story.",
"Have you ever kept a dried flower in a book? Tell us the story.",
"Have you ever talked to a celebrity? Tell us the story.",
"Have you ever climbed a hill or a mountain? Tell us the story.",
"Have you ever got a call from an unknown number and answered it in a funny voice? Tell us the story.",
"Have you ever fallen asleep while talking on the phone? Tell us the story.",
"Have you ever been the last one left at a party? Tell us the story.",
"Have you ever wanted to quit a job or school and did not? Tell us the story."
],
"sad": [
"What is one memory from childhood that makes you emotional when you think about it?",
"Who is a person you miss the most right now?",
"What is something you wish you had said to someone but never did?",
"What is the saddest movie or show scene that made you cry?",
"What is a goodbye you still think about?",
"When was the last time you cried, and what was it about?",
"What is a friendship you lost that you wish you could fix?",
"What is something you regret not doing when you had the chance?",
"What is a song that always makes you feel sad?",
"Have you ever felt left out in a group? What happened?",
"What is the loneliest you have ever felt?",
"What is one thing you wish people understood about you?",
"Who do you wish you could talk to one more time?",
"What is a promise you made and could not keep?",
"What is a place you used to love that you cannot visit anymore?",
"Which birthday or festival was the most disappointing for you?",
"What is something you are still sad about that others think is small?",
"What is the hardest thing you have ever had to let go of?",
"Have you ever pretended to be okay when you were not? When?",
"What is a mistake you wish you could undo?",
"Who in your life do you feel you have not thanked enough?",
"What was the hardest day of school for you?",
"What is something from the past that you miss so much?",
"What is an old photo that makes you feel nostalgic?",
"Have you ever felt like nobody noticed your effort? When?",
"What is the most painful thing someone has said to you?",
"What is one fear about the future that keeps you awake?",
"Which old friend would you most like to meet again?",
"What did you want to be as a child, and what happened to that dream?",
"What is a moment you felt really proud but nobody was there to see it?",
"When did you last feel truly homesick?",
"What is a lesson you learned the hard way?",
"Who is someone you forgave, and was it hard?",
"What is something you are afraid to lose?",
"What is the kindest thing someone did for you when you were down?",
"What is a childhood toy or object you wish you still had?",
"What is the saddest thing you have seen in real life?",
"Have you ever wanted to give up on something? What was it?",
"What is a regret you have about how you treated someone?",
"What is the most emotional message you have ever received?",
"Who do you think misunderstands you the most?",
"What is something you miss about being a kid?",
"What is a time you felt invisible?",
"Which relationship changed the most as you grew up?",
"Have you ever missed an important event because of something out of your control?",
"What is the biggest disappointment you have faced this year?",
"What is a dream you gave up on, and do you still think about it?",
"Have you ever lost something that mattered to you a lot? What was it?",
"What is the hardest apology you have ever had to make?",
"What makes you feel the most alone in a crowd?",
"What is a memory with a grandparent that you treasure?",
"What is a time you felt you let your family down?",
"Which phase of your life do you wish you could revisit?",
"What is a secret you carried alone for too long?",
"When did you last feel really thankful but sad at the same time?",
"What do you do when you feel low, and does it help?",
"What is the best advice someone gave you during a hard time?",
"Who has been your biggest support, and have you told them so?",
"What is something you are still healing from?",
"What is the one thing you would change about your past if you could?",
"What is a goodbye message you would write to your school days?",
"What scares you most about growing older?",
"Have you ever wished someone would simply ask if you are okay?",
"What is an old habit you wish you could break?",
"What is one thing that always cheers you up after a bad day?",
"What is the most meaningful thing someone has ever given you?",
"What is something you hope to say to your future self?",
"What moment in life made you realise you had grown up?",
"What is a person you outgrew, and how did you feel about it?",
"What is a small thing from your past that you cannot forget?",
"Which festival feels different now compared to your childhood, and why?",
"What is a letter you would like to write to someone but never send?",
"What do you wish you could hear from someone right now?"
],
"romantic": [
"What is your idea of a perfect date?",
"What is the most romantic thing you have ever done for someone?",
"What quality in a person makes your heart skip a beat?",
"Have you ever written a love letter or a long message to a crush?",
"What is the most romantic movie you have seen?",
"What would your dream proposal look like?",
"What is your favourite love song?",
"What was your first impression of the last person you liked?",
"Have you ever had a crush on a teacher or a senior? Who and why?",
"What is the cutest thing someone has done for you?",
"What is a romantic place you would love to visit?",
"Do you believe in love at first sight? Have you experienced it?",
"What is the first thing you notice about someone you like?",
"Have you ever liked someone in this group? You can answer with a hint.",
"What is your favourite romantic dialogue?",
"Would you rather have a candlelight dinner or a long drive at midnight?",
"What is the sweetest compliment you have received?",
"What is the most thoughtful gift you have ever received?",
"What does your ideal partner do for a living?",
"What would you cook for a romantic dinner?",
"Have you ever stayed up all night talking to someone you liked?",
"What is the longest time you have waited for a reply from a crush?",
"What is one habit of yours that your partner would find cute?",
"What is your idea of a perfect wedding?",
"What is the best love story you have heard from your family?",
"Have you ever been confessed to? How did you react?",
"What is the cheesiest thing you would do to impress someone?",
"What colour outfit do you find most attractive on someone?",
"What is the first thing you would do on a surprise date night?",
"Which actor or actress is your ultimate crush?",
"What does a perfect good morning message look like to you?",
"Have you ever gotten butterflies from a text message?",
"What is the most romantic thing about rainy weather for you?",
"Which couple in movies or shows would you like to be?",
"Would you be okay with a long-distance relationship? Why?",
"What is a love language that suits you best: words, time, gifts, touch, or acts?",
"What is the sweetest nickname someone has called you?",
"What is your ideal first message from a crush?",
"What is something small that makes a day feel romantic to you?",
"What is the most romantic song you would dedicate to someone?",
"Have you ever planned a surprise for someone you liked?",
"What is the best date you have ever been on?",
"What would you do if your crush suddenly called you right now?",
"Do you prefer a planned surprise or a spontaneous one?",
"What is a romantic gesture you think is overrated?",
"How do you act when you like someone, shy or bold?",
"What is your favourite way to spend a quiet evening with someone special?",
"What is one thing you would never compromise on in a relationship?",
"What is the most romantic city in the world in your opinion?",
"What does home feel like with the right person?",
"What is the cutest thing you have seen a couple do?",
"How would you ask someone out in the most filmy way?",
"What is your dream honeymoon destination?",
"What song would play in the background of your love story?",
"Have you ever gone out of your way to bump into someone you liked?",
"What is the best way to say sorry to someone you love?",
"What is the most romantic thing a friend has done for you?",
"What is the best compliment you could give to someone you like?",
"What is a quality you look for first: looks, humour, kindness, or confidence?",
"Which season is the most romantic for you, and why?",
"What would your love story be titled?",
"Have you ever fallen for a friend? What happened?",
"What is the best surprise you have ever planned or received?",
"What is the cutest text you have ever sent?",
"What would your perfect anniversary look like?"
],
"love": [
"What does love mean to you in one sentence?",
"Who was your first love, in a sweet and clean way?",
"What is the most important thing to you in a relationship?",
"What is the best advice about love you have ever received?",
"Do you believe in soulmates?",
"What is the biggest sacrifice you would make for someone you love?",
"Who is the person you love the most in your life?",
"When did you last tell someone you love them?",
"What is something you love about each person in this group?",
"What do you love most about yourself?",
"What is the kindest act of love you have seen?",
"How do you show love to your friends?",
"How do you show love to your family?",
"Do you think friends can be a form of love? Why?",
"Which person's love have you taken for granted?",
"What is the first thing you would do to make someone you love feel special?",
"What is your definition of true love?",
"Which movie got love right in your opinion?",
"What does a good relationship feel like?",
"What is more important in love: trust or honesty?",
"Have you ever loved something so much it surprised you, like a place, a hobby, or a pet?",
"What is the most loving message you ever received from a parent?",
"What is a love story from your family that inspires you?",
"What small thing do you do every day that shows love?",
"Who taught you what love is?",
"Do you believe in second chances in love?",
"What is the best thing about being loved?",
"What makes you feel loved the most?",
"Who in this group do you think is the most caring?",
"Have you ever been in love with a place or a city?",
"What is the sweetest note or card you have ever received?",
"What do you love about rainy days?",
"What would you tell someone who has never felt loved?",
"What is the difference between love and liking someone?",
"What do you think makes love last for decades?",
"Who is the person that always makes you feel safe?",
"What is one thing you love doing with your best friend?",
"What is a love you have for something unusual, like a food or a game?",
"Which person would you cross the city for in the middle of the night?",
"Which words from someone mean the most to you?",
"What love advice would you give your younger self?",
"Is it better to love or be loved? Why?",
"What would you do to cheer up someone you love?",
"Which celebrity couple do you think is a real inspiration?",
"What do you love about your hometown?",
"Whose love story would you like to hear in full?",
"What gift says \"I love you\" best without costing much?",
"What do you love about your parents?",
"What is something you love that people may find strange?",
"How do you handle it when someone you love is angry with you?",
"Have you ever loved someone who did not love you back, in any form?",
"What is the nicest way someone has shown they care about you?",
"What does a love letter from you to your best friend say?",
"What is the most precious thing love has taught you?",
"How would you describe your love for food?",
"What are three things you love about this group?",
"What is the best love advice you would give to a friend right now?",
"Which relationship in your life has taught you the most?",
"How do you feel when someone remembers a small detail about you?",
"When did you realise you truly cared about someone?",
"What would you do if you had to prove your love to your best friend?",
"What is the most loving thing you have done for a stranger?",
"How do you say \"I love you\" without saying it?",
"What is the longest friendship you have, and what keeps it strong?",
"What is your favourite memory of feeling deeply loved?",
"When was the last time you cried? What was happening?",
"When was the last time you laughed until your stomach hurt? What was happening?",
"When was the last time you ate something that was too spicy? What was happening?",
"When was the last time you lied to your parents? What was happening?",
"When was the last time you ran as fast as you could? What was happening?",
"When was the last time you made someone smile? What was happening?",
"When was the last time you danced for no reason? What was happening?",
"When was the last time you fought with a friend? What was happening?",
"When was the last time you told someone you loved them? What was happening?",
"When was the last time you made a new friend? What was happening?",
"When was the last time you felt really proud of yourself? What was happening?",
"When was the last time you got scolded? What was happening?",
"When was the last time you felt homesick? What was happening?",
"When was the last time you had a long chat at midnight? What was happening?",
"When was the last time you did something kind for someone? What was happening?",
"When was the last time you tried a new food? What was happening?",
"When was the last time you got really embarrassed? What was happening?",
"When was the last time you sang in front of someone? What was happening?",
"When was the last time you read a full book? What was happening?",
"When was the last time you forgave someone? What was happening?",
"When was the last time you got a surprise? What was happening?",
"When was the last time you stayed up all night? What was happening?",
"When was the last time you spent the whole day outdoors? What was happening?",
"When was the last time you said sorry? What was happening?",
"When was the last time you felt nervous? What was happening?",
"When was the last time you helped a stranger? What was happening?",
"When was the last time you called an old friend? What was happening?",
"When was the last time you got goosebumps from a song? What was happening?",
"When was the last time you woke up feeling totally happy? What was happening?",
"When was the last time you watched the sunrise? What was happening?",
"When was the last time you walked barefoot? What was happening?",
"When was the last time you cooked a full meal? What was happening?",
"When was the last time you took a long bath? What was happening?",
"When was the last time you felt jealous? What was happening?",
"When was the last time you got a compliment from a stranger? What was happening?",
"When was the last time you thanked a teacher? What was happening?",
"When was the last time you lost something important? What was happening?",
"When was the last time you felt really lucky? What was happening?",
"When was the last time you laughed at yourself? What was happening?",
"When was the last time you played a childhood game? What was happening?",
"What is your favourite memory from school?",
"What is your favourite festival and why?",
"What is your favourite childhood game?",
"What is your favourite song to sing in the shower?",
"What is your favourite food to eat when you are sad?",
"What is your favourite place in the world?",
"What is your favourite time of day?",
"What is your favourite colour and what it says about you?",
"What is your favourite movie of all time?",
"What is your favourite cartoon from your childhood?",
"What is your favourite snack for a movie night?",
"What is your favourite teacher and why?",
"What is your favourite way to spend a rainy day?",
"What is your favourite dance move?",
"What is your favourite dialogue from a film?",
"What is your favourite chai or coffee order?",
"What is your favourite smell from your childhood?",
"What is your favourite photo of yourself?",
"What is your favourite day of the week?",
"What is your favourite sport to watch?",
"What is your favourite subject in school?",
"What is your favourite family recipe?",
"What is your favourite app on your phone?",
"What is your favourite gift you have ever received?",
"What is your favourite street food?",
"What is your favourite joke you remember?",
"What is your favourite season and what you do in it?",
"What is your favourite character from a TV show?",
"What is your favourite vacation memory?",
"What is your favourite piece of clothing?",
"What is your favourite thing about your best friend?",
"What is your favourite thing about your family?",
"What is your favourite sound in nature?",
"What is your favourite way to relax?",
"What is your favourite thing to do on weekends?",
"What is your favourite thing about this group?",
"What is your favourite old song from the 90s?",
"What is your favourite moment from the last year?",
"What is your favourite compliment you remember?",
"What is your favourite bedtime story from your childhood?"
],
"brother": [
"What is your funniest memory with your brother?",
"What is the one thing your brother does that annoys you the most?",
"What is the best thing your brother has ever done for you?",
"Have you ever gotten your brother in trouble on purpose?",
"What is a secret you kept for your brother?",
"What is something you borrowed from your brother and never returned?",
"What is the biggest fight you ever had with your brother, and how did it end?",
"What is one thing you admire about your brother?",
"If your brother had a superhero name, what would it be?",
"What is your brother's most embarrassing moment that you witnessed?",
"What did you and your brother fight over most as kids?",
"What is the nicest thing your brother has said to you?",
"Have you ever blamed your brother for something you did?",
"What is a game you and your brother played for hours?",
"Which of your brother's habits do you secretly copy?",
"What is the funniest nickname you have for your brother?",
"What is the one thing you would never forgive your brother for?",
"What would you do if your brother needed help at 3 AM?",
"Who is the favourite child in your house, you or your brother, and why?",
"What did your brother teach you that no one else did?",
"What is the best prank you pulled on your brother?",
"What is the best prank your brother pulled on you?",
"Have you ever eaten your brother's food and denied it?",
"What is one thing you wish you could tell your brother but find awkward?",
"Would you trade places with your brother for a day? Why?",
"What is your brother's weirdest talent?",
"What song reminds you of your brother?",
"What is the most selfless thing your brother has done?",
"If you and your brother started a business, what would it be?",
"What is your brother's favourite food, and have you stolen it?",
"Which cartoon or movie did you watch the most with your brother?",
"What is the one rule you and your brother always broke?",
"How do you and your brother make up after a fight?",
"What is something your brother always gets right?",
"How does your brother act when he is in a bad mood?",
"What did your brother do that made you laugh until you cried?",
"What is a promise you made to your brother?",
"If your brother was a character in a movie, who would he be?",
"What is the best gift you have ever given your brother?",
"What is the best gift your brother has given you?",
"What are three words to describe your brother?",
"What would your brother say about you if we asked him right now?",
"What is the funniest thing your brother does when he is sleepy?",
"Did you ever hide something from your parents together with your brother?",
"What is one memory with your brother you would never trade?",
"What is one thing your brother does better than you?",
"Who is the better cricket or gaming player, you or your brother?",
"What is one thing your brother is scared of?",
"How did your brother react the last time you were sick?",
"What is the funniest family trip memory with your brother?",
"What is a lesson your elder or younger brother taught you?",
"If you could give your brother one superpower, what would it be?",
"Have you ever worn your brother's clothes without asking?",
"What is the best advice your brother ever gave you?",
"What would your brother's dating profile say?",
"What is something you are proud of your brother for?",
"What is something that makes you want to hug your brother?",
"What is the one thing you would change about your brother? Be kind.",
"Do you and your brother share a secret language or code?",
"What is the funniest thing your brother has ever said to your parents?",
"How would you describe your relationship with your brother to a stranger?",
"What is the most thoughtful thing you have done for your brother?",
"What did you think about your brother when you were little?",
"How would your brother describe you in one word?",
"What tradition do you and your brother have?",
"What would you do if your brother forgot your birthday?",
"What is the funniest thing your brother does to get his way?",
"What is a childhood fear you shared with your brother?",
"What is a family story about your brother that always gets told?",
"What is your favourite song that you share with your brother?",
"What is your favourite game that you share with your brother?",
"What is your favourite tradition that you share with your brother?",
"What is your favourite dish that you share with your brother?",
"What is your favourite trip that you share with your brother?",
"What is your favourite movie that you share with your brother?",
"What is your favourite festival memory that you share with your brother?",
"What is your favourite prank that you share with your brother?",
"What is your favourite nickname that you share with your brother?",
"What is your favourite habit that you share with your brother?"
],
"sister": [
"What is your funniest memory with your sister?",
"What is the one thing your sister does that annoys you the most?",
"What is the best thing your sister has ever done for you?",
"Have you ever gotten your sister in trouble on purpose?",
"What is a secret you kept for your sister?",
"What is something you borrowed from your sister and never returned?",
"What is the biggest fight you ever had with your sister, and how did it end?",
"What is one thing you admire about your sister?",
"If your sister had a superhero name, what would it be?",
"What is your sister's most embarrassing moment that you witnessed?",
"What did you and your sister fight over most as kids?",
"What is the nicest thing your sister has said to you?",
"Have you ever blamed your sister for something you did?",
"What is a game you and your sister played for hours?",
"Which of your sister's habits do you secretly copy?",
"What is the funniest nickname you have for your sister?",
"What would you do if your sister needed help at 3 AM?",
"Who is the favourite child in your house, you or your sister, and why?",
"What did your sister teach you that no one else did?",
"What is the best prank you pulled on your sister?",
"What is the best prank your sister pulled on you?",
"Have you ever worn your sister's clothes or used her makeup without asking?",
"What is one thing you wish you could tell your sister but find awkward?",
"Would you trade places with your sister for a day? Why?",
"What is your sister's weirdest talent?",
"What song reminds you of your sister?",
"What is the most selfless thing your sister has done?",
"If you and your sister started a business, what would it be?",
"What is your sister's favourite food, and have you stolen it?",
"Which cartoon or movie did you watch the most with your sister?",
"How do you and your sister make up after a fight?",
"What is something your sister always gets right?",
"How does your sister act when she is in a bad mood?",
"What did your sister do that made you laugh until you cried?",
"What is a promise you made to your sister?",
"If your sister was a character in a movie, who would she be?",
"What is the best gift you have ever given your sister?",
"What is the best gift your sister has given you?",
"What are three words to describe your sister?",
"What would your sister say about you if we asked her right now?",
"Did you ever hide something from your parents together with your sister?",
"What is one memory with your sister you would never trade?",
"What is one thing your sister does better than you?",
"What is one thing your sister is scared of?",
"How did your sister react the last time you were sick?",
"What is the funniest family function memory with your sister?",
"What lesson did your elder or younger sister teach you?",
"If you could give your sister one superpower, what would it be?",
"What is the best advice your sister ever gave you?",
"What is something you are proud of your sister for?",
"What is something that makes you want to hug your sister?",
"Do you and your sister share a secret language or code?",
"What is the funniest thing your sister has ever said to your parents?",
"How would you describe your relationship with your sister to a stranger?",
"What is the most thoughtful thing you have done for your sister?",
"What did you think about your sister when you were little?",
"How would your sister describe you in one word?",
"What tradition do you and your sister have?",
"What would you do if your sister forgot your birthday?",
"What is a childhood fear you shared with your sister?",
"What is a family story about your sister that always gets told?",
"Which outfit of your sister do you love the most?",
"Who gets ready faster, you or your sister, and who takes forever?",
"What did you and your sister whisper about at night?",
"What is your sister's most used phrase?",
"What secret recipe or snack do you and your sister share?",
"What would you do if your sister got married tomorrow?",
"Who is the better dancer, you or your sister?",
"What is your favourite song that you share with your sister?",
"What is your favourite game that you share with your sister?",
"What is your favourite tradition that you share with your sister?",
"What is your favourite dish that you share with your sister?",
"What is your favourite trip that you share with your sister?",
"What is your favourite movie that you share with your sister?",
"What is your favourite festival memory that you share with your sister?",
"What is your favourite prank that you share with your sister?",
"What is your favourite nickname that you share with your sister?",
"What is your favourite habit that you share with your sister?"
],
"irl": [
"If you found a wallet with 10,000 rupees and an ID, what would you do?",
"Would you rather know the exact date you will die or how you will die?",
"If you could erase one invention from history, which one would it be?",
"You can only keep one app on your phone forever. Which one and why?",
"If you had to live in one era, past or future, which would you choose?",
"A friend asks if their new haircut looks good, and it does not. What do you say?",
"If you could swap lives with anyone for a week, who would it be?",
"You are given 24 hours and unlimited money, but you must spend it all on others. What do you do?",
"Would you take a job you love for less pay or a job you dislike for double?",
"If you saw your friend cheating in an exam, would you say something?",
"Which is worse: being broke but happy, or rich but lonely?",
"If you could have dinner with any three people, living or dead, who would they be?",
"You have the power to pause time for one hour a day. How do you use it?",
"If you were stuck on a deserted island with one person from this group, who and why?",
"Would you rather lose all your memories or never be able to make new ones?",
"You can only eat one cuisine forever. Which one?",
"If everyone in the world could read your mind for a day, what would be the most embarrassing thing they would find?",
"If your phone was left unlocked with a friend for an hour, how worried would you be?",
"You see a stranger crying on a bench. Do you approach them?",
"You can instantly learn any skill. Which one do you pick?",
"Would you rather be the smartest person in the room or the funniest?",
"Is it ever okay to lie to protect someone's feelings? Give an example.",
"What is your rule for lending money to friends?",
"You win a lottery of 1 crore. What are your first three actions?",
"If you could only talk or text for the rest of your life, which one would you give up?",
"If you could live without sleep, would you? What would you do with the extra time?",
"Which would you choose: a luxury trip alone or a budget trip with all your friends?",
"What is one law you would change in your country?",
"If you could un-send one message in your life, what would it be?",
"If a friend and a family member both needed help at the same time, how would you decide?",
"You find out a friend's partner is cheating. Do you tell them? Why or why not?",
"If a genie gave you three wishes but none could be for yourself, what would you wish for?",
"Which is more important in a friendship: honesty or loyalty?",
"What would you do if you were invisible for a day, and could not be caught?",
"If you were the school or office principal for a day, what rule would you add?",
"Which habit of yours would hurt the most if you had to give it up?",
"If you could teleport anywhere right now, where would you go and who would you take?",
"If you could master any language overnight, which one would it be?",
"What is a risk you took that paid off?",
"If you could rewind one year of your life, which year and why?",
"Would you rather be known for something great or be happy but unknown?",
"Which one would you choose: the ability to fly or the ability to be invisible?",
"How would you spend your last 24 hours on earth?",
"Which fictional world would you most like to live in?",
"If you could have any job for a day, what would it be?",
"Would you rather have a rewind button or a pause button for your life?",
"What is one thing you would do if no one judged you?",
"What is a rule you follow that others find strange?",
"What is the best life hack you have ever discovered?",
"You are in a lift with your boss or teacher and it stops. What do you talk about?",
"Would you rather always be 10 minutes late or 20 minutes early?",
"If you could tell your younger self one thing, what would it be?",
"If you could make one rule for this group chat, what would it be?",
"If you could only keep five things from your home, what would they be?",
"If you were a teacher for a day, what would you teach?",
"You are given a free flight ticket to anywhere, leaving in two hours. Where do you go?",
"If you could talk to animals, which one would you ask a question first, and what?",
"Which would you rather give up forever: social media or junk food?",
"If your life had a background score, what genre would it be?",
"What is the logic behind your favourite superstition, if any?",
"If you were a billionaire, what would be the first problem you would solve?",
"Which would you pick: a pet dragon or a pet robot?",
"If you were told a secret you must keep, but it harms a friend, what would you do?",
"What do you think is the most overrated thing in life?",
"What do you think is the most underrated thing in life?",
"If a stranger offered you 50,000 rupees to never use your phone for a month, would you accept?",
"If there were a time machine that goes only forward, how far would you go?",
"If you had to survive with one tool in a forest, which tool would you choose?",
"Would you rather have unlimited pizza for life or have unlimited ice cream for life?",
"Would you rather always speak in rhymes or always sing instead of speaking?",
"Would you rather be able to fly or be able to read minds?",
"Would you rather live without music or live without movies?",
"Would you rather lose your phone for a week or lose your wallet for a week?",
"Would you rather be famous but disliked or be unknown but loved?",
"Would you rather never use social media again or never watch a movie again?",
"Would you rather have a personal chef or have a personal driver?",
"Would you rather wake up at 4 AM every day or stay up until 4 AM every day?",
"Would you rather be the funniest person you know or be the smartest person you know?",
"Would you rather eat only sweets for a month or eat only spicy food for a month?",
"Would you rather travel to the past or travel to the future?",
"Would you rather fight one horse-sized duck or fight a hundred duck-sized horses?",
"Would you rather have a pause button for life or have a rewind button for life?",
"Would you rather live in a treehouse or live in a houseboat?",
"Would you rather never be stuck in traffic again or never wait in a queue again?",
"Would you rather be able to talk to animals or be able to speak every language?",
"Would you rather have a home theatre or have a gaming setup?",
"Would you rather skip every exam or skip every wedding function?",
"Would you rather be a superhero with a boring power or be a regular person with great luck?",
"Would you rather lose all your photos or lose all your contacts?",
"Would you rather have a monkey butler or have a robot dog?",
"Would you rather live in the mountains or live by the sea?",
"Would you rather meet your future self or meet your past self?",
"Would you rather be the best player in a team that always loses or be the worst player in a team that always wins?",
"Would you rather give up chai forever or give up coffee forever?",
"Would you rather have a free flight every month or have free food every day?",
"Would you rather be stuck in a lift with your crush or be stuck in a lift with your boss?",
"Would you rather always have to tell the truth or always have to lie?",
"Would you rather have super strength or have super speed?",
"Would you rather sing at a stranger's wedding or dance at a stranger's wedding?",
"Would you rather live without AC or heater or live without a fan or a cooler?",
"Would you rather read a book a day or watch a movie a day?",
"Would you rather be rich in your 20s or be rich in your 60s?",
"Would you rather have no homework ever or have no chores ever?",
"Would you rather only wear one colour forever or wear a different colour every day?",
"Would you rather cook for 50 guests or wash dishes for 50 guests?",
"Would you rather have dinner with a celebrity or have dinner with a historical figure?",
"Would you rather never sleep again or never eat again?",
"Would you rather live in a world with no phones or live in a world with no cars?",
"Would you rather get 1 crore today or get 10 lakhs every year for life?",
"Would you rather know all secrets or be able to keep all secrets?",
"Would you rather never feel cold or never feel hot?",
"Would you rather have a pet elephant or have a pet tiger?",
"Would you rather be a great singer or be a great dancer?",
"Would you rather spend a night in a haunted house or spend a night alone in a forest?",
"Would you rather read everyone's texts or have everyone read yours?",
"Would you rather be the main character in a movie or be the writer of a movie?",
"Would you rather wear socks with sandals forever or wear a raincoat on sunny days forever?",
"Would you rather always arrive early or always arrive in style?",
"Would you rather only communicate with memes or only communicate with emojis?",
"Would you rather never stub your toe again or never get a cramp again?",
"Would you rather be invisible at will or be able to freeze time?",
"Would you rather have a room full of books or have a room full of games?",
"Would you rather swim with sharks or skydive from a plane?",
"Would you rather give up spicy food or give up sweet food?",
"Would you rather have 10 close friends or have 1000 acquaintances?",
"Would you rather be a pro cricketer or be a movie star?",
"Would you rather live in a big city or live in a quiet village?",
"Would you rather eat a bug or drink a glass of vinegar?",
"Would you rather never have to study or never have to work?",
"Would you rather get unlimited data or get unlimited battery?",
"Would you rather lose your sense of smell or lose your sense of taste?",
"Would you rather live in Paris for a year or live in Tokyo for a year?",
"Would you rather only watch comedy or only watch thrillers?",
"Would you rather always have hiccups or always have a runny nose?",
"Would you rather have a time machine that works once or have a teleporter that works ten times?",
"Would you rather be able to sleep anywhere or be able to eat anything?",
"Would you rather fail a test you studied for or pass a test you never studied for?",
"Would you rather be a bird for a day or be a fish for a day?",
"Would you rather get a surprise party or plan a surprise party?",
"Would you rather spend a day without talking or spend a day without eating?",
"Would you rather have free movie tickets for life or have free pizza for life?",
"Would you rather live in a castle or live in a spaceship?",
"Would you rather be great at maths or be great at music?",
"Would you rather always wear a hat or always wear sunglasses?",
"Would you rather get lost in a big city or get lost in a forest?",
"Would you rather have a magic wand or have a magic carpet?",
"Would you rather find 500 rupees on the road or find a lost puppy?",
"Would you rather text first always or wait for the other person to text first?",
"Would you rather learn the guitar or learn the piano?",
"Would you rather speak in whispers for a week or speak in shouts for a week?",
"Would you rather carry a heavy bag all day or carry a balloon all day?",
"Would you rather take a cold shower daily or eat cold food daily?",
"What would you do if you woke up to find your phone had no network for a week?",
"What would you do if you found out your best friend is moving abroad tomorrow?",
"What would you do if you were given the chance to attend any concert for free?",
"What would you do if you won a trip for two and had to choose whom to take?",
"What would you do if you were locked out of your house at midnight?",
"What would you do if you were asked to give a speech with no preparation?",
"What would you do if you saw your crush ahead of you in a long queue?",
"What would you do if you were given a 5-minute head start in a treasure hunt?",
"What would you do if your best friend forgot your birthday?",
"What would you do if you found a puppy without an owner outside your house?",
"What would you do if you got stuck in the rain with no umbrella and a new phone?",
"What would you do if you could be an expert in any field overnight?",
"What would you do if you accidentally sent a funny meme to your boss?",
"What would you do if you were told you can have any pet but only one?",
"What would you do if you were stuck in a lift with a stranger for an hour?",
"What would you do if the power went out for a whole day?",
"What would you do if your friend asked you to lie for them?",
"What would you do if you were the only one who knew the answer in class and the teacher called you out?",
"What would you do if you got a surprise day off tomorrow?",
"What would you do if a stranger paid your bill at a restaurant?",
"What would you do if you were invited to a party where you know no one?",
"What would you do if you got a free ticket to space for one day?",
"What would you do if your phone fell in water?",
"What would you do if you received a mystery gift with no name?",
"What would you do if you were asked to teach a class tomorrow?",
"What would you do if you forgot your wallet at a restaurant?",
"What would you do if someone copied your exam answers?",
"What would you do if a friend asked you for a big loan?",
"What would you do if your favourite team lost in the final?",
"What would you do if your crush replied to your story?",
"What would you do if your internet stopped in the middle of an online exam?",
"What would you do if you had to cook for guests with nothing in the fridge?",
"What would you do if you found a hidden room in your house?",
"What would you do if you could take any famous person's job for a day?",
"What would you do if you won a free shopping spree for 10 minutes?",
"What would you do if a friend invited you to a trip you cannot afford?",
"What would you do if you were chosen to lead a group project with people you do not like?",
"What would you do if your friend's secret was told to you by mistake?",
"What would you do if you got lost in a new city with 5 percent battery?",
"What would you do if you could instantly become fluent in a language?",
"What would you do if you were given a free lifetime supply of one food?",
"What would you do if your teacher or boss said \"come to my cabin\"?",
"What would you do if your friend started dating someone you do not like?",
"What would you do if you found out your neighbour is a celebrity?",
"What would you do if you had to spend a night in a library?",
"What would you do if you found an old letter addressed to you from the future?",
"What would you do if you were stuck on a train with no food?",
"What would you do if your parents handed you the house keys for a week?",
"What would you do if a stranger asked for directions in a language you do not know?",
"What would you do if you got a free coaching class from your favourite teacher?",
"What would you do if you found 10,000 rupees in an old jacket?",
"What would you do if you were told the whole group is going on a surprise trip?",
"What would you do if you were handed a microphone at a wedding?",
"What would you do if you won a bet and could choose any dare for the other person?",
"What would you do if you were granted one day of no rules?",
"What would you do if you saw a friend being bullied online?",
"What would you do if you were nominated as the group's leader?",
"What would you do if you got a message from an unknown number saying \"I know your secret\"?",
"What would you do if you had to teach your grandparents to use WhatsApp?",
"What would you do if you were given 24 hours in a city you have never visited?",
"What would you do if you were chosen to be a judge on a talent show?",
"What would you do if you could pause a moment of your life and revisit it later?",
"What would you do if you got to name a new city?",
"What would you do if you found an old diary of yours?",
"What would you do if you were allowed to redo one decision?",
"What would you do if you could change one thing about this group?",
"What would you do if you were allowed one question to the universe?",
"What would you do if you were the last one awake in the house at 3 AM?",
"What would you do if you met your favourite athlete at a mall?",
"What would you do if you were invited to cook on a TV show?",
"What would you do if your pet started talking to you?",
"What would you do if a magical door opened in your room?",
"What would you do if you could replay your favourite day?",
"What would you do if you were given a free lifetime pass for any one app?",
"What would you do if your friend made a joke about you in public?",
"What would you do if you were asked to be the best man or maid of honour?",
"What would you do if you heard your name being whispered in a quiet class?",
"What would you do if you had to choose between a trip and a gadget?",
"What would you do if you accidentally liked a very old photo of someone you follow?",
"Would you ever try bungee jumping? Why or why not?",
"Would you ever live without a phone for a month? Why or why not?",
"Would you ever eat a very spicy dish for a prize? Why or why not?",
"Would you ever sing on a stage in front of 1000 people? Why or why not?",
"Would you ever go on a solo trip to a new country? Why or why not?",
"Would you ever speak to a stranger on a long journey? Why or why not?",
"Would you ever donate your favourite belonging to someone in need? Why or why not?",
"Would you ever dye your hair a bright colour? Why or why not?",
"Would you ever take a cold shower for a week? Why or why not?",
"Would you ever become a vegetarian for a month? Why or why not?",
"Would you ever try a strange food from another country? Why or why not?",
"Would you ever learn a new language in a month? Why or why not?",
"Would you ever go without sweets for a year? Why or why not?",
"Would you ever spend a night in a haunted house? Why or why not?",
"Would you ever give a speech at a school or college? Why or why not?",
"Would you ever adopt a stray animal? Why or why not?",
"Would you ever try stand-up comedy? Why or why not?",
"Would you ever ride a camel or an elephant? Why or why not?",
"Would you ever go on a road trip with no plan? Why or why not?",
"Would you ever share your password with your best friend? Why or why not?",
"Would you ever move to another city for a dream job? Why or why not?",
"Would you ever teach something to a kid for a week? Why or why not?",
"Would you ever try a new hobby every month? Why or why not?",
"Would you ever volunteer at a shelter for a day? Why or why not?",
"Would you ever start a small business? Why or why not?",
"Would you ever forgive a friend who broke your trust? Why or why not?",
"Would you ever apologise first after a fight? Why or why not?",
"Would you ever show your childhood photos to the group? Why or why not?",
"Would you ever read your old diary out loud? Why or why not?",
"Would you ever wake up at 5 AM every day for a month? Why or why not?",
"Would you ever do a 24-hour digital detox? Why or why not?",
"Would you ever let your best friend choose your outfit? Why or why not?",
"Would you ever join a dance class? Why or why not?",
"Would you ever stay at a hotel alone? Why or why not?",
"Would you ever walk 10 km in a day? Why or why not?",
"Would you ever go to the cinema alone? Why or why not?",
"Would you ever cook a meal for the whole family? Why or why not?",
"Would you ever ask for a discount in a store? Why or why not?",
"Would you ever take a stranger's photo when they ask? Why or why not?",
"Would you ever go back to school for a week? Why or why not?",
"Would you ever swap phones with a friend for a day? Why or why not?",
"Would you ever help a friend move house? Why or why not?",
"Would you ever try meditation for 30 days? Why or why not?",
"Would you ever jump into a swimming pool in your clothes? Why or why not?",
"Would you ever plan a surprise for a friend? Why or why not?",
"Would you ever go on a camping trip without a phone? Why or why not?",
"Would you ever say a poem at a family dinner? Why or why not?",
"Would you ever take a one-month break from social media? Why or why not?",
"Would you ever call an old friend today? Why or why not?",
"Would you ever write a letter to a teacher? Why or why not?"
]
};
